### ISSUE TITLE
Being able to see the tool/block you're holding in your hand in 3rd person

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1447] opened 2016-12-05 20:25 UTC
The title says it all, also being able to see What other people in multiplayer Hold in there hands would be nice

**Comment by sofar** [comment] 2016-12-05 20:34
`wieldview` mod provides this option, it's part of `3d_armor`.

**Comment by tobyplowy** [comment] 2016-12-05 20:44
@sofar yeh but it should be added To default

**Comment by Fixer-007** [comment] 2016-12-05 20:49
I also thought about opening the same issue, it is basic gameplay feature to me.

**Comment by tobyplowy** [comment] 2016-12-05 20:54
@Fixer-007 that's why I opened it in the first place (i thought with all the conversations about the female player model it would be the correct time to open this)

Bdw it really is a basic gameplay feature especially in PvP

**Comment by stujones11** [comment] 2016-12-05 21:24
Unfortunately, there is no 'clean' way to accomplish this at present. My wieldview mod requires a custom model and only works well for certain tools, while my wield3d mod _should_ be the proper solution to this, it still suffers from attachment glitches which appear to be mostly upstream issues.

**Comment by tobyplowy** [comment] 2016-12-08 10:21
This needs to be coded In the engine I think

**Comment by stujones11** [comment] 2016-12-08 19:07
> This needs to be coded In the engine I think

It really does not matter where you code it, the problem is with irrlicht.

**Comment by paramat** [comment] 2017-01-14 05:06
More of an engine issue then a MTGame issue.

**Comment by stujones11** [comment] 2017-02-03 17:45
I do not understand the insistence of the 'Engine change needed' label because this is doable by mods already only it doesn't work so well because of either irrlicht or the model itself. What is clear is that for once, it is not the fault of minetest engine.

Such a mod may of course benefit for some engine changes but I do not think that something as game specific as this should be handled by the core,

**Comment by Fixer-007** [comment] 2018-01-31 18:59
Not sure why it is non-trivial, since it is done via mods for years, just merge it and fix that 180deg reversal bug ::)

**Comment by paramat** [comment] 2018-01-31 20:16
Actually this seems primarily an engine issue as hacking it in Lua is probably not optimal.
Please open a request there if there isn't one.

**Comment by stujones11** [comment] 2018-02-04 18:22
Nothing is being 'hacked' in lua. The attachment is handled by the engine & irrlicht already. The one thing the engine might can provide is a callback for wield-item changes. This type thing is game specific and should be done by the game. The engine has no reason to care how the player model looks.

**Comment by Fixer-007** [comment] 2018-02-04 20:03
At least embarrassing "Non-trivial" tag was removed :)

**Comment by paramat** [comment] 2018-02-04 20:40
Ok, i don't know much about how this would be implemented.

**Comment by stujones11** [comment] 2018-02-04 21:23
> Ok, i don't know much about how this would be implemented.

IMO it would be best handled by the `player_api` mod, wield-item changes would need to be polled or at least rate limited to avoid spamming servers with mouse-wheel events.

**Comment by Ezhh** [comment] 2018-02-14 18:34
Why close this? It's definitely something that would be a nice addition.

**Comment by Fixer-007** [comment] 2018-02-14 21:39
https://i.imgur.com/ZMvYxAU.jpg

**Comment by stujones11** [comment] 2018-02-14 22:32
FWIW, I am still investigating the glitching issues and I think I have narrowed it down either the model weights are not correctly exported or there is problem with the b3d loader code of Irrlicht.

While it seems there are ways to prevent the glitch by ensuring the main `body` bone of the model is never at the precise zero rotation (0,0,0). I could possibly do this to the player model as a last resort but I would much rather get to the root of the problem.

Maybe a different model format would be better, however, directx has problems of its own so going back to that is not option IMO, unless anything has changed since I last tried it.

**Comment by paramat** [comment] 2018-03-27 07:03
Let's move discussion to #2097

**Closed by paramat** 2018-03-27 07:03 UTC
Labels: Feature request
