### ISSUE TITLE
Lua crash if opening door with slab or stair

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1700] opened 2017-04-12 22:16 UTC
Engine 1399678, 12 apr 2017 minetest_game (new slab/stair placement code)

To reproduce:
+ place a door
+ open it while holding slab or stair

Error:
>ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'stairs' in callback item_OnPlace(): ...minetest\bin\..\games\minetest_game\mods\stairs\init.lua:31: attempt to perform arithmetic on field 'y' (a nil value)
stack traceback:
...minetest\bin\..\games\minetest_game\mods\stairs\init.lua:31: in function <...minetest\bin\..\games\minetest_game\mods\stairs\init.lua:20>

**Comment by SmallJoker** [comment] 2017-04-13 07:37
@MarkuBu

**Comment by MarkuBu** [comment] 2017-04-13 07:53
Huh?

**Comment by MarkuBu** [comment] 2017-04-13 08:01
Ah, it only happens if you click on the upper half of the door. Let me think about that

**Comment by MarkuBu** [comment] 2017-04-13 08:23
I'm not sure if this is correct. If you place something to an other node only one value in pointed_thing differs. If I place something at the upper half of the door I have two different values

```
{
	type = "node",
	above = {
		y = 3,
		x = -246,
		z = -1602
	},
	under = {
		y = 2,
		x = -246,
		z = -1603
	}
}

In this example y and z are different

**Comment by MarkuBu** [comment] 2017-04-13 09:57
The first question: are there other nodes where this can happen?

The second question: should I fix this in pointed_thing_to_face_pos or should that be fixed in the engine?

**Comment by paramat** [comment] 2017-04-13 10:50
Under and above should only have 1 component differing because they're either side of a face.
2 values differing means they are diagonal from each other.

**Comment by paramat** [comment] 2017-04-13 11:16
```
{
	type = "node",
	above = {
		y = 3,
		x = -246,
		z = -1602
	},
	under = {
		y = 2,
		x = -246,
		z = -1603
	}
}
```
How do these positions relate to the door? This may be a clue.
The door top nodebox is not pointable, the door base node has a selectionbox that covers the entire door, so above / under may give diagonal positions due to this: perhaps under is the base node but above becomes the position in front of the upper part of the selectionbox?

**Comment by MarkuBu** [comment] 2017-04-13 11:23
I'll check that. I seems that the problem is in the `for` loop. The y coordinate is not added to `oc`. Maybe I can fix that there

**Comment by paramat** [comment] 2017-04-13 11:40
Well above and under being diagonal will break fine pos anyway because the player is not pointing at a face.

**Comment by MarkuBu** [comment] 2017-04-13 11:47
If I punch a door from the top everything works. Just FYI

It only seems to affect the y coordinate. So as a workaround I may just check if y is in oc and if not, I just add it to prevent the crash

**Comment by MarkuBu** [comment] 2017-04-13 11:52
This code after the for loop fixes the crash

```
	if not oc["y"] then
		oc[#oc + 1] = "y"
	end
```

I even can place slabs/stairs to the upper half of the door while holding sneak key

**Comment by MarkuBu** [comment] 2017-04-13 12:05
https://github.com/minetest/minetest/pull/5581

**Comment by paramat** [comment] 2017-04-13 14:36
@MarkuBu 
```
{
	type = "node",
	above = {
		y = 3,
		x = -246,
		z = -1602
	},
	under = {
		y = 2,
		x = -246,
		z = -1603
	}
}
```
How do these positions relate to the door? This will be useful to know.

**Comment by MarkuBu** [comment] 2017-04-13 14:56
@paramat see https://github.com/minetest/minetest/issues/5580#issuecomment-293918452

**Comment by paramat** [comment] 2017-04-19 01:08
https://github.com/minetest/minetest/pull/5581 merged.

**Closed by paramat** 2017-04-19 01:08 UTC
Labels: Bug, Engine change needed
