### ISSUE TITLE
Falling nodes on top of new doors are falling

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest_game#923] opened 2016-03-14 09:56 UTC
To reproduce, place a falling node above a new door (sand, or even more visible, snow). The node is falling, and so is not diggable either. Moreover, this creates an entity which is used for static purposes only.

**Comment by paramat** [comment] 2016-03-14 13:34
@sofar

**Comment by sofar** [comment] 2016-03-14 14:28
Try the patch in #926

**Comment by sofar** [comment] 2016-03-14 16:51
I'll have to dig deeper. I can't make the top part walkable since then you can't walk *through* a door.

**Comment by sofar** [comment] 2016-03-14 22:24
I think I can make it ```buildable_to```. Reading the code this may just fix it.

**Comment by sofar** [comment] 2016-03-15 06:10
Please test #928. Make sure to re-place all your doors.

**Comment by paramat** [comment] 2016-03-21 06:31
928 merged

**Closed by paramat** 2016-03-21 06:31 UTC
Labels: Bug

**Comment by everamzah** [comment] 2016-03-22 12:50
Placing a door under a pine tree with snow, and digging the pine needles above the door results in a stuck entity.

![screenshot_20160322_084952](https://cloud.githubusercontent.com/assets/1761623/13952135/12a559f2-f00b-11e5-895d-7c49db135d9a.png)

**Comment by sofar** [comment] 2016-03-22 18:25
I'll check this, but it sounds oddly similar to the sand block stuff. Did you update and place new doors?

**Comment by kilbith** [comment] 2016-03-22 19:15
Can't reproduce that.

**Comment by sofar** [comment] 2016-03-22 19:38
@everamzah can you verify you were running latest minetest_game and try to reproduce again?
