### ISSUE TITLE
Add background statbar icons

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2676] opened 2020-05-11 19:54 UTC
So #6030 was just fixed. This means Minetest has now support for background statbar icons.
The logical continuation is to add these icons into MTG to make the statbars more readable.

This means adding `heart_gone.png` and `breath_gone.png`.

See <https://github.com/minetest/minetest/issues/6030> for nice icons you can use.

**Comment by Wuzzy2** [comment] 2020-05-11 19:55
Relevant Minetest PR: https://github.com/minetest/minetest/pull/9462

**Comment by sfan5** [comment] 2020-05-13 17:25
duplicate of #2660, which is your own issue

**Closed by sfan5** 2020-05-13 17:25 UTC
Labels: Feature request, Textures
