### ISSUE TITLE
beds: player stucks if bed is destroyed before leaving it

### ISSUE THREAD

**Issue by xeranas** [minetest/minetest_game#836] opened 2016-02-12 17:57 UTC
Steps to reproduce issue:
- Add `enable_bed_night_skip = false` to `minetest.conf` file
- Start game, wait for night
- ~~Change player view to 3rd person (F7 key)~~ (reproducable in all views)
- Lay on bed
- Destroy bed by punshing

Result:
Player cannot move, stuck in air

**Comment by Napiophelios** [comment] 2016-02-13 01:46
it seems to work fine for me.

you have to right click on the bed
to get out of bed

**Comment by xeranas** [comment] 2016-02-13 09:58
@Napiophelios you need test with minetest_game cloned from this branch not subgame which is included into 0.4.13 Minetest. Configuration `enable_bed_night_skip` not exist in minetest_game released with 0.4.13 Minetest.

**Comment by xeranas** [comment] 2016-02-13 14:08
@Napiophelios seems you right. However bug still valid as bed is destructible and if you destroy bed before leaving it you pretty much stuck in air.

**Comment by sofar** [comment] 2016-03-06 07:30
Can't reproduce. The formspec that displays when you are in a bed makes you stand up again if you exit that formspec.

I did:

- enable_```bed_night_skip = false```
- start game, ```/time 0```
- enter bed
- log second player on, punch bed away under first player
- first player: hit ```esc``` on formspec, now walking normally

**Comment by Napiophelios** [comment] 2016-03-06 22:29
Confirmed in singleplayer mode.
-enable_bed_night_skip = false
-enter bed
-destroy bed with axe....get stuck

You will have to place another bed somewhere else and right click it to get unstuck.

**Comment by sofar** [comment] 2016-03-06 22:34
I wonder if this is a singleplayer only issue... I certainly didn't try with singleplayer.

**Comment by Napiophelios** [comment] 2016-03-06 22:51
Probably so, there is no formspec with singleplayer.

**Comment by paramat** [comment] 2018-02-14 06:43
@sofar any ideas for a fix?

**Comment by sofar** [comment] 2018-02-14 06:50
How do you destroy a bed while you are in it?

Seems like an obvious issue - the bed is diggable while the player is attached to it (in singleplayer).

Simple fix: refuse to allow any bed to be dug if a player is attached to it. That should prevent it in multiplayer too. Fix would be somewhere in a `on_dig` callback?

**Comment by HybridDog** [comment] 2018-02-14 08:35
There's a can_dig field in the node definition: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L4876

**Comment by paramat** [comment] 2018-05-30 19:50
Bug confirmed in singleplayer.

**Comment by paramat** [comment] 2018-06-01 00:02
Seems low priority as a player is highly unlikely to dig their own bed except through curiosity, and if they get stuck re-entering the world fixes the bug.

**Comment by bell07** [comment] 2018-06-01 22:37
The bug can happen in multiplayer too, more often. A player can destroy the bed of other player.
But the difference in multiplayer there is no stuck because the formspec is forced to the player:
```
	if not is_sp then
		update_formspecs(false)
	end
```
And if formspec is closed, the player stay up.

The issue seems funny, but I think it should be fixed even if not critical for multiplayer
![image](https://user-images.githubusercontent.com/4731334/40866158-7651e54c-65fc-11e8-87c9-665300c8c296.png)

**Comment by paramat** [comment] 2018-06-02 19:06
Yes i have no objection to a fix.
I actually think breaking the bed from under another player is ok to allow :)

**Comment by paramat** [comment] 2018-06-19 21:07
#2126 merged.

**Closed by paramat** 2018-06-19 21:07 UTC
Labels: Bug, Low priority
