### ISSUE TITLE
Boats sink through world if underwater, dependent on collisionbox size

### ISSUE THREAD

**Issue by adrido** [minetest/minetest_game#1137] opened 2016-06-13 15:25 UTC
If your boat gets under water, e.g. by driving through a water-fall the boat starts to sink. But it does not stop at the ground, you will sink through stone, and other massive nodes too.

This is reproducible with stable Minetest 0.4.14 and latest Minetest Game.
This does not happen with Minetest Game 0.4.14

**Comment by paramat** [comment] 2016-06-13 19:10
This may be lua lag, were you using any mods? try disabling all mods.

**Comment by adrido** [comment] 2016-06-14 02:09
This happens with plain Minetest Game. No additional mods. On singleplayer and on server.

**Comment by paramat** [comment] 2016-06-14 03:54
Thanks, will investigate.

**Comment by paramat** [comment] 2016-06-14 03:56
The only change since release is https://github.com/minetest/minetest_game/commit/fc902a77de1e54b85076b2a0682fb30dd70359dc
And i now seem to remember that the collisionbox needed to be how it was to avoid this, could you try reversing that change?

**Comment by adrido** [comment] 2016-06-14 04:27
Yes, If I revert the commit fc902a77de1e54b85076b2a0682fb30dd70359dc boats behave like before. They working correct then.

**Comment by paramat** [comment] 2016-06-14 16:39
Great thanks, i'll revert that soon.

**Comment by sofar** [comment] 2016-06-14 21:07
I'm OK with the workaround in #1139, but this is a bug in the `step` code that really needs fixing instead. Please don't close this bug after the workaround has been merged.

**Comment by paramat** [comment] 2016-06-14 21:08
Ok yes it's a weird behaviour that could do with fixing.

**Comment by t4im** [comment] 2016-07-06 09:31
Yea, it appears it is making several [hard coded assumptions](https://github.com/minetest/minetest_game/blob/master/mods/boats/init.lua#L169) about boat height. Change the collision box and with that center of mass/position and you mess those up.

**Comment by paramat** [comment] 2018-05-17 02:11
I'm not sure this is a bug in boats code, seems more an engine bug and should possibly be moved there.

**Comment by appgurueu** [comment] 2021-02-10 21:46
Is this still reproducible?

**Comment by appgurueu** [comment] 2022-01-17 13:14
Can't reproduce. Boats are pushed up if inside water (side note: players often take advantage of this to build fast "water elevators").

**Closed by appgurueu** 2022-01-17 13:14 UTC
Labels: Bug, Possible close
