### ISSUE TITLE
[Bug] Beds/CSM : Servers easy crashable through use of CSM

### ISSUE THREAD

**Issue by dopik** [minetest/minetest_game#2021] opened 2018-01-16 08:58 UTC
EDIT by paramat: removed CSM code.
/////////////////

This little CSM essentially crashes most servers when you die. I assume this happens, because of this (out of minetest_game/mods/beds/functions.lua ):
if enable_respawn then

```
	-- respawn player at bed if enabled and valid position is found

	minetest.register_on_respawnplayer(function(player)

		local name = player:get_player_name()

		local pos = beds.spawn[name]

		if pos then

			player:setpos(pos)

			return true

		end

	end)

end
```

I think the respawn functions gets trigered, but before it is actually executed the player has already left.
This of cource leaves player as a nil value wich results in a crash on all servers running beds and having damage enabled.
Not tested for consistency.

**Comment by raymoo** [comment] 2018-01-16 21:22
I feel like this is an engine issue since respawn callbacks are called on invalid players. Maybe disconnected players should be removed at the end of a server step instead of immediately (I don't know if that is actually what happens or causes the problem).

**Comment by paramat** [comment] 2018-01-16 22:50
Maybe related to death formspec having been moved to CSM? Which should not have been done i feel.
Try adding lines to the start of the beds function:
```
if not player then
    return false
end
```

**Comment by Ezhh** [comment] 2018-01-16 23:44
Duplicated the crash... 

Tried adjusting beds mod. No change.

Removed beds mod... Still crashes on death.

Just to be absolutely sure, switched to a test subgame that has never had beds... Still crash on death. This isn't MTG related.

**Comment by paramat** [comment] 2018-01-16 23:54
Moving to engine, don't post the CSM code anywhere, we'll deal with this privately.

**Closed by paramat** 2018-01-16 23:54 UTC
Labels: Bug, Engine change needed, High priority

**Comment by paramat** [comment] 2018-01-17 00:07
Tests indicate this doesn't actually crash a server.

**Comment by Ezhh** [comment] 2018-01-17 00:09
Tested on two live servers (both my own of course) and it kicks the player, regardless of whether beds are in use on the server, but doesn't crash the server itself.

**Comment by paramat** [comment] 2018-01-17 00:10
Devs can contact me privately to see the CSM code.

**Comment by red-001** [comment] 2018-01-17 14:14
@dopik could you provide information on how you tested this? Only was able to duplicate this when the user with the mod is the one hosting the server and the server exiting in that case in expected behavior.

**Comment by dopik** [comment] 2018-01-17 17:14
Well, I wrote this to help me trick a mod on a server.
The server essentially rewrote the bed respawn mechanic wit another one in the home mod wich gets executed 2 seconds after the one in beds. While testing (on said server, wich I wasn't hosting) the server crashed as I tried it. Tested it a second time, to get sure that it didn't just happen by chance at the same time -> crashed in the same way. Because it crashed immediatly and not 2 seconds after my death, I assumed that it was caused by the beds mod.
After thinking over it I noticed that this probably could be done with more things than just respawning and that it probably isn't just caused by beds. Could explain part of what @Ezhh  experienced

**Comment by Ezhh** [comment] 2018-01-17 17:22
I realised yesterday after posting I wasn't being very accurate, since it wasn't really a crash.

I've done more tests today, including on a local test server with a second client connecting, and nothing I try can crash the server.

If this only happens on one specific server, it makes me wonder what they've done there to allow it. Could you maybe test on Dark Lands Survival to see if that crashes? (I'm the admin, and give permission for the test in this case). I can't get the server there to crash, so we may as well double check I'm testing it correctly.

**Comment by dopik** [comment] 2018-01-17 17:29
Tested it, seems as it didn't crash the server.
Maybe this actually only crashes that specific server. Maybe it's really only that 2 seconds delay thing wich causes this.

**Comment by Ezhh** [comment] 2018-01-17 17:33
I see your joins and parts in the log and can confirm no crash.

**Comment by red-001** [comment] 2018-01-17 21:38
sounds like a faulty mod, if there is a whole 2 second delay this could even be caused by more normal user interaction (respawning and closing minetest), I suggest adding a check to see if the user if still online after the 2 second timer.
