### ISSUE TITLE
Furnace doesn't start burning again when mover adds fuel

### ISSUE THREAD

**Issue by StaceyRieck** [minetest/minetest_game#2123] opened 2018-05-16 12:31 UTC
If a furnace runs out of fuel (but still contains an item to be smelted), it will not start burning again after fuel has been added by a mover. The user must remove the fuel and add it again (or add other fuel) for the furnace to become active again.

Reproduce the issue:

- Place furnace and add to it stack of items to be smelted.
- Add in small amount of fuel (not enough to smelt anything completely)
- Wait for it to run out of fuel (should say "inactive" and "Fuel: Empty")
- Use a mover to add more fuel to furnace.
- Furnace now contains fuel and object to be smelted, but does not resume smelting. Still says fuel is empty. 
- Remove fuel to inventory and add it again. Furnace resumes.

**Comment by paramat** [comment] 2018-05-16 17:03
Could you link to the code of the 'mover' you are using?

**Comment by rubenwardy** [comment] 2018-05-16 17:18
This is because the mover doesn't trigger a callback as it's not a player. The correct fix is for the mod itself to trigger the node timer

**Comment by raymoo** [comment] 2018-05-22 02:01
@paramat Maybe an API for moving items around that doesn't require players and has callbacks

**Comment by paramat** [comment] 2018-05-22 18:39
Well i mean, are we doing something wrong or is this mod's responsibility, from rubenwardy's comment ot looks like this is mod's responsibility.

**Comment by raymoo** [comment] 2018-05-22 18:42
@paramat It's not a bug if that's what you mean.

**Comment by paramat** [comment] 2018-05-22 21:59
Yes it seems a mod issue, closing.

**Closed by paramat** 2018-05-22 21:59 UTC
Labels: Low priority, Possible close
