### ISSUE TITLE
New shelf overlays don't line up

### ISSUE THREAD

**Issue by ghost** [minetest/minetest_game#1359] opened 2016-10-31 06:34 UTC
@sofar are you having a laugh?  :)

![screenshot_20161031_023050](https://cloud.githubusercontent.com/assets/1761623/19845951/2920b99a-9f12-11e6-8252-3932e79c0e1c.png)
![screenshot_20161031_023054](https://cloud.githubusercontent.com/assets/1761623/19845952/292c9d64-9f12-11e6-86b5-ed056f622fa4.png)

![big1](https://cloud.githubusercontent.com/assets/1761623/19845989/6aec7706-9f12-11e6-94ec-2bb17e4a2f60.png)
![big2](https://cloud.githubusercontent.com/assets/1761623/19845988/6aeac8ca-9f12-11e6-8639-09e330253dc0.png)

In my own personal opinion, 0acd9a2ccb2f766de5237964a5da046148075d79 is distasteful.

**Comment by everamzah** [comment] 2016-10-31 07:33
Additionally, not all books are shaped the same.

![big2a](https://cloud.githubusercontent.com/assets/1761623/19847103/bc87d5bc-9f1a-11e6-9714-a5d5221b1ef7.png)

Undoubtedly, the same could be said for vessels.

**Comment by DS-Minetest** [comment] 2016-10-31 08:20
these are there because Sam put so often the same shape of book there
its damage caused by using it
=> the shape doesn't have to suit

**Comment by sofar** [comment] 2016-10-31 22:27
I see no issue.

The backdrop is suggestive, and meant as such. On top of that, mods that change book shapes can provide alternative textures, and so can texture packs. A texture pack could entirely remove the effect as well.

**Comment by Ferk** [comment] 2016-10-31 23:22
I don't think they necessarily need to match the same shape as the item.
But maybe the contrast could be reduced so that they fade in the background and don't interfere too much with the icon.

**Comment by Wuzzy2** [comment] 2016-11-01 01:03
It seems the background has an offset of exactly 1 pixel to the right, compared to the item image.

**Comment by paramat** [comment] 2016-11-01 05:21
Looks bad and i had not thought about alternative shaped books. I should have opposed this, sorry.

**Comment by Rui-Minetest** [comment] 2016-11-01 12:23
I think a icon should be hidden when its slot has a item.
http://pastebin.com/JPCJusrG

**Comment by stujones11** [comment] 2016-11-02 19:56
@Rui-Minetest I am sure it is workable but perhaps a little overkill for such a simple feature. I would be happy enough if they were aligned correctly with the matching images and darkened down slightly to be less noticeable with non-matching images.

**Comment by everamzah** [comment] 2016-11-02 20:34
The issue, I find, is that the background overlay, which is always present, doesn't necessarily match some item -- or that it may match one item, but not another.  Basically, there are different kinds of vessels (group:vessel) and books (group:book).

**Comment by stujones11** [comment] 2016-11-02 22:54
The books and vessels in mtg would look pretty much okay with my above recommendations. The images supplied by third party mods that do not fit are the fault of the modder, IMO

**Comment by everamzah** [comment] 2016-11-03 05:00
The images posted in the issue are not third party mods.  https://github.com/minetest/minetest_game/issues/1359#issue-186215159

**Comment by everamzah** [comment] 2016-11-03 05:01
Also, it may not matter one iota, but that doesn't negate the fact that things don't line up.  I may be particular here, but I'm not wrong.  *laugh*

**Comment by paramat** [comment] 2016-11-03 13:01
I also don't like how a new overlay has to be made for a new book texture, if lining-up is wanted.
I might make a PR to revert this.

**Comment by stujones11** [comment] 2016-11-05 20:38
> I might make a PR to revert this.

@paramat I think that is probably the best idea for now, maybe place-holders could be added as a more generic feature using @Rui-Minetest's method of only displaying them on empty slots. Either way the current look is completely unacceptable.

**Comment by paramat** [comment] 2016-11-06 05:39
This has added some complexity, and extra textures, for no good reason and looking worse as a result.

**Comment by Wuzzy2** [comment] 2016-11-06 13:40
> This has added some complexity, and extra textures

This is a valid reason to reject almost anything. xD Also, there were far bigger PRs with far more textures. This PR included only 2. I think this argument is pretty weak.

> for no good reason

No. The reason was to make the purpose of the slots a little bit more obvious. IMO it is not obvious that a bookshelf is *only* for storing books. In the real world, a bookshelf is just a shelf and you can store other stuff than just books in it. Of course the player might find out eventually, but the idea here is “being nice to the user”.

> looking worse as a result

OK. This is a valid argument, but only against this particular implementation. What would be the *right* way to do it graphically?

I think the biggest problem is the “one pixel off” problem. This problem seems to come from the engine and there is nothing Minetest Game can do about it (for now). And there is no way to pixel-perfectly align formspec elements. Minetest formspec coordinates are a big mess anyway. :-(

> We don't need icons for furnace either, the flame above the lower slot makes it clear the lower slot is for fuel and the upper for what is being smelted.

How can you claim that you know that it “makes it clear”? You are not a Minetest Game newbie. You should ask newbies if you want to be sure. I can recall when I first played Minetest-c55 (many MANY years ago), I would probably not have understood what the furnace slots mean if I would not have read the wiki. I agree, the flame is an important improvement but I am not sure if it would have been enough. I guess the furnace might need a different approach to make it more obvious, I don't think icons alone would help. But anyways, the furnace is a bit off-topic here.

**Comment by paramat** [comment] 2016-11-06 14:17
Many MTGame devs like this so i doubt it will be reverted and i don't think i'll try.
I've never seen a complaint about how a newbie suffered due to lack of slot icons, it only takes a few secinds to learn through trial and error. Generally i think you have a slight tendency to imagine newbie problems and then try to add unnecessary spoon-feeding idiot-proof clutter.
Please can the slot textures have less contrast?

**Comment by Wuzzy2** [comment] 2016-11-06 15:00
> Please can the slot textures have less contrast?

This is an excellent idea! See PR #1370. :-)

I think the darker icon color practically fixes this issue as the effect of the icons not lining up pixel-perfectly is now too subtle to be noticed.

**Comment by paramat** [comment] 2016-11-07 14:40
#1370 merged.
#1372 if merged will fix this issue.

**Comment by rubenwardy** [comment] 2016-11-15 01:41
#1372 was merged

**Closed by rubenwardy** 2016-11-15 01:41 UTC
Labels: Bug
