### ISSUE TITLE
Player model: bones are oriented incorrectly

### ISSUE THREAD

**Issue by Rogier-5** [minetest/minetest_game#1376] opened 2016-11-08 08:27 UTC
The player model has its bones oriented incorrectly, so that when `minetest.set_bone_position()` is used to reposition them, using angles of 0°, they point in strange directions. IMO, the bones should be oriented in such a way that using angles of 0° makes them point in their default directions.

This problem is especially applicable to the arms, as the orientation of the bones does not allow them to be rotated in an intuitive manner, requiring higher math to convert the desired orientation (e.g. pointing left, forward, up, at an angle of 45°, ...) to the actual position vector that makes this happen.

IMO the following code should position all limbs (approximately) in their default positions. However, the player will look as in the image below. (Note: I don't know whether a negative offset is _supposed_ to be to the right. Maybe the entire model is mirrored as well)

```lua
object:set_bone_position("Body", {x=0, y=0, z=0}, {x=0, y=0, z=0})
object:set_bone_position("Head", {x=0, y=6.75, z=0}, {x=0, y=0, z=0})
object:set_bone_position("Arm_Right", {x=-2, y=6.75, z=0}, {x=0, y=0, z=0})
object:set_bone_position("Arm_Left", {x=2, y=6.75, z=0}, {x=0, y=0, z=0})
object:set_bone_position("Leg_Right", {x=-1, y=0, z=0}, {x=0, y=0, z=0})
object:set_bone_position("Leg_Left", {x=1, y=0, z=0}, {x=0, y=0, z=0})
```

![bones_a0](https://cloud.githubusercontent.com/assets/6202053/20091306/646cb9d2-a592-11e6-8e6c-c77c2d2e0642.png) ![bones_a1](https://cloud.githubusercontent.com/assets/6202053/20091307/6470e4b2-a592-11e6-996a-6214b25d81a0.png)

The picture is mostly self-explanatory. Note in particular:
- The entire model is raised by about 0.33 nodes. I would expect that the body remains in its default position when using position 0,0,0
- The body is rotated 180° (or is it mirrored ? - see my remark above), so that its back is now facing forward
- The arms are not vertical. This means that some small angle is needed to make them vertical. This adjustment will vary with the other angles used, and will have to be recomputed if they are changed. If the arm must be rotated around its axis, the computations for the adjustments become even more complex, as the bone does not align with the axis of the arms.

The following code will make the player look normal (although it may still be slightly misadjusted):
```lua
object:set_bone_position("Body", {x=0, y=-3.3, z=0}, {x=0, y=180, z=0})
object:set_bone_position("Head", {x=0, y=6.75, z=0}, {x=0, y=180, z=0})
object:set_bone_position("Arm_Right", {x=-2, y=6.75, z=0}, {x=180, y=0, z=-8.5})
object:set_bone_position("Arm_Left", {x=2, y=6.75, z=0}, {x=180, y=0, z=8.5})
object:set_bone_position("Leg_Right", {x=-1, y=0, z=0}, {x=180, y=0, z=0})
object:set_bone_position("Leg_Left", {x=1, y=0, z=0}, {x=180, y=0, z=0})
```

As I didn't have a texture with cape, I don't know how the cape is oriented by default.

**Comment by sofar** [comment] 2016-11-08 21:06
This is most likely due to some weird bone offset/size thing coming from blender or the b3d exporter. No idea why, though.

**Comment by stujones11** [comment] 2016-11-08 21:29
I do know that the arm bones are angled slightly away from the body which makes attachements a bit tricky to align, however,  I am not sure about the other issues or even if anything can be done about them  model-wise.

**Comment by Rogier-5** [comment] 2016-11-08 23:30
It would be nice if at least the angled arms could be 'fixed'. That is certainly something that should be done in blender.

As for the 180° rotation (or mirroring, whatever it is) issues: I don't have any significant blender experience, but if those who do consider it hard to do, or maybe just too much to ask from random model designers to get right, maybe there's a way to solve this in minetest ?

At startup, minetest could (hopefully ?) query the model, or Irrlicht, for the bones' default coordinates. It could then use these as a baseline, and adjust the return values of `get_bone_position()` and the arguments given to `set_bone_position()` so that, as far as mods are concerned, the default position and orientation of the body are always 0,0,0 and 0,0,0. The limbs' default orientations would also be adjusted to be 0,0,0 (but not their relative positions of course).

**Comment by stujones11** [comment] 2016-11-09 18:10
> It would be nice if at least the angled arms could be 'fixed'.

I have tried to do that before but the results were not good. The problem is that if you move the arm tops outward then the shoulder pivots in the wrong place, ultimately disconnecting from the body. If you move the arm bottom inwards then attached items are not located correctly in the hand. The only solution I could think of is add a tiny shoulder bone between the arm top and the body.

> maybe there's a way to solve this in minetest ?

Using the default bone positions as a baseline sounds like the way I would have expected it to be anyway but this really belongs in the other issue.

**Comment by stujones11** [comment] 2016-11-09 18:49
I've just taken a closer look at the model and noticed that the head bone is in fact rotated 180° to the body. That is likely the mirroring issue and should be easy enough to remedy. Fixing the arms, however, would require redoing al the affected animation frames.

**Comment by Rogier-5** [comment] 2016-11-09 23:33
> Straightening the arms, however, would require redoing all the affected animation frames.

A played around a bit using blender, and it seems that changing the arms could be easy enough. The animation seems to be unaffected by the other changes I made (head and arms). ...if only I managed to export the model: the export script exports the model sideways, so that its right side is facing forward. If I rotate the model in blender, then blender still shows the animation the way it should be, but minetest gets it wrong.

[character.zip](https://github.com/minetest/minetest_game/files/582184/character.zip)

**Comment by stujones11** [comment] 2016-11-11 17:45
> The animation seems to be unaffected

Notice how the arms are twisting during the walk and mine animations, this previously compensated for the angle and needs to be removed from the key-frames. I do like how you have lowered the arm tops so that it can pivot outward without disconnecting from the body, however, I think it still needs some slight adjustment.

**Comment by Rogier-5** [comment] 2016-11-11 20:47
I fixed the arms. I think they now move in the same way as the original model.
I also added a modified sam texture with cape, so that the cape can be seen as well.

@stujones11 How dow you mean 'slight adjustment' ? Could you describe / elaborate ?

If you (or anybody) manage to export it to b3d so that it works in minetest, please post the b3d file. I still don't manage export a b3d file that makes the player look the same in minetest as it does in blender :-(

[character.zip](https://github.com/minetest/minetest_game/files/586722/character.zip)

**Comment by stujones11** [comment] 2016-11-12 15:05
> How dow you mean 'slight adjustment' ? Could you describe / elaborate ?

I am not really sure to be honest, it just looks a bit weird how the shoulder seem to drop if you extend the arms sideways but there is probably nothing you can do about it and it doesn't effect the stock animations besides 'Lay'

Regarding export, be sure to use ether the exporter included in the minetest repo or the supertuxcart b3d exporter. That latter produces a slightly smaller binary but you will need to manually unlink the textures to avoid irrlicht warnings.

**Comment by Rogier-5** [comment] 2016-11-13 07:45
> or the supertuxkart b3d exporter.

Thanks! That one works. I _was_ using the one from the minetest repo...

And no warnings whatsoever

> it just looks a bit weird how the shoulders seem to drop

It looks OK to me. The shoulders are lower than before, but IMO they don't drop. Or maybe you mean that one side goes down while the other side of the shoulder goes up ? Previously, all of the shoulder went up, and it looked like he was shrugging. 

Left = before, right = after:

![screenshot_20161113_000527](https://cloud.githubusercontent.com/assets/6202053/20242703/ac55546c-a938-11e6-8113-e1d3eb7bc0cd.png) ![screenshot_20161113_001521](https://cloud.githubusercontent.com/assets/6202053/20242693/5a4531b0-a938-11e6-9e68-e00ce1f64301.png)

And pointing sideways is *much* better:
![screenshot_20161113_000500](https://cloud.githubusercontent.com/assets/6202053/20242698/8520c3d6-a938-11e6-9bbb-185beb351117.png)![screenshot_20161113_000722](https://cloud.githubusercontent.com/assets/6202053/20242699/85274a8a-a938-11e6-8cae-650f3e61406a.png)

Pointing forward:
![screenshot_20161113_001242](https://cloud.githubusercontent.com/assets/6202053/20242710/f5259a9e-a938-11e6-9a2a-c53fcd1e1570.png)![screenshot_20161113_000921](https://cloud.githubusercontent.com/assets/6202053/20242709/f51f67aa-a938-11e6-9cf4-fcb36392f93c.png)

The one thing I don't manage to solve is the fact that the model rotates 180° after setting one bone. It may be a b3dexport bug, or an irrlicht bug. Or the model is incorrect.: when I select 'view front', it shows me the back side.

[character.zip](https://github.com/minetest/minetest_game/files/587512/character.zip)

**Comment by Ferk** [comment] 2016-11-13 12:43
> it doesn't effect the stock animations besides 'Lay'

@Rogier-5 did you check the Lay animation?

**Comment by stujones11** [comment] 2016-11-13 14:55
I agree that image 2 and 3 look better, I am not so sure about the first one but it's okay, I guess. There do still seem to be some slight twisting issues, evident in the first example.

![arm](https://cloud.githubusercontent.com/assets/3710749/20246519/4902b92c-a9b0-11e6-8ace-ff45711bdb51.png)

You should remove (zero) the 'roll' from the arm bones in edit-mode if you have not already done so, I have not yet had a chance to look at your latest model.

**Comment by Rogier-5** [comment] 2016-11-13 18:14
For the record: lay animation before and after. IMO before it looks like sam is shrugging:

![screenshot_20161113_182106](https://cloud.githubusercontent.com/assets/6202053/20247588/331f6a90-a9d0-11e6-88ab-4f983419a56a.png) ![screenshot_20161113_183240](https://cloud.githubusercontent.com/assets/6202053/20247589/3324488a-a9d0-11e6-9329-bf22ae5e9a3b.png)

I agree that the new 'animation' is not optimal either, but I don't think it is possible to do better, except at the expense of the arm dynamics.

>```
WARNING[Main]: Irrlicht: Could not open file of texture: character.png
```

Ah. _That_ warning...
I updated the export script, and it seems they are gone now.

> reduce the arm thickness by an imperceptible amount

Good idea. unfortunately, It's not yet obvious to me how to achieve that. Maybe I'll figure it out... In the mean time, don't hold your breath.

**Comment by paramat** [comment] 2016-11-14 07:26
Screenshots look good. The arm should obviously be rotating around the centre of the 'shoulder cube': a point on the arm centreline and 2 pixels from the end.

**Comment by paramat** [comment] 2016-11-15 13:45
I now notice the current arm is too high when digging, due to it's rotation point.

**Comment by Rogier-5** [comment] 2016-11-17 09:45
PR Created. See #1392

**Comment by paramat** [comment] 2016-11-18 01:21
> reduce the arm thickness by an imperceptible amount

I don't think that's necessary, by default the arms are never in this position, and if they are the breathing animation will be moving the shoulder back and forth anyway, avoiding z-fighting.

**Comment by stujones11** [comment] 2016-11-18 19:28
It would seem that the z-fighting (or whatever it was) is not present in the lay animation pictured above so unlikely to be an issue.

**Comment by paramat** [comment] 2016-11-25 03:12
#1392 merged.

**Closed by paramat** 2016-11-25 03:12 UTC
Labels: Request
