### ISSUE TITLE
Trapdoors float over slabs

### ISSUE THREAD

**Issue by An-dz** [minetest/minetest_game#545] opened 2015-06-19 18:06 UTC
If somehow possible, make the trapdoors work like the slabs so one can use it in the upper part of a node. This would allow the use over a slab without making it float half node in the air.

**Comment by RHRhino** [comment] 2015-06-19 18:14
You have to create at least two new nodes 1) slab + trapdoor closed on the ground and 2) slab + trapdoor open on the ground 

If you want to rotate them or put them on walls you have to create 2 more nodes for each rotation - that might be too many new nodes for minetest_game. It would be better if you create it as a mod and put it on the forum.

**Comment by C1ffisme** [comment] 2015-06-20 01:24
I think that think would be a good idea.

**Comment by nanepiwo** [comment] 2015-06-25 02:18
This should be added, along with signs on fences and slabs, etc. The problem is a non-hacky way to implement this... What would happen if you dug the slab+trapdoor node? Would you get both items back? Would the slab stay but you get a trapdoor in your inventory?

**Comment by paramat** [comment] 2015-08-01 00:07
-1. What's the use of a trapdoor over a slab? This is just the expected behaviour because a slab occupies the entire node, so anything placed above floats. I feel this is unnecessary and complex.

**Comment by Sokomine** [comment] 2015-08-10 03:57
I think this refers to the way trapdoors can be placed. If it where possible to mount them to a node from below so that they open *downwards*, that would look considerably better in combination with slabs. Else an opened trapdoor extends halfway over the slabs.
@An-dz: check the hatches in my cottages mod and see if they do what you wish for.
It would also be good to make trapdoors *climbable* so that they produce less problems if used in combination with ladders.

**Comment by Ferk** [comment] 2015-09-21 21:33
Imho, trapdoors look good as they are.
But making them climbable sounds like a good idea. After all it's only natural for someone to be able to cling on a trapdoor and climb it.

**Comment by Fixer-007** [comment] 2016-01-10 23:52
+1, right now trapdoors have very limited position selection

**Comment by paramat** [comment] 2016-01-11 20:08
:-1:  Complexity and npt much needed.

**Comment by sofar** [comment] 2016-01-15 08:46
#787 allows full rotation for trapdoors, which addresses the top comment - "allows a trapdoor to be placed against the top of the node".

**Comment by paramat** [comment] 2016-01-20 22:50
#787 merged.

**Closed by paramat** 2016-01-20 22:50 UTC
Labels: feature request

**Comment by 0-afflatus** [comment] 2016-01-30 19:10
Little afterthought: if we were going to do this then all doors should be able to be positioned mid-node so they line up with fences, bars and panels. All of which breaks the KISS principle.

**Comment by sofar** [comment] 2016-01-30 20:14
Putting a trapdoor with length 1 mid-block would cause it to extend into adjacent blocks when opening.

But maybe @0-afflatus  can make one that splits into two halves when opening?

**Comment by 0-afflatus** [comment] 2016-01-30 22:11
@sofar we seem to be crossing wires, perhaps I should turn the irony level down or at least use emojis.
