### ISSUE TITLE
Visual regression after indexed images merge

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1397] opened 2016-11-19 14:27 UTC
I'm confident enough that this https://github.com/minetest/minetest_game/commit/af3c91862cd1ca0ee5865845ea5ddeab3b9f680a caused visual bugs in minetest, I've noticed it at least on grass, rails, regression starts at middle distance and also depends on your yaw. This has something to do with LOD.

**To experience this bug enable "Mipmapping" and use latest minetest_game as of Nov 18**

Examples: https://i.imgur.com/GZJ2Le3.png , https://i.imgur.com/V6yNlB0.png

I'm at 681d127, I've checked few days old minetest_game and it has no such problem.

AMD/ATI HD6870 / Win7 / latest supported driver

**Comment by est31** [comment] 2016-11-19 14:37
I think this is an engine bug, or a driver or irrlicht bug.

**Comment by paramat** [comment] 2016-11-19 18:12
What shader settings / mip mapping etc. settings?

**Comment by paramat** [comment] 2016-11-19 18:32
I get this with green grass when mipmappng is on (shaders and all else off).
Also:

![screenshot_20161119_182753](https://cloud.githubusercontent.com/assets/3686677/20457590/7734974a-ae86-11e6-9362-2d082f77f10f.png)

I suspect the auto-indexing, will revert.

**Comment by Fixer-007** [comment] 2016-11-19 18:32
It is not only grass, it got worse for some other blocks like rails when LOD kicks in. 
**To experience this bug you need to enable mipmapping.**

**Comment by paramat** [comment] 2016-11-19 18:34
I suggest reverting the texture change and slowly converting them one by one in Gimp.

**Comment by rubenwardy** [comment] 2016-11-19 18:51
Agreed - but it's best not to commit them all individually (because commit spam)
Although the cause should probably be found

**Comment by rubenwardy** [comment] 2016-11-19 18:55
A quick google finds this: https://www.opengl.org/wiki/Common_Mistakes#Paletted_textures
Not sure if relevant - I've never explored OpenGL's intricacies

**Comment by paramat** [comment] 2016-11-19 19:28
I won't commit them individually.

**Comment by sofar** [comment] 2016-11-19 20:34
I've seen this, but I think it was on an Intel GPU. I can't reproduce this on NVIDIA. Sadly, I have no Intel GPU available right now to confirm.

**Comment by sofar** [comment] 2016-11-19 20:35
BTW, if this is really an issue, we need to convert *all* (ALL) textures from indexed to RGB(A).

Just reverting the ones in this set isn't going to help. Any texture with alpha will cause breakage, not the ones in this set.

My advice: don't revert this, instead, if any texture has alpha, make it RGBA.

**Comment by paramat** [comment] 2016-11-19 21:03
Yes my GPU is Intel integrated graphics.

> Any texture with alpha will cause breakage

So why have we not had this bug before? we have had indexed textures with alpha for years.

**Comment by paramat** [comment] 2016-11-19 21:11
For aspen leaves, looks like the auto-conversion changed the colour of the transparent pixels, so that when opaque leaves are used the wrong colour shows. These will require reverting.

**Comment by paramat** [comment] 2016-11-19 22:20
Discussion http://irc.minetest.net/minetest-dev/2016-11-19#i_4745383

**Comment by paramat** [comment] 2016-11-19 23:32
```
22:26 paramat        ha i've just noticed the bug is present for dry grass, we just didn't notice it before
22:26 paramat        dry grass has been buggy for a year
22:26 paramat        with mipmap on
22:30 paramat        hm resaving as i mentioned didn't fix them though
22:34 paramat        resaving as RGBA does fix them
22:37 paramat        sofar ^ RGBA is necessary after all, it fixes the bug with or without 'save colours from transparent pixels'
22:37 paramat        i just fixed dry grass this way
22:39 paramat        so all indexed alpha textures must be converted to RGBA
22:40 paramat        this can be partly done by reverting the alpha textures just changed (copy them into a PR from an older version)
22:41 paramat        then we can change the others later
```

**Comment by paramat** [comment] 2016-11-19 23:33
Once #1398 is merged this issue must stay open until all indexed alpha textures are converted to RGBA.

**Comment by paramat** [comment] 2016-11-19 23:49
#1398 merged.

**Comment by paramat** [comment] 2016-11-20 03:38
Before we continue converting, any adice on what to enable out of these when exporting?

![screenshot from 2016-11-20 03 27 50](https://cloud.githubusercontent.com/assets/3686677/20460143/967cbe60-aed2-11e6-8f83-2a22f5587a5e.png)

I guess for leaves textures that become opaque we will need 'save background colour' and/or 'save colour values from transparent pixels'? Otherwise neither are needed?

**Comment by paramat** [comment] 2016-11-20 04:51
" Save background color
If your image has many transparency levels, the Internet browsers that recognize only two levels, will use the background color of your Toolbox instead. Internet Explorer up to version 6 did not use this information."
So that's not needed then.

For leaves textures this is probably needed:
" Save color values from transparent pixels
With this option is checked, the color values are saved even if the pixels are completely transparent."

**Comment by paramat** [comment] 2016-11-20 04:54
I might soon get to work on converting the remaining indexed alpha textures to RGBA.

**Comment by paramat** [comment] 2016-11-22 03:36
https://github.com/minetest/minetest_game/issues/1397#issuecomment-261747102

Now i'm geting visual bugs with mip-mapping enabled even with textures converted to RGBA and with all combinations of 'save background colour' and 'save colour values from transparent pixels', so i doubt this linked comment is correct.

**Comment by rubenwardy** [comment] 2016-11-23 00:18
I think this would be better solved in the engine or Irrlicht. Or worked-around

**Comment by paramat** [comment] 2016-11-23 00:54
Yes it seems an engine / graphics issue.

**Comment by Fixer-007** [comment] 2016-11-30 22:10
I still slightly see whitish part on grass plane directed to me.

**Comment by paramat** [comment] 2016-12-05 08:14
#1441 merged.

**Comment by paramat** [comment] 2018-05-17 02:04
Note that mip-mapping causes visual bugs. We have made 'allfaces optional' nodes RGBA so all is done on the MTG side of things.

**Closed by paramat** 2018-05-17 02:04 UTC
Labels: Bug, Engine change needed, Non-trivial, Textures
