### ISSUE TITLE
make bookshelf craftable with written books

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest_game#1466] opened 2016-12-20 17:13 UTC
wouldnt it be more logical to craft a bookshelf with written books, too?

**Comment by C1ffisme** [comment] 2016-12-20 21:29
If the bookshelf gives you back the book in the bookshelf inventory, then I can agree with that.

**Comment by paramat** [comment] 2016-12-21 02:20
The written books would disappear on crafting :-1:

**Comment by DS-Minetest** [comment] 2016-12-21 14:14
ill close this since @SmallJoker opened the PR

**Comment by C1ffisme** [comment] 2016-12-21 15:40
@DS-Minetest No, keep this open. The issue is closed when the PR is closed.

**Comment by DS-Minetest** [comment] 2016-12-21 16:17
ok

**Comment by DS-Minetest** [comment] 2017-03-03 23:10
Now that @paramat closed the PR, should I close this issue, too?

**Comment by paramat** [comment] 2017-03-03 23:41
Closing.

**Closed by paramat** 2017-03-03 23:41 UTC
Labels: Request / Suggestion
