### ISSUE TITLE
Can dig and place blocks while sleeping

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#2317] opened 2019-02-21 00:46 UTC
If you sleep in bed, you can dig and place blocks around you and otherwise interact with the world.
This is possible in singleplayer.

Version: 0.4.17.1.

**Comment by paramat** [comment] 2019-02-21 02:25
Duplicate of #1951 

Lying in bed is not sleeping, if you were sleeping you wouldn't be concious of the world around you, the 'sleeping' happens during the unconcious skip to the next day. So i can't see a problem with interaction.
Reopened that issue to consider if interaction should be disabled while in bed.

**Closed by paramat** 2019-02-21 02:25 UTC
