### ISSUE TITLE
Doors are not converted (since lbm intro?)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1062] opened 2016-04-29 15:36 UTC
MT Version: 46fd114
MTG Version: 5cd4b5

I have a world copy saved by me from 0.4.12 server, before that lbm thing doors converted fine to new ones, now nothing is converting.
World: [Just Test.zip](https://github.com/minetest/minetest_game/files/242731/Just.Test.zip)

Related to https://github.com/minetest/minetest_game/pull/1040 ?

**Comment by sofar** [comment] 2016-04-29 16:39
re-run the LBMs by removing the `lbm` related lines from env_meta.txt, and the doors are converted properly.

**Comment by Fixer-007** [comment] 2016-04-29 16:47
Tried, at first it helped but as I moved further from the spawn conversion stopped. :/ Can this be mitigated somehow?

**Comment by sofar** [comment] 2016-04-29 16:56
duplicate of https://github.com/minetest/minetest/issues/4050

**Comment by paramat** [comment] 2016-04-29 18:52
See possible explanation in https://github.com/minetest/minetest/issues/4050

**Closed** 2016-04-29 18:55 UTC
Labels: Bug, Needs engine-change
