### ISSUE TITLE
Discussion of clientside-option connected glass

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest_game#2326] opened 2019-03-06 00:34 UTC
In response to the engine issue, I figured I'd open a more specific issue for the game specific problem.

Right now connected glass is ambiguous, and this confuses players and modders alike. This issue is to discuss what the best non-ambigous solution to this.

I would vote that glass and obsidian glass blocks should both be connected, while their respective panes be left unconnected to give builders options.

My secondary vote is that obsidian glass should be connected, while normal glass should not.

**However, this really should come down to what is the most popular look builders are going for so as to not disrupt it too much.**

**Comment by paramat** [comment] 2019-03-06 07:53
:-1: for both suggestions, they would both be extremely unpopular.

However i agree with considering in this issue what we could do concerning connected glass, if you change the issue title we can discuss here.
For background on this see the engine issue https://github.com/minetest/minetest/issues/8290

**Comment by Ezhh** [comment] 2019-03-06 10:32
Also :-1: for both suggestions. Why should someone sign in to a server or singleplayer world that has had the option set one way or the other for potentially years suddenly find the appearance of things changed? Your preference or my preference or anyone's preference aren't necessarily going to match and not everyone would understand how to change it back.

Also inconsistent behaviour if changing this would be a terrible thing. (Also just to note: I mostly dislike connected obsidian glass because you are effectively left with invisible walls, while this isn't an issue with normal glass, so I'd want the exact opposite of you.)

**Comment by paramat** [comment] 2019-03-07 04:12
This issue is now for discussion of what to do, if anything, about clientside-option connected glass.

As discussed in the engine issue, i consider using 'glasslike framed optional' for MTG glass was a mistake. For each glass type there should have been nodes provided, one with 'glasslike' drawtype, one with 'glasslike_framed' drawtype.

If we decide to try and put things right in MTG, currenly it seems to me the approach would be:
Keep existing glass nodes unchanged.
For each glass type, add 2 new nodes, one with 'glasslike' drawtype, one with 'glasslike_framed' drawtype.
Encourage builders to use the new ones.

**Comment by benrob0329** [comment] 2019-03-07 05:17
The idea of never being able to change existing behavior in MTG is really hurting it's development.

Games change with time, if existing servers and worlds want to keep old behavior they can. Nobody said that Nyan Cats shouldn't be removed because they had been used, server owners had just been told to either get rid of them or use a mod. But when a bad decision can cause confusion and ambiguity, we can't correct because..someone might like the old behavior and can't be bothered to use a mod? This isn't sneak code, it's all very changeable Lua. We aren't removing blocks, we're properly defining how they are supposed to look.

Adding more nodes would likely cause extra confusion and cruft, and leaving the original nodes in place only leaves the problem while making things more confusing. I'm sorry but sometimes a visual change will need to happen for the sake of better defining the game.

Not wanting to make a decision because some people (who can very much use a mod that would keep it consistent for the entire server!) is going to lead to stagnation on issues which need a line drawn.

**Comment by Linuxdirk** [comment] 2019-03-07 09:22
> The idea of never being able to change existing behavior in MTG is really hurting it's development.

Quoted for emphasis.

**Comment by Ezhh** [comment] 2019-03-07 11:18
You realise that part of discussing how to fix an issue is to identify the problems with the suggested fixes? I see issues with your specific suggestions. That doesn't mean no one can think of another approach, or that one of those approaches won't still be considered.

> Keep existing glass nodes unchanged.
> For each glass type, add 2 new nodes,

No, that's not a fix, that's hiding the issue at absolute best. Servers will still have the original glass, and if we remove that from creative inventory, players will try to match the new glass to what they see as the old glass, which won't match for everyone. That sounds like a huge mess.

Any actual fix means two (not three) nodes. Previous nodes need to convert definitely to one of the two options, and a new node needs to be added for the second option.  The issue are:
- will it cause too much disruption? (there will be unhappy people no matter what).
- which way round should it be? Here some data about how many people change the options would be great, but I'm not sure how to get this. I suspect most people go with the default.

**Comment by paramat** [comment] 2019-03-08 07:56
We realise how much your suggestions will upset players and break the mods, games and servers that rely on how these nodes are now. The situation is a somewhat messy and i agree with that, but it's not an urgent situation with no other solution, so the upset is not justified.

MTG is constrained in many ways by how it is and how much relies on it being the way it is, inevitably this hurts it's development. It is full of mess that i would love to change but can't. That's why we keep asking for new games, because MTG will always be messy.
If you're unhappy write a new game or fork MTG and do things a better way.

> if existing servers and worlds want to keep old behavior they can.

No, server owners would be furious if they suddenly had to code custom versions of MTG to not break their server. We support the MT community and don't cause large unnecessary breakages, as this is.
> we can't correct because..someone might like the old behavior and can't be bothered to use a mod?

> who can very much use a mod that would keep it consistent for the entire server!

That's a misrepresentation of the disruption and server owners also don't want to use mods to fix an unnecessary and breaking of MTG.
> we're properly defining how they are supposed to look.

No we're not, you personally are trying to dictate how they should look based on your own taste, and forcing one half of players to have glass the way they don't like it. The way they look now is exactly as the builders intended (that is, the players, including the builder, decide).
//////////////////////////////

> Any actual fix means two (not three) nodes. Previous nodes need to convert definitely to one of the two options, and a new node needs to be added for the second option.

I would personally be ok with that, my suggestion was because i was concerned about the disruption and upset caused by one half of all glass nodes having to be replaced, that could be very unpopular.
Having 3 nodes is not ideal i admit. I'm wondering which is the lesser evil.

**Comment by benrob0329** [comment] 2019-03-08 15:21
To quote the last line of the first post

>However, this really should come down to what is the most popular look builders are going for so as to not disrupt it too much.

I'm not bitching over my specific tastes not being used, I'm complaining about not wanting to draw any lines to reduce ambiguity, other than adding an unnecessary amount of nodes. **I don't care what nodes end up being connected and what nodes do not.** My suggestions were purely for the sake of discussion, thus I called them "my vote", and explicitly stated that it should be down to what change will cause the least disruption in visible appearance.

**Comment by paramat** [comment] 2019-03-21 02:30
Moving some engine discussion here.

If we make all glass one drawtype, and provide the 2 drawtypes and not the clientside optional drawtype, we could make rebuilding easier by adding a no-wear tool that swaps one drawtype for the other (TumeniNodes idea). I would support that to help the transition.

**Comment by benrob0329** [comment] 2019-03-21 03:46
Would it change all glass connected to it? Because otherwise having to manually select every glass node would be a huge pain. (Perhaps two versions of it, one of which requires a priv to use? Or a rightclick/leftclick difference?)

**Comment by Ezhh** [comment] 2019-03-21 10:29
In case this approach is helpful, I double checked how I did this on RC, because as far as I'm aware, that's the only example we have of this being changed on a server after it was long established and many things built. (I only changed it for obsidian glass, but the same approach could go for any other type.)

1. The current glass was changed to never be connected, instead of optionally connected.
2. I created an _alt node which was optionally connected.

This means people who don't select connected notice no difference, while those who usually do may need to adjust some of their builds to get the desired results. This caused very little disruption on the server (I would guess because a lot of players never realise the option exists). Of course it may upset some people, but there is no approach that doesn't carry that risk.

The tool idea just sounds weird and strange. We'd be adding something that basically makes very little sense to the game.

**Comment by Fixer-007** [comment] 2019-03-21 17:55
Having an option for connecting glass-like blocks will be very useful.

**Comment by paramat** [comment] 2019-03-22 02:16
Personally i'm fine with not having a tool for this, i was just concerned about players complaining about the amount of rebuilding they have to do =) 
Such a tool could always be added as an optional mod if a server desires it.

**Comment by paramat** [comment] 2019-07-29 19:48
I'm in the mood to do this now.
I suggest (similar to what Ezhh has done on her server):

For each glass node:
Make current glass never connected, "glasslike".
Add a new node that is always connected, "glasslike_framed".

So, no nodes would remain that are cientside-optionally connected, as these would just perpetuate the problem.
A tool for quick conversion from "glasslike" to "glasslike_framed" can then be provided as an optional mod, and i would be happy to create this.
Anyone very unhappy with the change can use a mod to override glass back to it's previous drawtype.
A forum post would be made to explain all this.

@Ezhh would you be able to support this?

**Comment by Ezhh** [comment] 2019-08-01 15:03
I'd like to know whether those who originally raised/supported this feel that would be an acceptable solution.

**Comment by benrob0329** [comment] 2019-08-01 15:21
Adding a "Glass Framer" or similarly named tool which bulk-converts glass to `glasslike_framed` and back would be a decent solution IMO. But normal glass should always be dropped to avoid messy crafting and inventory madness.

**Comment by paramat** [comment] 2019-08-01 21:45
I would also be ok with having the conversion tool provided by the game, but Ezhh wasn't keen on this. Just as long as it is clearly provided somehow.

**Comment by Ezhh** [comment] 2019-08-06 09:03
Sorry, but I am really against dropping normal glass from inventories. I don't want to need to place one thing (especially something as common as glass) then manually change it. I want to be able to place the thing I actually want to build with.

**Comment by paramat** [comment] 2019-08-06 21:34
Ah ... i certainly don't suggest only having 1 type of glass and have to convert it after placement. I disagree with benrob0329's apparent suggestion that both types of glass should drop normal glass.
My thoughts about a conversion tool are only about making it easier for players to convert existing glass in builds into framed glass, after this change.

My suggestion is (from post above):
> For each glass node:
Make the existing glass never connected, "glasslike" drawtype.
Add a new node that is always connected, "glasslike_framed" drawtype.

**Comment by DS-Minetest** [comment] 2019-08-07 13:17
I wonder if a change in such a controversial topic, that is actually just about some minor optical difference, is even worth the effort.
(I personally never had any problems with the current situation when playing the game. I just use the setting to chose the glass type that I think is generally more pretty and I doubt that this differs greatly from building to building.)

**Comment by benrob0329** [comment] 2019-08-07 14:41
At this point I'm beginning to feel that it is not worth the effort. Any fix that is merged will be unsatisfactory to someone, and servers can always use a mod to fix this in whatever way they feel necessary.

**Comment by paramat** [comment] 2019-08-07 21:52
Also see the engine issue for more discussion buried in there somewhere https://github.com/minetest/minetest/issues/8290

@sfan5 could you confirm whether you disapprove of making a change?
Waiting for more core dev input, @SmallJoker ?

**Comment by sfan5** [comment] 2019-08-08 08:48
Not having read the preceding discussion:
I'd like to have connected glass in MTG by default. (which also means I support mt8290)
If this is not liked individually, connected glass can be disabled. If this is not liked by a server owner, they can use a mod to rectify that.

If I'm missing something that makes this solution not viable, please point it out.

**Comment by SmallJoker** [comment] 2019-08-08 16:56
I have a hard time understanding what you actually want to change.

1) Either you want to drop the `_optional` part in the glass drawtype definition
2) Duplicated glass nodes: framed and plain glass
3) Change the default for `framed_optional` (engine issue)
4) ???

Could someone be so nice and provide some visuals of how they imagined it?

Some graphics for comparison:
![grafik](https://user-images.githubusercontent.com/1497498/62721765-39e28b00-ba0d-11e9-9f6b-d8d9eb830264.png)

**Comment by benrob0329** [comment] 2019-08-08 17:01
@SmallJoker the engine issue was to change the default setting, but that spawned this issue to drop `_optional` in MTG, which brought up whether glass should be connected or not, which then had a compromise suggested of having both connected and non-connected glass nodes in MTG.

**Comment by paramat** [comment] 2019-08-08 22:10
sfan5,
> I'd like to have connected glass in MTG by default using framed_optional.
The default is set in the engine, and MTG glass is already 'framed optional', so https://github.com/minetest/minetest/issues/8290 does everything you want.

Because you thumbed-up https://github.com/minetest/minetest_game/issues/2326#issuecomment-519127848 i was trying to clarify if you disagreed with my suggestion https://github.com/minetest/minetest_game/issues/2326#issuecomment-516136382

You need to read the discussions to know what i am proposing, which is https://github.com/minetest/minetest_game/issues/2326#issuecomment-516136382
However, wait until i open a new clearer issue.

SmallJoker,
> I have a hard time understanding what you actually want to change.

Assuming that's directed to me, i'm asking about your opinion of my suggestion here https://github.com/minetest/minetest_game/issues/2326#issuecomment-516136382
However, wait until i open a new clearer issue.

Anyway, this has become confusing because the engine issue and this issue are not actually about what i (and Ezhh too as far as i know) are suggesting. A new issue is needed which i might open.

The original request of this issue is disapproved by Ezhh and myself so closing.

**Closed by paramat** 2019-08-08 22:10 UTC
Labels: Discussion, Request / Suggestion

**Comment by benrob0329** [comment] 2019-08-08 22:57
Yeah sorry, this issue is a mess. It was supposed to be a discussion issue about MTG's glass drawtype _with_ some of my own suggestions to start the discussion, but it's spiraled into a big mix of things and needs a clearer issue made as paramat has said.

**Comment by paramat** [comment] 2019-08-08 23:04
Specific issue #2434
