### ISSUE TITLE
Gameplay, Hunger

### ISSUE THREAD

**Issue by Luraktinus** [minetest/minetest_game#2004] opened 2018-01-02 11:27 UTC
I really would like to have a hunger bar. It would be more a "game" if there is some goal.

**Comment by benrob0329** [comment] 2018-01-02 14:34
It would have to last a few days (which is realistic) so you can actually get food, since only grasslands have grass to plant wheat.

I would also recommend tying it into how far the player walked, that way sprinting (reduced fast mode) drains hunger.

**Comment by paramat** [comment] 2018-01-02 17:12
Duplicate of #853 
Has been discussed a lot, engine changes may be needed.

**Closed by paramat** 2018-01-02 17:12 UTC
Labels: Feature request

**Comment by Luraktinus** [comment] 2018-01-02 23:14
why an engine change? there is a mod for it... just merge the mod...

**Comment by rubenwardy** [comment] 2018-01-02 23:15
> engine changes may be needed.

Not any more, since attributes were added
