### ISSUE TITLE
Chest remains open

### ISSUE THREAD

**Issue by RichardTry** [minetest/minetest_game#2791] opened 2020-12-07 18:06 UTC
If you open a chest and quickly open another chest (maybe another formspec, but don't work with furnace), first chest menu close, but node remains open.
![screenshot_20201207_205212](https://user-images.githubusercontent.com/16964020/101387627-c0440100-38cf-11eb-8875-eb52eb23c1eb.png)

**Comment by paramat** [comment] 2020-12-10 19:49
Possible duplicate of #2031

**Closed** 2020-12-10 19:50 UTC
Labels: Bug, Duplicate
