### ISSUE TITLE
TNT blows item entities into/through nodes

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest_game#483] opened 2015-04-04 18:01 UTC
![screenshot_20150404_125337](https://cloud.githubusercontent.com/assets/9893266/6993883/19ab8642-daca-11e4-8977-b6ed167d3eea.png)

Two ways to solve : 

- Put all exploded blocks into a bone-like block (cheap, but also stops lag)
- Change the engine to make entities potentially avoid being inside nodes. (At least, in a way that allows modding capability. Whether or not an entity gets out of nodes or not should be settable.)

**Comment by ShadowNinja** [comment] 2015-04-07 03:40
IIRC the root cause is that entities just poll their current position to check if they're inside a solid node and stop if so, but TNT pushes items too fast for them to stop themselves before they've already gone too far.  This should be changed to proper collision handling, but that probably has other issues.

**Comment by PilzAdam** [comment] 2015-04-07 08:22
@ShadowNinja the item entities use the collision system of the engine.

**Comment by C1ffisme** [comment] 2015-04-07 22:23
What we need is to re-prioritize the engine's processes. Maybe we should tune block drawing settings to be faster and more efficient. And things like clouds should be fully disable-able.

**Comment by PilzAdam** [comment] 2015-04-07 22:59
@C1ffisme Your comment is useless and offtopic.

**Comment by C1ffisme** [comment] 2015-04-07 23:56
@PilzAdam What I'm saying is, we need to put physics control before block drawing. Reprioritize. Re-organize the order of processes.

**Comment by BlockMen** [comment] 2015-04-08 10:18
> the item entities use the collision system of the engine.
@PilzAdam if its an engine bug why keeping the issue open?

**Comment by PilzAdam** [comment] 2015-04-08 11:52
@BlockMen I don't know if it's an engine bug; maybe the TNT spawns the entities inside nodes?

**Comment by C1ffisme** [comment] 2015-04-08 16:18
@BlockMen Because:

1. TNT is causing the bug and
2. It can be fixed without modifying the engine.

**Comment by BlockMen** [comment] 2015-04-08 18:41
@C1ffisme not if the items are spawned correctly. But since you seem to be sure its caused by TNT you could show the code part that spawns the items incorrect or (even better) make a PR to fix it.

> Put all exploded blocks into a bone-like block (cheap, but also stops lag)

That is no fix, its a workaround.

**Comment by C1ffisme** [comment] 2015-04-09 01:48
@BlockMen What I mean is, it's an engine bug (Most likely), but TNT is what is causing this bug.

Question : When TNT spawns items, does it just spawn them at a drop spot, or spawn them at the TNT and add velocity (Might be another solution)?

**Comment by ExcaliburZero** [comment] 2015-05-03 03:26
@C1ffisme I took a quick look at the TNT mod's [item dropping function](https://github.com/minetest/minetest_game/blob/master/mods/tnt/init.lua#L35-L58) and it seems to spawn the objects randomly in the blast radius and then give them a velocity and acceleration.

**Comment by C1ffisme** [comment] 2015-05-03 21:30
> it seems to spawn the objects randomly in the blast radius

That's it! Maybe it goes slightly farther than that! Maybe if we changed ```pos.x = center.x + math.random(-radius, radius)``` to ```pos.x = center.x + math.random(-radius + 1, radius - 1)```

**Comment by ExcaliburZero** [comment] 2015-05-03 21:55
@C1ffisme I tried changing the locations where the items dropped in the way you mentioned ([See here](https://github.com/ExcaliburZero/minetest_game/commit/ff6d3271be3cf8845854d057ebdcfe9699b3ec99)). However, I still had some items get stuck inside nodes.

![screenshot_20150503_174727](https://cloud.githubusercontent.com/assets/4276196/7447137/84163982-f1bd-11e4-9346-d322b6f12984.png)

**Comment by C1ffisme** [comment] 2015-05-05 16:09
Hmm...It does look like you got less underground nodes though...

So obviously this is a physics problem, and objects can ignore nodes for split-seconds.

**Comment by PilzAdam** [comment] 2015-05-05 16:12
Are the items spawned in a square? That may explain it, since the TNT causes a circular crater.

**Comment by C1ffisme** [comment] 2015-05-05 16:15
Maybe...

Try making the explosion have the same radius as the item spawn, and see if any entities end up in nodes.

Maybe the awnser is writing down the nodes that an entity CAN spawn in, rather SUPPOSING that a node might be spawnable.

Or use ```if node == air then (recursion function to find air node to spawn)```.

**Comment by paramat** [comment] 2015-05-05 16:55
> IIRC the root cause is that entities just poll their current position to check if they're inside a solid node and stop if so, but TNT pushes items too fast for them to stop themselves before they've already gone too far.

I suspect this is the cause, the only way to detect collision is to detect being inside a node, so fast moving objects are already underground when collision is first detected.

**Comment by ExcaliburZero** [comment] 2015-05-05 18:39
@PilzAdam The entities appear to be spawning in a square of a size of `2 * radius` x ` 2 * radius`. So that could be the cause, however I have a feeling that it might be due to entity movement as @ShadowNinja and @paramat noted.

I think I will try to test it to see if the square spawning space is the issue.

**Comment by ExcaliburZero** [comment] 2015-05-05 18:51
I did a quick test to see if the spawning range was the issue by reducing the spawning range to a 1x1 square, which in theory should prevent node entities from spawning inside nodes ([See here](https://github.com/ExcaliburZero/minetest_game/commit/f864267cbe457978ca4e5a79ca9520dd153a982e)). However, tnt still caused node entities to end up inside nodes.

![screenshot_20150505_144549](https://cloud.githubusercontent.com/assets/4276196/7480347/04c29994-f336-11e4-840f-8c398ebd00f7.png)

 I think the issue is not being caused by the spawning of the node entities.

**Comment by C1ffisme** [comment] 2015-05-06 00:14
Wow, this can only mean that we're looking at an engine bug. We need to fix collision!

Or, we can make entities try to pop out of nodes like minecraft (If you try to drop gravel on an item, it will fly out of the node.)

**Comment by paramat** [comment] 2015-05-06 17:56
No it's not a bug, just an unavoidable result of how collision detection works with fast moving entites.

**Comment by ShadowNinja** [comment] 2015-06-21 17:48
This seems to fix it for me; a bit of a hack but it works:
```Lua
local function rand_pos(center, pos, radius)
	local node
	local i = 0
	repeat
		-- Give up and use the center if this takes too long
		if i > 4 then pos.x, pos.y = center.x, center.y end
		pos.x = center.x + math.random(-radius, radius)
		pos.z = center.z + math.random(-radius, radius)
		node = minetest.get_node(pos)
		i = i + 1
	until node.name == "air"
end
```

**Comment by C1ffisme** [comment] 2015-10-22 22:57
I did find another bug (or just bad code design) with TNT : #708 .

**Comment by paramat** [comment] 2016-02-18 11:50
#710 merged.

**Closed by paramat** 2016-02-18 11:50 UTC
Labels: bug, Medium priority, needs engine-change

**Comment by ShadowNinja** [comment] 2016-02-23 06:22
Items can still get pushed into nodes by TNT explosions -- but this is an issue with the engine item_entity's collision detection.
