### ISSUE TITLE
 Replace snow sounds 

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest_game#1899] opened 2017-09-26 20:54 UTC
the snow sounds are bad, we should replace it.
--

**Comment by Fixer-007** [comment] 2017-09-26 22:49
dupe of https://github.com/minetest/minetest_game/issues/1388

**Comment by SmallJoker** [comment] 2017-09-27 08:55
ok, they will get replaced somewhen.
--

**Closed by SmallJoker** 2017-09-27 08:55 UTC
Labels: Request / Suggestion, Sounds
