### ISSUE TITLE
More interesting caves

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1142] opened 2016-06-17 22:10 UTC
I personally think caves should be more interesting because they are just dark tunnels and really boring. Maybe biome caves like an ice cave and a underground green cave maybe a biome which adds giant glowing mushrooms, also stalagmites and stalactites would be amazing.

**Comment by paramat** [comment] 2016-06-17 22:16
The more fanciful ideas here are for mods.
Caves in ice do not appear because ice has been made 'not ground content' to avoid ugly holes in ocean iceshelf. It would be good to have caves in 'on land' ice but we would need 2 types of ice, one that is ground content.
Decorations cannot be placed in caves currently but the decoration API might be capable of this later.
BIome material cannot be placed in caves because caves are cut after biome is placed, however that might be changed by hmmmm later.

**Comment by tobyplowy** [comment] 2016-06-17 22:19
@paramat so caves will be as boring as they are right now for a long time. Are the corals still pland?

**Comment by paramat** [comment] 2016-06-17 22:21
If you find caves boring that's your problem, many enjoy them as plain stone.

**Comment by tobyplowy** [comment] 2016-06-17 22:23
@paramat boring is a bit of an overstatement but they are just a little bit too plain.

**Comment by paramat** [comment] 2016-06-17 22:27
These are engine issues so closing.
I might make non-mgv6 caves more common though.

**Closed by paramat** 2016-06-17 22:27 UTC
Labels: Feature request, Needs engine-change

**Comment by tobyplowy** [comment] 2016-06-17 22:35
@paramat Ravines could also be really awesome http://minecraft.rvdbrg.com/wp-content/uploads/2011/09/2011-09-12_20.21.38.png

**Comment by C1ffisme** [comment] 2016-06-17 22:55
What about a feature to manipulate cavegen, such as changing the wall material?

**Comment by paramat** [comment] 2016-06-17 23:00
Yeah thse ravines were by hmmmm i just re-enabled them, we weren't happy with them.

**Comment by tobyplowy** [comment] 2016-06-18 09:05
@C1ffisme that would be an amazing feature

**Comment by tobyplowy** [comment] 2016-06-18 09:06
@paramat why were you not happy with it?

**Comment by Ferk** [comment] 2016-06-18 13:20
Ice caves are not the same thing as caves in ice, though. You can have an ice cave in a rocky mountain, the ice formations are caused by the low temperature and humidity. An ice cave doesn't have to be completely made of ice. 
But I guess it's not doable in the current engine.

**Comment by C1ffisme** [comment] 2016-06-18 15:18
> and a underground green cave maybe a biome which adds giant glowing mushrooms, also stalagmites and stalactites

This would be a pretty cool thing to make in Minetest, perhaps similar to Terraria's [Underground Jungle](http://terraria.gamepedia.com/Underground_Jungle)?

**Comment by tobyplowy** [comment] 2016-06-18 17:22
@C1ffisme that was exactly what I was trying to say. but I guess it doesn't matter now because the issue is closed :(

**Comment by C1ffisme** [comment] 2016-06-18 20:20
@tobyplowy I think this is best made as an API in the engine, rather than a part of MTG by itself. You could try and open an issue about an API there.

**Comment by paramat** [comment] 2016-06-18 21:22
Giant glowing mushrooms are a fantasy thing, our biomes are roughly realistic.
The biome API makes it easy to create your own biome systems and decorations, see Ethereal/Xanadu.

**Comment by C1ffisme** [comment] 2016-06-19 02:14
@paramat It is possible to create biomes on the ground, but under the ground, there can only be stone with ores and caves. (Without using voxelmanip or register_on_generated, you can't even have rock layers, as far as I know.)

**Comment by paramat** [comment] 2016-06-19 03:52
Sorry i misread.

> an API for underground biomes/decorations.

This might happen soon, hmmmm is planning changes.

**Comment by paramat** [comment] 2016-06-23 23:46
I'm working on making mgv7/flat/fractal/valleys tunnels 50% more common https://github.com/minetest/minetest/pull/4240
