### ISSUE TITLE
Have beds to depend necessarily on red dye?

### ISSUE THREAD

**Issue by Echoes91** [minetest/minetest_game#475] opened 2015-03-25 19:22 UTC
We know that colored beds are nicer, and also that red wool should come out from red dye, but why should somebody stay awake every night until he finds a rose? The bed should have worked the same whatever the color of the wool was. 
I can imagine that defining and drawing textures for each color like the good old PilzAdam's work may be boring and low priority, that's why i have two proposals: either fall back to the Minecraftish solution where every wool color gives the same red bed (it may be one of the worst things to copy but after all why the bed is red if not due to MC?), or we can make the bed white. White bed could be crafted coherently with white wool, thus not depending on any flower species, and also look more sober (I think MT feels overall more sober than MC).
What do you think? If you like either one or the other one i can make a PR. 
Sorry for the long writing...

**Comment by C1ffisme** [comment] 2015-03-26 16:58
IDEA : Why not make the simple bed white, and the fancy bed red? Then the simple bed can be used for simple sleeping, and the fancy one for decoration when you find a rose!

**Comment by Echoes91** [comment] 2015-03-27 10:19
That can be a good compromise too.

**Comment by C1ffisme** [comment] 2015-03-27 15:35
The problem is making a white bed that looks good. I don't think I would want to sleep in a white bed. So someone has to make a REALLY good texture.

Or, since leaves are pretty much everywhere, why not make leaves (or cactus) make a green dye, which can make the simple bed.

**Comment by 0-afflatus** [comment] 2015-04-07 00:42
The Way To Go is different coloured beds like the old-style beds.

**Comment by C1ffisme** [comment] 2015-04-07 22:34
@0-afflatus True, but then we have to add a whole bunch of nodes. And people really don't need that many in-game. It's better to have 1 or 2 beds and stick with that.

Maybe if we had a bed that could be dyed via crafting, while the colored types didn't appear in the creative inventory. Maybe different colors of bed could be defined by a param. We just need a non-heavy, not-to-many-node solution.

Or we could go the minecraft way, where every wool makes a bed. Cheap, but might work just for gameplay reasons.

**Comment by PilzAdam** [comment] 2015-04-07 22:58
@C1ffisme Making all wool result in the same bed would break my beds mod, since the generic recipe would override the color-specific ones.

**Comment by C1ffisme** [comment] 2015-04-07 23:59
@PilzAdam I believe your beds mod would override the minetest one, overriding the crafting recipe. So actually nothing would happen to your mod, because of naming conventions.

**Comment by 0-afflatus** [comment] 2015-04-08 00:06
Personally, the old coloured bed models with the new functionality would suit me fine. And I might just do that if it is not too complicated. I'm not sure this discussion is really going anywhere.

**Comment by PilzAdam** [comment] 2015-04-08 11:53
@C1ffisme this is not specified behavior, so we have to assume the worst case. Maybe add a way in the engine to remove / override recipes.

**Comment by C1ffisme** [comment] 2015-04-08 16:17
@PilzAdam I saw an engine issue about that.

**Comment by npmaier** [comment] 2015-04-08 17:01
I like white beds.  It kind of harken back to days on the farm where they
had white mauslin sheets.   I've seen pictures of the depression.  Early
survival would be more authentic
-Bikemare

**Comment by BlockMen** [comment] 2015-04-08 18:44
@PilzAdam huh? Except some 0.4.5 or 0.4.6 dev version user mods with the same name did always replace the game mods...
And IMO its the right behavior.

**Comment by PilzAdam** [comment] 2015-04-08 19:08
@BlockMen why do you provide an API to add new beds when mods that want to add new beds have to override it?

**Comment by BlockMen** [comment] 2015-04-09 07:13
@PilzAdam i ment there general behavior of mods. 
And just for the protocol: Why are you claiming the whole time your mod would break when you are not even using the API...

**Comment by PilzAdam** [comment] 2015-04-09 09:39
@BlockMen it's not about my mod. A mod that wants to add beds for all colors using the API you provide would depend on unspecified behavior regarding the crafting recipes.

**Comment by Echoes91** [comment] 2015-04-09 09:47
What about giving it a different name?  "morebeds" could add new ones depending on default "beds" without overriding it, as moreores does not override default ores.
Otherwise you could merge both good works by adding the old colored beds to the new code and API within the same "beds" mod, right?

**Comment by BlockMen** [comment] 2015-04-10 18:49
@PilzAdam you can use any recipe. only the recipe for the default beds is fixed.

@Echoes91 I don't see the point in renaming. The reason that there are "only" two beds is that Minetest Game should not get bloated. If ppl want more colors, a mods could easily add by using the API.

And yeah, one solution would be a white bed or a "raw" bed that could get crafted with any kind of wool and dyed afterwards. But first i think a white bed wouldnt look good and second it would be even more confusing than now IMO.

**Comment by Echoes91** [comment] 2015-04-10 19:39
I meant to give a different name to the mod that should add more beds, so that it can use the default mod's API without overriding it. And the raw/white bed should be crafted only with the raw white wool, without overriding any colored bed or creating any confusion.

**Comment by C1ffisme** [comment] 2015-10-21 16:12
I wonder... what if we could set the texture of the bed based on a parameter, and not make several nodes of beds?

I'm not sure if this is possible, but if this could be done, you can just see all the node types we could save. Wool could be 1 node type, metal blocks could be 1 node type, desert and normal stone could be 1 node type, we would just need two things:

- Make the bed item have data which corresponds to either a string with a texture, or a number with a colorize hue.
- Set the bed depending on what data this item has, and set the drop so that the item has the data of the bed.

You can see how useful this feature would be in mods.

**Comment by BlockMen** [comment] 2015-10-30 20:35
Removed color dependency in Minetest NeXt.
https://github.com/BlockMen/minetest_next/commit/4ff5cad24c62d634fd15444fa38a0e4253ac63db

**Comment by paramat** [comment] 2016-03-02 22:58
> we can make the bed white. White bed could be crafted coherently with white wool, thus not depending on any flower species

I support this.

**Comment by paramat** [comment] 2016-03-08 20:40
I realised this is not much of an issue, since to get wool you need cotton seeds from junglegrass, and jungles are usually more distant than roses

**Comment by 0-afflatus** [comment] 2016-03-08 23:46
OK I'm going to look for a different solution for night-skip voting as using the beds mod from minetest_game in grailtest isn't satisfying my requirements. AFA decor is concerned, players can do interesting things with coloured wool. I think I want to de-couple night-skip voting from this.

I'll stop making comments on this issue as minetest_game isn't really my concern.

**Comment by mtango688** [comment] 2016-08-10 20:37
Broken, inconsistent, and generally not accepted. Yeah, nice standard you have here.

Meanwhile, I shall continue to promote this:

`-- fix the bed recipes

minetest.register_craft({
	output = "beds:bed",
	recipe = {
		{"group:wool", "group:wool", "group:wool"},
		{"group:wood", "group:wood", "group:wood"}
	},
})

minetest.register_craft({
	output = "beds:fancy_bed",
	recipe = {
		{"", "", "group:stick"},
		{"group:wool", "group:wool", "group:wool"},
		{"group:wood", "group:wood", "group:wood"},
	},
})
`

**Comment by paramat** [comment] 2016-08-11 12:10
@rubenwardy @sofar your opinions? I think this can be closed now, or we should make a decision. I'm :-1: for any change but don't feel strongly about it. PilzAdam is -1.

**Comment by rubenwardy** [comment] 2016-08-11 14:09
I think that multicolor beds is much more of a mod thing, and allowing any wool to make a bed could break mods that add multi color beds

**Comment by sofar** [comment] 2016-08-11 21:26
Please close. MT Biomes aren't that large, the game offers no extra challenge other than it "being dark" at night (there are no monsters), so making beds an end-game item is currently appropriate.

:-1:

**Comment by paramat** [comment] 2016-08-12 12:59
4 dissapprovals out of 7, closing.

**Comment by mtango688** [comment] 2016-08-17 13:44
It isn't a "challenge" at all. I don't need help to hold down the "w" button and look for something red. It's an annoyance, and a super unnecessary one at that. Being dark isn't an issue. You just go afk for ten minutes. There is no "end game" because this game has so goals to begin with.

Literally, the only value insisting on red has is that it is different for the sake of being different. It pointlessly annoys people who also play or are otherwise familiar with Minecraft.

**Comment by paramat** [comment] 2016-08-17 16:46
> It pointlessly annoys people who also play or are otherwise familiar with Minecraft.

That's no issue, MT is obviously going to differ in many areas.

Rethinking this i'm neutral not opposed, i would actually prefer to not require any dye, and have a white bed, perhaps made from white wool? Surely any other bed mods would only override default's recipes so the mod breakage argument doesn't seem strong. Most use the MTGame bed mod anyway.

**Comment by sofar** [comment] 2016-08-17 17:29
@mtango688 being "annoying" is your perception of a barrier. Others may perceive this barrier differently, so we're not disputing that you find it annoying, but some of us want it to be "annoying to some players".

Pausing play for ten minutes isn't something I would expect all players to do, only a subset that are having issues with darkness. I'd expect players to create torches and make light, thought, and as long as most players do, the mechanism of day/night is valid. That's not pointless.

**Comment by paramat** [comment] 2017-05-25 11:05
Since PilzAdam and BlockMen have left this is now 2 disapprovals, and i think this should be reconsidered, i find the current need for a certain dye ridiculous too.

**Comment by C1ffisme** [comment] 2017-05-25 17:05
@paramat 
> That's no issue, MT is obviously going to differ in many areas.

I'm totally fine with this, just make sure that the one thing they don't differ in is whether or not the game is actually fun to play.

**Comment by paramat** [comment] 2017-05-25 17:21
I'm thinking either a range of coloured beds plus a white one needing no dye, as beds are part of builds furniture.
Or, just a white bed needing no dye. At least then the basic bed is a neutral colour.

**Comment by paramat** [comment] 2017-05-25 23:14
> to get wool you need cotton seeds from junglegrass, and jungles are usually more distant than roses.

This is why the difficulty argument is no issue, not needing a dye doesn't really make them easier to craft. The locations of biomes means that you are highly likely to pass a rose by the time you find a jungle for cotton seeds.
I don't like how we are so obviously copying MC by having a red bed.

I suggest a whote bed from:

```minetest.register_craft({
output = "beds:bed",
recipe = {
{"group:wool", "group:wool", "group:wool"},
{"group:wood", "group:wood", "group:wood"}
},
})

minetest.register_craft({
output = "beds:fancy_bed",
recipe = {
{"", "", "group:stick"},
{"group:wool", "group:wool", "group:wool"},
{"group:wood", "group:wood", "group:wood"},
},
})
```

**Comment by mtango688** [comment] 2017-05-26 12:19
Sweet! Thanks a lot!

**Comment by paramat** [comment] 2017-06-03 22:31
Thinking on this, i'm sure many like the red beds, so the thing to do would be to add white beds (or maybe just the simple one) without removing the red ones.
However see #1566 perhaps this PR (reworked to keep individual textures for dyes and wool) could provide a red and white bed,
I would like to wait for more input before doing the work of making white bed textures.

**Comment by paramat** [comment] 2017-06-10 18:40
Ok i will add an additional white bed.

**Comment by paramat** [comment] 2017-06-15 17:17
I'll register a 'simple white bed' soon, any comments or objections?

**Comment by C1ffisme** [comment] 2017-06-16 15:12
Just feel like mentioning it... but MC recently added colored beds to their game. Although even they didn't have enough block IDs for it, and the colored beds are actually tile entities...

**Comment by paramat** [comment] 2017-06-23 12:36
We are considering that, there's a PR that might be reworked to do that but the author is absent, so in the meantime this will be a simple quick fix.

**Comment by paramat** [comment] 2017-06-23 22:01
See #1794 i will therefore not work on a white bed. Coloured beds are useful for colour co-ordination in builds.

**Comment by paramat** [comment] 2018-07-05 01:43
PR #2150

**Comment by Ezhh** [comment] 2018-09-14 16:35
I'm rather indifferent about beds in general, and wondering why some people are against adding a white bed. 

I do feel adding all colours isn't necessary for MTG itself.

**Comment by paramat** [comment] 2019-02-08 18:02
How about making the red bed not require red dye as a simple fix? After all most of the bed is the mattress which can be considered white wool. We have many items with coloured components that don't use a dye.
Have to consider mod recipe conflicts though.

**Comment by Ezhh** [comment] 2019-02-09 19:24
No objection to removing the requirement for dye.

I'm not familiar with the mod you're referring to, but most mods are intended for use with MTG, so please don't rule that out unless you've checked (though generally we shouldn't be restricted based on what another non-MTG mod has done, it's still good practice not to break something that already exists when we're aware of a possible issue).

**Comment by paramat** [comment] 2019-02-09 20:07
Hmm, in this case the mod is very much MTG beds mod code modified, instead of something meant to be parallel, so i think it's the responsibility of the mod to work around MTG. If we merge my suggestion i'll make a post in the mod thread.

https://forum.minetest.net/viewtopic.php?t=18775
"This is a modified version of the default Minetest game's beds mod by Blockmen.
These are experimental replacements for the beds mod.
Don't test them except for in a newly created world."
Also experimental so i'll go ahead and make a PR.

**Comment by paramat** [comment] 2019-02-09 22:59
PR #2309

**Closed** 2019-02-10 21:38 UTC
Labels: Low priority, Request / Suggestion, Supported by core dev
