### ISSUE TITLE
Decide whether MTG should allow non-"generic" gameplay

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest_game#2000] opened 2018-01-01 05:29 UTC
I was going to post some comment in #515 but realized this needs to be resolved before anything else.

# The question
There has been a lot of discussion of whether MTG needs to be a playable game or a modding base, but these aren't mutually exclusive. A more important distinction is whether the game is a *generic* modding base, because remaining generic will prevent adding more specialized and interesting features. You can have a playable game that is also a modding base (by providing an API to interface with its features), but not if the modding base has to be a generic one.

If non-generic gameplay is allowed, then the kinds of special gameplay mechanics desired should be decided so people can know what kinds of features to focus on and expect to get merged when PRs are made.

If non-generic gameplay is disallowed, nothing specific has to be done. I would hope that a separate subgame is added that tries to be its own game, though (but still moddable by providing APIs to its systems).

I think that this is the most critical unresolved design question and should be added to the 0.5 milestone.

# My opinion

My personal opinion is that MTG is currently not really generic in any real sense, but just what people imagine a generic voxel sandbox to be like, which is a "flavorless Minecraft". MTG already dictates some game features, such as an Earthlike environment, mining ores, tools and weapons, farming mechanics, etc. A modding base may benefit from being less generic, because it can provide deeper or more complex systems that mods can use as a common thing to build upon.

I don't want there to have to be two separate subgames as that would split development effort.

**Comment by C1ffisme** [comment] 2018-01-01 07:10
Considering the more recent (last few years) features: TNT, Crops, etc. I would say that we're moving towards non-generic gameplay, although without a detailed idea of what does and doesn't belong. (Do Sci-Fi elements fit? What about Magic or Fantastical ones? Does High-Tech only get put in the game if it's "made by aliens"?)

**Comment by raymoo** [comment] 2018-01-01 08:44
@C1ffisme 
I would prefer a clear answer once and for all, so that it doesn't get brought up every time a new feature is discussed.

**Comment by Fixer-007** [comment] 2018-01-01 14:47
What about making MTG full fledged game, but make it modular, so it can still be used as very modular modding base, you can easily disable/tweake via mod certain parts of the game. You can even add simple flag like "base" that disables literally everything, except decorative blocks, and then you enable "tools","furnace/smelting", "farming", "mobs", or customise it, make additions, overwrite etc etc.

**Comment by NewbProgrammer101** [comment] 2018-01-01 16:09
> What about making MTG full fledged game, but make it modular, so it can still be used as very modular modding base, you can easily disable/tweak within external mod certain parts of the game. You can even add simple flag like "base" that disables literally everything, except decorative blocks, and then you enable "mapgen6", "tools","furnace/smelting", "farming", "mobs", "whatever", or customise it, make additions, overwrite etc

I think most of that can be done in game.conf

**Comment by raymoo** [comment] 2018-01-01 21:34
@Fixer-007 Sounds like a good idea to me, though it seem like it would have some overlap with things being separated into mods.

**Comment by paramat** [comment] 2018-01-02 17:01
We don't have to make 'big, binding decisions for the future'. The situation, dev intentions and game direction are always changing, development is organic and broken down into small issue-by-issue individual decisions that are made 'in the moment'.

> I think that this is the most critical unresolved design question

Being anxious about not having a big fixed plan for the future is unnecessary, and a big fixed plan is unnecessary (and impossible anyway). I see this type of anxiety in issues quite often and it is interesting that it is players and contributors that are the most anxious, not the core devs. Have you noticed how the core devs are the most relaxed and laid back about 'plans', and just do what seems what is best in the moment? It's a more artistic, and the best, approach.

However, although it will not be binding and is not specific to individual issues, so doesn't mean much, if it helps i will say that the answer is 'yes', i get the impression the other devs would say 'yes' and i do too.

> I would say that we're moving towards non-generic gameplay, although without a detailed idea of what does and doesn't belong

The detailed idea doesn't have to exist. If after a huge amount of effort and argument we did decide in detail, the next day our intentions would change and it would be out of date already. A fixed detailed decision would be inflexible and not take into account the specifics of each issue or the current situation.

> @C1ffisme
I would prefer a clear answer once and for all, so that it doesn't get brought up every time a new feature is discussed.

This is entirely the wrong approach, the correct approach is indeed actually to reassess in every issue, in the moment, taking into account the current situation and the details of the issue.

> make it modular, so it can still be used as very modular modding base,

This is our intention, to add new things as mods whenever possible, then to make MTG's internal mods switchable in mod configuration.

**Comment by paramat** [comment] 2018-01-02 17:03
This is obviously a duplicate of #1999 no need to open an almost identical issue.

**Closed by paramat** 2018-01-02 17:03 UTC
Labels: Discussion, Question

**Comment by raymoo** [comment] 2018-01-02 19:34
It's enough for me to know that MTG is currently open to specialized features. I said that I wanted an answer once and for all, but what I actually wanted was just to have it clearer what the current stance is.

However, it seems like it would be difficult to decide after adding non-generic features, to go back to genericity.

**Comment by paramat** [comment] 2018-01-02 21:31
Ok, currently my best assessment of the other dev's opinions is that we are happy to develop MTG to make it a little more of a 'game', but it will likely remain fairly simple and a little general as it is and will always be a mod base for many mods, so much depends on it.
For a complete or exciting or very impressive game it seems a new game will be needed to do that as MTG is somewhat burdened by it's history and how so much depends on it.

**Comment by raymoo** [comment] 2018-01-03 00:40
I don't feel like that should keep new systems from being added on top of what is already there, though I guess it may be that development effort on such features might be better spent on a game designed to incorporate them from the beginning.

**Comment by paramat** [comment] 2018-01-03 22:54
> I don't feel like that should keep new systems from being added on top of what is already there

I agree, and it won't. Each suggestion will be dealt with issue by issue.
