### ISSUE TITLE
Chests Don't Close when you quit Minetest

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1769] opened 2017-06-08 16:34 UTC
I don't really know how to explain this but if you quit the minetest client without closing a chest it will stay open When you join again (this is probably a bug but I don't think it's important but I reported it anyways)

**Comment by tobyplowy** [comment] 2017-06-08 16:35
[demo vid.zip](https://github.com/minetest/minetest_game/files/1061680/demo.vid.zip)

**Comment by DS-Minetest** [comment] 2017-06-08 21:01
An easier way to hold a chest open is by spamming esc (holding the button).
But it's a feature I think. Open chests can be used as decoration.

**Comment by paramat** [comment] 2017-06-09 12:11
The chest has been left open so why would it be closed on rejoin?

**Comment by tobyplowy** [comment] 2017-06-09 12:36
@paramat well You're Not really using the chest anymore (and if you dount quit The client and press Escape instead the chest closes Because you don't use it Anymore) but @DS-Minetest raised a good point you can actually use this as decoration

**Comment by Ferk** [comment] 2017-06-09 17:00
This was already pointed out in the PR for introducing the feature: https://github.com/minetest/minetest_game/pull/793#issuecomment-195546419

Imho, as long as the chests being left open don't really have any repercussions it's not something worth a fix, specially if the fix would be troublesome/complicated.

**Comment by paramat** [comment] 2017-06-09 18:53
I'm adding this from the forums https://forum.minetest.net/viewtopic.php?f=6&t=17806

"Version of Game (0.4.16)
OS (Linux Mint 17.3)

They is a bug with chests on servers.

If Player 1 Joins the game and opens a chest and then disconnects the chest will stay open and cannot be closed by any other player apart from they player who opened it.

The main problem with this is that the open is indestructible even though the chest is empty.

Edit:

They are 2 chest on the server. If i join the game and open chest one, then disconnect the chest will stay open, only i can close it.

if I join the game and open chest 1 then disconnect, then do the same for chest 2, by reconnecting chest 1 will close and chest 2 will be stuck open.

Resetting the server dose not fix this issue"

**Comment by DS-Minetest** [comment] 2017-06-09 21:48
Suggestion:
Add to the for loop in nodes.lua in line 1819 something that checks if the player with the name `v` is connected and if it's protected against `player`.

**Comment by DS-Minetest** [comment] 2017-10-29 12:05
Afaik, this is fixed now. To be closed?

**Comment by MarkuBu** [comment] 2017-10-29 12:14
I still can confirm this bug. If I open a chest and hit esc before the inventory is shown, I can exit the game and the chest is still open.

Or I open a chest and close the client window

I use the latest minetest (0.5.0-dev) and MTG

**Comment by paramat** [comment] 2017-10-29 13:14
However, is it harmless?

**Comment by MarkuBu** [comment] 2017-10-29 13:45
I think the problems are discussed in this thread

**Comment by paramat** [comment] 2017-10-29 15:13
Ok the only significant issue is https://github.com/minetest/minetest_game/issues/1769#issuecomment-307471210 which was thought to be fixed, but maybe not.

**Comment by DS-Minetest** [comment] 2017-10-29 15:22
I can confirm, too, chests still stay open (at least in singleplayer). So, https://github.com/minetest/minetest_game/commit/c5c9e423caf901d8a9a97ce959f4ee31cadbf7a0 doesn't work?
@tenplus1

**Comment by MarkuBu** [comment] 2017-10-29 15:33
If the server crashes (or if server is started from the gui and the hoster closes the window) the chest is still open. 

Only if a player is leaving a server the chest will be closed.

**Comment by DS-Minetest** [comment] 2017-10-29 15:41
I assume, it's the fault of the use of `minetest.after`.
Btw does `minetest.swap_node` even work in unloaded blocks? (Maybe load with voxelmanip.)
Maybe only use after and play sound if there is at least one player near.

**Comment by paramat** [comment] 2017-10-30 10:31
@tenplus1

**Comment by rubenwardy** [comment] 2017-10-30 21:38
simple, don't quit Minetest

**Comment by tobyplowy** [comment] 2017-10-30 21:43
@rubenwardy that's not going to fix the Problem!

**Comment by Ferk** [comment] 2017-11-15 20:04
@MarkuBu,  to clarify: even if the chest is still open, you can still close it manually. Is that correct?

Or is the chest impossible to close like it happened before?

**Comment by MarkuBu** [comment] 2017-11-15 20:55
It seams that something has changed. In singleplayer the chest stays open if I hit esc fast enough if I open it and exit to main menu. But if I join again I can close the chest 

But this isn't possible anymore in multiplayer. If I open a chest and hit esc, the chest inventory overlays the exit menu. That didn't happen two weeks ago.

I can't reproduce the bug now

**Comment by paramat** [comment] 2018-02-14 23:25
I think the author is rage-closing issues.

**Comment by sfan5** [comment] 2018-07-07 11:28
If you don't have anything productive to say, don't comment.

**Comment by that-other-guy123** [comment] 2018-07-07 13:15
@sfan5 me or @tobyplowy

**Comment by tobyplowy** [comment] 2018-07-07 13:17
@that-other-guy123 please stop pinging me I'm trying to forget this
Remember

**Comment by that-other-guy123** [comment] 2018-07-07 13:17
Je

**Comment by that-other-guy123** [comment] 2018-07-07 13:20
Also I like open chest as decoration

> But it's a feature I think. Open chests can be used as decoration.

Yes I agree

**Comment by paramat** [comment] 2018-07-07 18:48
tobyplowy we did respect your contributions and issues, even if we disagreed with some of them. We treated you like anyone else. You made yourself angry for some reason but are blaming us for it. Maybe the direction of MT just wasn't to your taste, this can be frustrating but no-one is to blame for that.

**Comment by that-other-guy123** [comment] 2018-07-07 19:57
@paramat I hav show te mesage to Toby and he ask if I can giv u his mesage so here is it
I just copy paste

> Hey dude I'm not in the mood to go on the github just send them this as a response 
> @paramat Eheh that maybe true,
> but I'm mad becouse of other reasons 
> Like that one comment by @sofar on Irc saying minecore doesn't need any picks it's already full of holes
> Or you paramat saying that we make no chance of success and that we are waisting people's time
> 
> I only had good intentions with minetest and I have helped you and your community for 3 years
> I have helped with the legend of minetest so it's a more professional game 
> And I have Co made farlands and that is seen as a very good game although I'm not proud of my texture work for it and I took over the summerfealds pack for minetest (lipki lost interest in minetest so I was the only hope for updates) so yeah I have been made fun of by you guys I have been backstabed 
> I have been hurt and annoyed beyond beleave so that's why I left 
> Thank god for scare I was going to leave soon but then he came and I am finally  having a good time 
> And every time I see a message from minetest I have to role my eyes and say to my self why can't they just leave me alone 
> 
> Now for some positive stuff I did have fun at the time when I was still interested in minetest 
> But I just really whant to move on and becouse no one let me I was left with more choise I had to remove everything that had to do with me and minetest 
> 
> So that's it do with it what you want I don't care 
> I know everything I just said will be taken out of context but whatever
> I hope it at least clarifies some things
>
> also sorry for not contacting you guys my self but I just can't do it anymore I have had enough drama


So that is his mesage

**Comment by paramat** [comment] 2018-07-07 20:11
Ok, we'll try to not ping him anymore (i won't). He can stop notifications from MT issues if he wants to (icons in notification list).

**Comment by paramat** [comment] 2019-01-01 02:50
> If Player 1 Joins the game and opens a chest and then disconnects the chest will stay open and cannot be closed by any other player apart from they player who opened it.

Tested this, if a player opens a chest then disconnects, the chest closes when they disconnect.
If anyone experiences a problem with an unclosable chest open a new issue.

**Closed by paramat** 2019-01-01 02:50 UTC
Labels: Bug
