### ISSUE TITLE
Add furnace alloy support

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest_game#2093] opened 2018-03-23 18:22 UTC
This is not correct, steel is an alloy of [iron and carbon](https://en.wikipedia.org/wiki/Steel)
[EDIT by paramat: Not correct.]

Furnaces don't support making alloys, so there are 3 options:

* Add alloy support
* Combine iron with coal to make a new craft item - steel mix or smth
* Rename steel and steel-based items to iron

**Comment by pauloue** [comment] 2018-03-23 19:37
From https://en.wikipedia.org/wiki/Steel#Steel_production:

> When iron is smelted from its ore, it contains more carbon than is desirable. To become steel, it must be reprocessed to reduce the carbon to the correct amount, at which point other elements can be added.

and from https://en.wikipedia.org/wiki/Iron:

> Crude iron metal is produced in blast furnaces, where ore is reduced by coke to pig iron, which has a high carbon content. Further refinement with oxygen reduces the carbon content to the correct proportion to make steel.

So iron + coal probably wouldn't make sense.

**Comment by paramat** [comment] 2018-03-23 22:54
Hmm looks like iron + carbon is not correct anyway, however:

I prefer allowing funaces to accept multiple inputs, will have many uses, like maybe copper + tin for bronze.
Combining craftitems is hacky but acceptable, maybe for short term, we do it for bronze already.

Changing items from steel to iron: no thanks, lots of texture work, lots of mod breakage and much is intended to be 'steel'. Shiny steel is a much more satisfying material to have than iron.
/////////////////

We could assume the furnace automatically processes to reduce carbon content.
We could change the description of iron bars.

**Comment by TumeniNodes** [comment] 2018-03-25 03:16
**The discovery was made by anthropologist Peter Schmidt and metallurgy professor Donald Avery, both of Brown University. Very few of the Haya remember how to make steel but the two scholars were able to locate one man who made a traditional ten-foot-high cone shaped furnace from slag and mud. It was built over a pit with partially burned wood that supplied the carbon which was mixed with molten iron to produce steel. Goat skin bellows attached to eight ceramic tubs that entered the base of the charcoal-fueled furnace pumped in enough oxygen to achieve temperatures high enough to make carbon steel (3275 degrees F). [Ibid] 

excerpt from the last section of this topic: http://factsanddetails.com/world/cat56/sub362/item1495.html

This is a good bit of information, and may be helpful if anyone decides to just replan all the ore/metals/tools aspects of the game some day...

**Comment by paramat** [comment] 2018-03-27 01:02
Reading up on this, there is such a thing as high carbon steel, but it is brittle so probably not what we want for weapons and tools. It seems we are making reduced carbon steel (iron with removed carbon) which in early industrial times was made by forcing air (oxygen) through molten iron.
So the first comment here is partly a misunderstanding.

If we wanted to make this more realistic we could add a 'bellows' node that is placed beside the furnace and checked for. But then the creation of other metals may also use bellows, perhaps it's better to keep it simple and assume the single furnace node contains bellows etc. for multiple types of smelting?

Iron ore smelting to steel is not a big issue because it is roughly correct, we have just left out some details. The production of other metals is likely more complex too, we also form tools from raw diamonds.
The furnace is more a symbol for a process than being realistic and we shouldn't get too realistic.

I still support an alloy furnace for copper + tin = bronze since crafting ingots together is very hacky, that is a bigger issue here.

Another bigger issue here is the fact that tools have durability as if bronze is tougher than steel, steel is being treated as if it is iron (what a mess!), we need to reverse the order of steel and bronze.

**Comment by tenplus1** [comment] 2018-03-27 20:10
+100 for alloy smelter to give a level 2 for high temp metals to be smelted, leaving the default furnace as level 1 for food and iron only.

**Comment by Fixer-007** [comment] 2018-03-27 22:41
>alloy furnace for copper + tin

Another furnace just for useless metal for useless tool (aka bronze, that is also unpopular and unbalanced), that will be really bad way.

**Comment by paramat** [comment] 2018-03-28 10:44
No same furnace, just add multiple inputs. It won't be just for bronze it will be useful in other ways.

**Comment by cx384** [comment] 2018-03-28 11:04
I think we should keep steel and change the progression line.

1. Wood (trees)
2. Stone (ground)
3. Bronze (alloy furnace) and maybe iron or other materials
4. Steel (blast furnace)
5. Mese/Diamond (ores)

**Comment by paramat** [comment] 2018-03-28 11:11
#2096 merged.

**Comment by Fixer-007** [comment] 2018-03-28 18:34
There is another problem, if we want more realistic steel production, then other metal production should be evaluated.

**Comment by Ferk** [comment] 2018-03-29 07:25
I think it's ok to skip realism when it's for the sake of simplifying things. The problem is that having bronze be better for tools than steel is not a simplification, it's plain backwards and wouldn't be something people who don't know the game would expect.

I agree with the idea of requiring an evolved furnace for smelting steel. It will reverse the equation and give a bronze tier, adding up to the game progression. I already suggested this in the past.

Though if bronze is changed it probably would be good to not make it too weak, just marginally weaker (if at all) than steel would be fine. There are more advantages to steel than just the tools and it would be good to still be able to use some bronze after having a steel forge, even if just for the sake of saving up on steel.

About having an "alloy furnace", honestly to me it looks like it's a bit too much, unless it's done in a simple (for the user) and generic way (usable for other things than just bronze).
For example: just having a furnace with a single 4x4 inventory that acts at the same time as input and output. So you can cook combined things inside. Also with merged input+output it would also add some extra gameplay element if things like bread can turn into ashes when you leave the grain for too long inside the oven (imagine an "overcooked" kind of gameplay in minetest, where you need to work as a team to cook and time things right).

**Comment by benrob0329** [comment] 2018-03-29 12:35
Iirc historically MT had an overcook mechanic.

**Comment by paramat** [comment] 2018-05-08 21:49
Engine part of alloy furnace request.
https://github.com/minetest/minetest/issues/7300

**Comment by ChristianSirolli** [comment] 2018-06-08 13:54
I don't think the input and output should be combined. This messes with mass smelting ores and cooking food and bricks. Perhaps the "overcooking" happens only in the output, if it left there too long when there is still fuel being burned. And that can have some interesting affects on the metals.

I would think we should have a 3x3 input grid with a 2x2 output grid. That way there can be support for more complex smelting. We could have the current recipe for bronze (8 copper surrounding 1 tin) but in the furnace instead of crafting it.

**Comment by maxoutrunner** [comment] 2019-01-16 10:06
Do we really need steel in the base game?

Rather than having steel, I'd have pure iron, and leave steel production to the modders.

**Comment by rubenwardy** [comment] 2019-01-16 10:45
No, steel probably isn't needed. But it would be nice to have support for alloying

**Comment by paramat** [comment] 2019-01-16 14:51
Well, too late, we can't remove steel items now =)

**Comment by TumeniNodes** [comment] 2019-01-17 04:00
Remove steel???
Good Lord... could you imagine the revolt? That would probably come close to another catastrophic change not too long ago, which shall not be called by name.

**Comment by Fixer-007** [comment] 2019-01-17 13:10
>Remove steel???

That's some crazy trolling? I might as well remove minetest_game anyway with this kind of thinking.

**Comment by Fixer-007** [comment] 2019-01-17 13:11
>Do we really need steel in the base game?

What is even a base game? I think this is road to further disaster.

**Comment by paramat** [comment] 2019-01-17 17:33
I don't even consider MTG a 'game' =) ;)

**Comment by benrob0329** [comment] 2019-01-18 12:51
If you renamed steel to wrought iron or even just iron most players probably wouldn't even notice. A lot of servers use technic on top of this, and most people I talk to agree that the steel naming doesn't make sense.

**Comment by Ezhh** [comment] 2019-01-18 18:07
> If you renamed steel to wrought iron

So long as it's the description that changes, not the node name... but then we have to think about how confusing the node name not matching the description would be.

**Comment by paramat** [comment] 2019-01-18 23:04
*Sigh* It was just a casual remark by a person who prefers iron, which ignored the many issues it would cause, it's not remotely justified and isn't worth considering. Yes i do think we need steel in MTG since it's such a fundamental material and the only modern material (we need at least one).
> A lot of servers use technic on top of this, and most people I talk to agree that the steel naming doesn't make sense.

Why is it wrong?
The first post in this thread was a misunderstanding, it does make sense that iron smelts to steel, we assume the furnace has oxygen-blasting.

Also, what another mod does is of little importance, we don't develop MTGame to fit around other mods, other mods should fit around MTGame if they are meant to be based on MGame. If technic does something which makes MTGame seem wrong that's the fault and responsibility of the mod.

The only valid question here about iron is: Should we add iron as another material?

**Comment by jastevenson303** [comment] 2019-01-19 00:03
Yes.

**Comment by Ezhh** [comment] 2019-01-19 13:18
Adding iron would be insanity.

Paramat, the steel in MTG doesn't make sense. Unless there are mods that actually depend on it being steel and not iron, the only barrier to changing it is the name issue and wanting to avoid aliases (that can be enough of a reason by itself).  Please don't claim people don't understand just because they are willing to explore methods of solving things that you don't personally agree with. 

Either way, I'm not pushing for any change, because it's almost guaranteed there'll be complaints no matter what happens. An alloy furnace would be nice though. It's something I'd support.

**Comment by paramat** [comment] 2019-03-24 05:29
:+1: for an alloy furnace.

**Comment by An0n3m0us** [comment] 2019-05-30 15:13
Possible alloy furnace texture:
![test1](https://user-images.githubusercontent.com/49789044/58642642-a8acb500-82f5-11e9-9a31-b8edfd7df37b.png)
![test2](https://user-images.githubusercontent.com/49789044/58642643-a9454b80-82f5-11e9-8d88-43b23d947ad5.png)

**Comment by tenplus1** [comment] 2020-05-23 12:02
@maxoutrunner - that's why I made the pigiron mod to add in iron tools and have a special smelting recipe for steel, but an alloy furnace would be a better method :)

**Comment by paramat** [comment] 2020-07-27 01:38
Closing due to #2710

**Closed by paramat** 2020-07-27 01:38 UTC
Labels: Feature request
