### ISSUE TITLE
Teleportation

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest_game#1945] opened 2017-11-10 23:56 UTC
Many other games with large maps have some form of teleportation or fast travel. This often means once you reach a place the slow way (by walking or similar!) you can then get back there more quickly. But all minetest_game has is /home.

**The problem:** This can be offputting for those who like to build in multiple locations, because no matter what justification is used, constantly spending xx minutes walking between locations over and over again is not fun.

**The suggested fix:** Some kind of teleportation system that allows more locations than one to be saved.

I'm posting this in the hope of seeing whether or not this would be supported as a concept, and if it is supported, what the desired features of a teleportation system for minetest_game would be.

**General points to consider:** 
- Must the player travel "the slow way" to a place before being able to teleport there? (Personally I feel this is vital).
- Should there be a per use cost to prevent it being too easy?
- Should teleporting use a permanent placeable item of some kind, or just involve some action which  saves the location?

**Points to consider for multiplayer use:**
- Should other players be able to use your teleports? (Keep in mind, this would mean one player who travelled a long way could then allow others to skip all the work of exploring/ travelling. For example: instant access to deep mines.)
- Should you be able to set teleport points to an area another player has protected? (I know minetest_game doesn't have a protection mod, but this is still worth considering.)

**Comment by paramat** [comment] 2017-11-11 01:09
Seems a good idea, but without making it too easy or too cheap. Also i would prefer there is a way to disable the feature if desired, however that could be done by making MTG mods disableable in the mod configuration menu (there may be an issue for this) which would be useful for many reasons.

My opinion on the 5 points:
1. Yes.
2. Yes. Since mese is our 'magickal/mysterious/alien substance' maybe mese crystals or mese crystal fragments as part of the recipe? Mese ore is now found at y = -512 so has a reasonable cost.
3. Thinking on it.
4. No.
5. No.

**Comment by MarkuBu** [comment] 2017-11-11 08:33
4. A user can enable other players to use the teleporter similar to the skeleton key for the chest

**Comment by Ezhh** [comment] 2017-11-11 16:09
@paramat It should be a separate mod, therefore easy to disable by removing that mod. (Better if it's possible to disable mods in the configuration menu as well of course, and would like to see that, but it would be a separate issue to this).

For 3, I think a permanent placeable item is only really required if it's intended for other players to be able to use a teleport point.

**Comment by paramat** [comment] 2017-11-11 16:34
Yes it certainly should be a separate mod, we do that whenever possible now.

**Comment by Ezhh** [comment] 2017-11-19 18:12
Is there any interest in this, or should I close the issue?

**Comment by rubenwardy** [comment] 2017-11-19 18:23
> Must the player travel "the slow way" to a place before being able to teleport there? (Personally I feel this is vital).

Yes

> Should there be a per use cost to prevent it being too easy?

Yes

> Should teleporting use a permanent placeable item of some kind, or just involve some action which saves the location?

Not sure what this means. An object placed at the destination?

> Should other players be able to use your teleports? (Keep in mind, this would mean one player who travelled a long way could then allow others to skip all the work of exploring/ travelling. For example: instant access to deep mines.)

I'm not sure, depends on the rational

> Should you be able to set teleport points to an area another player has protected? (I know minetest_game doesn't have a protection mod, but this is still worth considering.)

I think this is fine by default, but there should be an API to allow other mods deny teleportation (think `register_can_create_teleport_to()` and maybe a setting)

**Comment by Ezhh** [comment] 2017-11-19 18:27
@rubenwardy A placeable item would be something like a travelnet box or teleport pad that remains visible as opposed to, for example, marking a location on a map which would not leave a node behind.

**Comment by paramat** [comment] 2017-11-19 21:06
@rubenwardy Seems obvious you should not be able to set a teleport point in a protected area, as that enables teleporting into player's bases if you manage to sneak into one and place a teleport point.

**Comment by Ezhh** [comment] 2017-11-19 21:34
@paramat yes, that's why personally I would rather prevent that, but it also introduces a level of complexity. For example, if you set a teleport point (especially if there is no visible indication one has been set), then someone protects that area at a later time, we're back to the same situation. [This] (https://github.com/Ezhh/warp_potions/blob/master/init.lua#L77) is how I handled the issue in my warp potions mod, but I'm not sure if this kind of check would be suitable within MTG. It works by still allowing one final use of the teleport point (so you could set a new one nearby), but then provides a warning message and disables the teleport point right after that use.

**Comment by benrob0329** [comment] 2017-11-19 21:52
Perhaps our favorite SciFi material Mese becomes quantumly entangled with another crystal, and can teleport the player to other crystal but with a high risk of loosing most of your health.

**Comment by rubenwardy** [comment] 2017-11-19 22:30
> that enables teleporting into player's bases if you manage to sneak into one and place a teleport point

What about public cities that you're not a member? Should still be allowed. I also don't really see an issue with spawning in other players bases, it's an optional thing for server which are hard core survival and PvP

**Comment by Ezhh** [comment] 2017-11-19 23:12
@rubenwardy You even get players on creative servers getting upset over people being in their homes sometimes.

It might be worth deciding whether shared teleports should be allowed, and whether there should be physical objects to place first though, because they both might change how protection needs to be considered.

**Comment by benrob0329** [comment] 2017-11-19 23:21
If teleportation is a point-to-point object (one teleporter moves you to the other, no frills) then I don't see why having to secure said teleporter would be a problem.

**Comment by paramat** [comment] 2017-11-19 23:38
Rubenwardy good point. maybe the presence of an actual node at a teleport point will help this issue since then it's visible.

**Comment by tacotexmex** [comment] 2017-12-14 16:02
This is the exact reason I use [Telemosaic](https://github.com/tacotexmex/telemosaic) originally by bendeutsch. The mod solves the above stated design issues in a beautiful way imo. I'd recommend something very similar for MTG.

**Comment by jastevenson303** [comment] 2017-12-15 14:00
Just wanted to point out that MTG comes with sethome.get/go/set functions and beds.spawn table.  minetest.conf also contains the static_spawnpoint setting, which is often used.  I think it's worth mentioning these, as they may be used in, or combined with whatever solution is best.

**Comment by raymoo** [comment] 2017-12-27 08:18
There's a system I've seen in some RPGs where you have to bind a consumable teleport item to a teleport beacon that exists in the world, and then later on you can use the item to get back there. This kind of system could force any player that wants to use it to walk there by binding the teleport item to the player that bound it to the location. Even if you don't do that, it limits how much players who haven't reached the beacon can use it, because to share the teleport, other players would have to make extras in advance.

The item could be made expensive to add a per-use cost, and the requirement of a beacon would mean you can't build a teleport point into someone's base. Beacons could also be affected by protection, if you want to keep players from binding to it, but this isn't strictly necessary because the player building the beacon could just place it outside their house, or in a cellar with locked doors like people do already with travelnet boxes.

**Comment by Ezhh** [comment] 2017-12-27 13:25
@raymoo That sounds very much like what my warp_potions mod (the one that got me thinking about this) does. You need to physically place (so protection is respected) a potion, and smash it in order to set the initial teleport point, then use of the same type of potion from the inventory will return you to that point and the potion is consumed in the process (per use cost).

**Comment by benrob0329** [comment] 2017-12-27 16:55
I would like to note that teleportation might not be the solution to not having fast ways to travel. I feel like it will become a similar situation to our tools, people get the bare minimum and go straight to diamond most of the time because there is no reason to use anything in between.

We need faster ways to travel normally IMHO, it should be progressive based on what players have already built. For example, sail boats to travel faster by canal, or trains to travel faster by track.

**Comment by Ezhh** [comment] 2017-12-27 17:59
@benrob0329  That's why there'd be a requirement to travel somewhere the slow way first. I'm completely against anything that allows you to instantly travel deep underground for resources you didn't first reach on foot.

**Comment by InfiniteOtter** [comment] 2018-01-09 18:14
There are several good mods that allow for teleportation. I love most of them. I think they should stay mods since teleportation is a fantasy/sci fi addition. I prefer having portals, but they don't really belong in the base game. Portals effect mood. A travelnet portal in the corner of the castle or woodland grove makes things a bit odd. I would prefer a glowing diagram on the floor of a castle or a ring of mushrooms in the woods.

**Comment by paramat** [comment] 2018-03-27 06:28
I've been quiet on this recently, i'm still unsure whether it should be in the game or stay separate mods, since it is somewhat special. I'm neutral at the moment, i do feel it is low priority.

**Comment by TumeniNodes** [comment] 2018-07-14 20:37
I'm throwing in the suggestion of using https://forum.minetest.net/viewtopic.php?f=11&t=9373&hilit=compassgps

With some tweaking, it could be made costly to use, as well as to have some impact on health each time it is used.
It's a simple mod, can be added/removed easily, and can be made to have adjustable risks, so it can be set by individual game-devs

So just an idea

**Comment by paramat** [comment] 2018-07-14 21:51
Doesn't seem related to teleportation though.

**Comment by Fixer-007** [comment] 2018-07-14 22:23
Teleports will interfere with carts, people should use carts, and sethome should be configurable and probably disabled by default.

**Comment by TumeniNodes** [comment] 2018-07-14 22:59
> Doesn't seem related to teleportation though.

How so? There is literally a button of the formspec to teleport the player to whichever location they have selected.
I use this mod all the time

My thought is, additons could be made to make it cost something to teleport (possibly requiring a crystal to activate it or something) and then, also impact the player with fatigue, or something as an effect from teleporting

**Comment by paramat** [comment] 2018-07-17 00:21
Sorry, the teleportation feature was hidden away amongst all the other features, didn't see that.

**Comment by raymoo** [comment] 2018-07-17 01:11
I think any material cost of using a teleporter should scale with distance, to balance against the increasing initial build cost of a minecart track. You could also balance teleporters by limiting them to sending only a certain number of players per time period. With both suggestions, you would have two tradeoffs:
- Minecarts have an expensive initial cost, while teleporters have an expensive usage cost. The teleportation cost could be something whose production rate can't scale beyond the number of players, to prevent teleporters from becoming cheap due to tech advancement.
- Minecarts are slow but can handle any number of players at the same time, while teleporters are quick but have a limited bandwidth. Depending on the cost to construct teleporters, you could construct more of them to increase bandwidth, but this takes up space, which is scarce in spawn areas or other places you might have a lot of players traveling. The space cost could be made higher by requiring the teleporter to be a large multinode structure.

I imagine that if teleporters were balanced this way, they would be used to connect locations that are traveled to less frequently, and where the value of travel is high enough to justify expensive travel. For example, secondary bases used for producing goods or forward bases used for PvP or other events.

To be safe, teleporter balance could be tweaked so that they are usually not desirable over minecarts and players can choose to use them in whatever niche they end up fitting into.

**Comment by benrob0329** [comment] 2018-07-17 01:55
Perhaps teleporters could be dangerous to the player, hurting or removing stamina (or breath) based on the distance.

**Comment by NathanSalapat** [comment] 2018-07-17 11:57
I like the way the Hyperloop mod does teleportation. You have to build a "tube" that connects both locations and then you can jump from one location to another on the system.

**Comment by tacotexmex** [comment] 2018-07-17 14:09
The way I see it, immersive teleportation can be made sense by either a low-tech/magic solution like in telemosaic, or by a high-tech solution like hyperloop. Both of those requires the traversal to both end points and both require gathering of resources.

Mods like compassgps annihilates immersion by not incorporating these features with an in-game rationale in mind.

**Comment by InfiniteOtter** [comment] 2018-07-17 14:42
I still don't think teleportation belongs in the basic game. I don't think the issue is play balance. It is an issue of style. If your server is for rugged individualists, then limit or avoid teleportation.

If a server intends to have player interaction it needs to have a good method for players to get together quickly and not just by meeting at spawn. Personally I prefer the /tphr "whoever" method to generate a teleport here request. With full teleport rights, a player can teleport to 0 -30000 0 and start mining deep without the work. Without teleportation of some form, player interaction become restricted. With /tpr requests, you still need someone to be at a location for others to go there. With /tphr, you can show things and share them.

On crowded worlds players cannot interact or even find empty areas to mine and build without portals of some sort. Putting in huge delays or forcing everyone to return to spawn can get old quickly. Throwing in a cost for using a portal is also excessive. As it is most portal schemes require mese blocks or more to set up. Someone had to dig fairly deep to make one. 

Even as rugged individualists, as the game progresses, going up and down ladders can get pretty tiresome and even using mine carts can mean you are staring at a screen for a long time doing nothing. Making a intermittent ladder speed drop can allow you to risk your neck setting up the system but get back down deep fairly quickly. This still means you are going deep by slowing yourself with a ladder every 10 or so blocks below the last and using /home to get back up to ground level.

Without a portal, on a well developed world, I cannot ever show you my home. I had to build it so far from spawn that it might take thirty minutes of your following me to see the building I made. I have quit servers just because of that issue. Why play on a multiplayer game when you can't fully interact?

The problem with portals of any kind is that there is no generic portal that will meet every need. A Telenet booth looks out of place in a dark age castle.

Play balance is not the big issue. You could require HV power to run a portal or have a tank of mese that gets depleted when a portal is used and still not solve the basic issues.

As far as mine carts vs portals go, mine carts are more fun and portals are more convenient. What I would love to see is the ability to load a mine cart, send it and have it go on it's own, drop off the load in a chest or hopper and come back to where I am mining. I need to look, it may exist somewhere.  If I could dig, drop stuff in a hopper and expect it to be delivered to a set of hoppers with overflow, I would be pretty excited by the change. If I could hit a single key and have the bottom two rows of my inventory drop into the hopper, I would be motivated to run tracks everywhere I mined.

**Comment by raymoo** [comment] 2018-07-18 01:16
My balance suggestions are for a survival setting. If you just want a fast way to move around a multiplayer building server, then I agree that my suggestion would be bad. In that case you can just use travelnets.

However, you can have player interactions with a survival-focused server too. In such a server players might form their own communities and desire travel to be less than instant to support the survival aspect of the game.

I can't think of a good Minetest example, but the Minecraft conversion mod TerraFirmaCraft is a good example of a game supporting this style of gameplay. It has a variety of fairly deep survival / crafting mechanics that interact with each other, in a way that makes it optimal to split up responsibilities and specialize, rather than try to do everything yourself. It also makes it so that ores and other key resources are concentrated in specific locations, so that the cost of travel is a significant element of gameplay. Quick and cheap travel in this setting would remove the challenge of figuring out the best way to manage the cost, which could be things like building forward bases or trading with communities / people who live near resources you don't have. I don't think TFC has advanced transport beyond boats, but balanced forms of transport would add another element to travel without making the existing strategies irrelevant.

I won't address your comments about players who are mostly playing alone (which is what I assume you meant by "rugged individualist"), because you never actually said why they wouldn't want a balanced form of teleportation available.

**Comment by jastevenson303** [comment] 2018-07-22 12:00
Amazing.  Use the beds.

**Comment by MayeulC** [comment] 2018-07-23 11:23
> The idea of beds sounds good as long as there is a material travel cost scaling with distance, and isn't just health, since health is just a cost of one apple per hp. Probably actually less, since you'll be next to a bed and could just kill yourself and pick up your items.

Mmm, that health example was just a possibility among others. Since there is a direct relationship between health and food, teleporting could also require you to have enough food in your inventory to cover the distance: IRL, you would need some provisions for travel as well (though there is no hunger in MTG). It can also provide an incentive for gathering food.

> I don't think the idea is too different from my portals suggestion though, other than flavor. They're both rate-limited, space-limited teleportation constructions that could have a per-use cost.

Indeed, this is just making it more plausible and natural, while providing quality of life improvements (select respawn location), and reusing existing items. I don't really see a better candidate.
Also as a side note: how about adding a layer of straw to the bed recipe?

**Comment by HybridDog** [comment] 2018-07-25 20:09
I use an updated version of mauvebic's bookmarks mod: https://github.com/HybridDog/bookmarks
It allows admins to define places where players can teleport to.

**Comment by tacotexmex** [comment] 2018-07-26 09:13
It seems like many of you is trying to solve the issue of multiplayer teleportation. While this is of equal importance to be solved, it seems to me that immersive and as much in-game singleplayer teleportation is what needs to be adressed primarily. After all, multiplayer teleportation systems vary depending on taste, server specifics and so on while the singleplayer experience is what MTG really is built around.

**Comment by HybridDog** [comment] 2019-08-20 16:39
Is anybody against the addition of the bookmarks mod?

**Comment by LoneWolfHT** [comment] 2019-08-20 16:42
> Is anybody against the addition of the bookmarks mod?

If we added something like that I would prefer it be this: https://content.minetest.net/packages/sofar/warps/

**Comment by DS-Minetest** [comment] 2019-08-21 10:28
There are many, many teleportation mods. Do we need another one from mtg?

**Comment by tacotexmex** [comment] 2019-08-21 16:11
Yes, why not. A well-written, API-enabled and in-game based one that others can exted upon.

**Comment by TumeniNodes** [comment] 2019-08-21 19:24
Why not just merge compassGPS into MTG?
https://forum.minetest.net/viewtopic.php?t=9373

**Comment by paramat** [comment] 2019-08-22 00:21
I prefer teleportation is left to optional mods, i don't want to keep adding low priority features to MTG. It's also quite specialist and the implementation a matter of taste.

**Comment by paramat** [comment] 2019-08-29 00:10
.. so i disagree with this being in the roadmap.
This also doesn't have any stated core dev support yet, although perhaps rubenwardy supports it?

**Comment by paramat** [comment] 2020-08-28 20:58
Closing due to #2710 and no support from other core devs.
I think it is best to leave teleportation to optionally added mods, as the desired implementaton will very so much.

**Closed by paramat** 2020-08-28 20:58 UTC
Labels: Feature request
