### ISSUE TITLE
Can interact with world while sleeping

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1951] opened 2017-11-20 08:02 UTC
While you're asleep, you can still interact with the world. You can dig, rightclick, punch, place blocks. Or eat apples. All in your sleep.
You can even try to dig your own bed in your sleep!

**Comment by MarkuBu** [comment] 2017-11-20 08:08
Maybe you are a somnambulist

**Comment by NewbProgrammer101** [comment] 2017-11-20 17:17
Reproduced the issue.

This should be fixed lol.

**Comment by paramat** [comment] 2017-11-20 21:44
Sure that 'asleep' isn't actually 'falling asleep'? I would have thought the 'asleep' part never happens since it is unconciousness.
Being in bed doesn't have to stop interaction.

**Comment by BluebirdGreycoat** [comment] 2017-11-21 00:46
I think we do need a way to temporarily disable interact for a player without actually revoking interact, which could result in an issue if the server crashes. Plenty of uses, not just beds. Remember how kicking a player used to be done? Ban, then unban. Then we got kick_player. This is sort of the same thing.

**Comment by Fixer-007** [comment] 2017-11-21 21:13
>Sure that 'asleep' isn't actually 'falling asleep'? I would have thought the 'asleep' part never happens since it is unconciousness.

But night skip suggest loss of unconsciousness.

**Comment by jastevenson303** [comment] 2017-11-22 06:27
Is this the bug where the formspec doesn't show up in bed?  Seems to be
related to latency.

**Comment by BluebirdGreycoat** [comment] 2017-11-22 08:39
Not necessarily.

**Comment by jastevenson303** [comment] 2017-11-22 10:04
Is that what this is about, though?  Because sometimes the formspec shows up, restricting my access to interact with the environment, and other times it doesn't show up (but still skips night and exits bed) and during this time I can interact.

Wanted to make sure.  The issue states this as a constant, but that hasn't been my experience.

**Comment by paramat** [comment] 2019-02-21 02:21
Duplicated in #2317 
Reopen to consider if interaction should be disabled when lying in bed awake, i can't see a problem and low priority.

**Closed** 2019-02-21 02:28 UTC
Labels: Not a bug, Request / Suggestion
