### ISSUE TITLE
Spam-tapping on beds and more...

### ISSUE THREAD

**Issue by EGYT5453** [minetest/minetest_game#3066] opened 2023-09-26 18:44 UTC
I thought that the bug I encountered was related to the "beds" mod (maybe it still is.)

https://github.com/minetest/minetest_game/assets/113429882/416645a3-9dec-437d-96b6-7c0fa3e679e8

Short description:
The current day was 92;
I spam-tapped on the bed to lie down and get up again and again;
After waking up and seeing "You can only sleep at night", the current day was 99.

==========

But then I remembered about a bug I found earlier.
I was spam-tapping under myself, swimming in lava. Somehow Sam has become invincible (although he can't interact with the world. (place blocks, execute commands etc.))

https://github.com/minetest/minetest_game/assets/113429882/4d5000e0-3609-43b0-af2a-625b37515cf7

https://github.com/minetest/minetest_game/assets/113429882/06f957c4-851c-43cc-b1e8-7f3fc5124760

Sorry for the low quality, GitHub doesn't allow files larger than 10MB.
Also, I don't fully understand how to replicate it. Sometimes it does, sometimes it doesn't.

If it helps, I was playing build 5.7.0 from F-Droid.

**Comment by appgurueu** [comment] 2023-09-26 19:33
Your first report seems like a genuine bug: After the first skipped night, it should be day, so you shouldn't be able to sleep again. This looks like a race condition; I'll look into it.

The second report is unfortunately an engine issue.

**Comment by EGYT5453** [comment] 2023-09-26 21:33
I noticed that if you wake up before the day starts, it will be night for a few seconds, and the morning will start exactly when it would have started if you hadn't woken up before it. Maybe this is why it's possible to spam-tap the bed and skip days - MTG will add +1 to the days counter, but after you get out of bed, not after the morning starts (this is just a theory, as the only thing I've seen from the MTG code is the translation files.)

https://github.com/minetest/minetest_game/assets/113429882/ebd239fa-c42a-453d-b22a-f5506a40666c

Oh, and sometimes Sam doesn't want to lie in bed and sit in the boat, but that's off topic and probably already reported...

**Comment by appgurueu** [comment] 2023-09-26 21:36
> [bed night skip bug stuff]

I've already found the issue and submitted a PR to fix this, see https://github.com/minetest/minetest_game/pull/3067.

> Oh, and sometimes Sam doesn't want to lie in bed and sit in the boat, but that's off topic and probably already reported...

Yeah, that's indeed a duplicate of https://github.com/minetest/minetest_game/issues/3043. This is an engine issue too and has already been fixed in 5.8-dev, which will hopefully be released soon (probably in about a month or two).

**Closed** 2023-09-29 20:31 UTC
Labels: Bug
