### ISSUE TITLE
Change title and icon of non-stable minetest_game to "testing"

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest_game#1809] opened 2017-06-29 04:33 UTC
There is a stable branch which I use for normal playing and a master branch for testing, if they were `Minetest` and `Minetest (testing)` or `Minetest (non-stable)` it would be easier to know which one is stable and which one is not.
I'm not sure it's a good idea because anyone may do this him/herself.

**Comment by Wuzzy2** [comment] 2017-06-30 23:59
Except this is called “Minetest Game”, not “Minetest”.

**Comment by paramat** [comment] 2017-07-02 04:24
Is there currently any way to know what version MTG is? If not that might be useful.

**Comment by Wuzzy2** [comment] 2017-07-02 11:00
I think subgames don't allow for any metadata whatsoever, except their official name in `game.conf`.

**Comment by Fixer-007** [comment] 2017-07-02 13:26
>Is there currently any way to know what version MTG is? If not that might be useful.

related https://github.com/minetest/minetest_game/issues/1494

**Comment by paramat** [comment] 2017-07-02 14:04
I'd be happy for it to be stored anywhere in a simple .txt form, not necessarily visible in-game.

**Comment by paramat** [comment] 2017-07-16 02:13
:-1: For the request in 1st post.

**Comment by Wuzzy2** [comment] 2017-07-16 14:04
I also disagree with this feature request. Reason: The data is non-atomic. It conflates two independent data points: The name of the subgame and the development state (testing vs release). 

Better to store this information (+ version number, if there is one) in the metadata as a separate data point.

**Comment by paramat** [comment] 2017-07-17 08:12
^ Yes.

**Comment by farooghkz** [comment] 2017-07-24 15:16
@paramat, if it's not necessary to be visible in-game, so how I would **easily** know which one is stable and which one is testing(or non-stable)?

**Comment by paramat** [comment] 2017-07-24 16:00
However the version is stored, it will be easily seen, even if it's a text file you open, it doesn't have to be visible in-game, although that may be possible somehow).

**Comment by farooghkz** [comment] 2017-07-25 13:21
@paramat: the version is stored?where?

**Comment by octacian** [comment] 2017-07-25 14:21
I disagree with the initial suggestion as well; it's not a good way of implementing this for multiple reasons. It would be better to add some parameters to `game.conf` such as `version` and `release_type` (to determine if `stable` or `dev` version - there's probably a better name).

**Comment by paramat** [comment] 2017-07-25 17:05
Sorry, it isn't stored yet, i just mean if it is, it will be easy to access.

**Comment by farooghkz** [comment] 2017-07-25 17:46
> I disagree with the initial suggestion as well; it's not a good way of implementing this for multiple reasons. 

Why?I am interested in knowing those reasons.
If it should not be visible in-game, yet it's a good idea to mention it somewhere.

**Comment by paramat** [comment] 2017-08-13 10:24
Duplicate of #1494 please continue discussion there.

**Closed by paramat** 2017-08-13 10:24 UTC
Labels: Duplicate, Request / Suggestion

**Comment by farooqkz** [comment] 2018-01-13 08:41
@paramat, consider I have 2 versions(stable and non-stable) of minetest_game in my games folder and I want to create a new world and play. Which Minetest game should I choose to create my new world?

**Comment by paramat** [comment] 2018-01-13 11:32
Best to not have both versions in the games folder, it's rare that anyone does.

**Comment by farooqkz** [comment] 2018-01-13 13:13
So how people do testing?
