### ISSUE TITLE
enable_fire setting default is misleading

### ISSUE THREAD

**Issue by Desour** [minetest/minetest_game#3166] opened 2024-11-14 19:01 UTC
If `enable_fire` is not set explicitly, it defaults to true on singleplayer and false otherwise.
But the setting in settingtypes / in the mainmenu is only a bool, which defaults to true.
I tried to test something with fire, and looked into the settings menu to check that it's enabled. The ticked checkbox suggested it was, but it wasn't. It's very confusing, and can't be figured out without looking into the code.

An enum instead of a bool would be more appropriate.

**Comment by appgurueu** [comment] 2024-11-15 00:28
I agree. An enum feels overcomplicated. I get the idea but this is probably intransparent to server owners as well.

Frankly I would be inclined to simplify this to just a bool. Is it really that bad if we start enabling fire by default on servers?

**Comment by sfan5** [comment] 2024-11-15 09:49
duplicate of #2678

**Closed by sfan5** 2024-11-15 09:49 UTC
