### ISSUE TITLE
Items should be picked up If You Walk into them (not by hitting them)

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest_game#1051] opened 2016-04-22 20:39 UTC
Now you have to sort of Hit the item to pick it up this is okay but if you have a lot of items scattered around this can be extremely annoying I speak from experience UHhhhhhh. also it's faster en more efficient to just walk into it and just pick it up (NOTE) there would be a timer on it so you don't instantly pick it up again maybe like Five Seconds?

**Comment by NathanSalapat** [comment] 2016-04-22 21:26
There is a mod that does this item_drop.

**Comment by C1ffisme** [comment] 2016-04-22 21:55
@NathanSalapat "There is a mod" isn't a good argument, since it prohibits other ideas from mods becoming features in the game.

I would personally enjoy this, but only for items dropped by TNT, and other players. It would be annoying to drop an item, only to pick it up again.

**Comment by tobyplowy** [comment] 2016-04-22 23:19
@C1ffisme yes there would be a timer on it so you don't instantly pick it up again maybe like Five Seconds?

**Comment by tobyplowy** [comment] 2016-04-22 23:25
@NathanSalapat The fact that it is a Mod that doesn't mean that it can't be added to the game. (At least That's My opinion) :/

**Comment by C1ffisme** [comment] 2016-04-23 00:47
@tobyplowy My basic idea is that the clicking to get items feature should remain, and only certain objects can be picked up again. Throwing an item? If you need to pick it back up, you can probably do that with your mouse. Blowing up TNT? You probably need to catch all those items. It's a bit annoying.

**Comment by everamzah** [comment] 2016-04-23 01:21
I think it would be ideal to automatically pickup an item as you walk immediately over it, and that this behavior ought to be settable by the client.

**Comment by DonBatman** [comment] 2016-04-23 02:18
I like the idea of item pickup but only in minetest_game. The engine should remain as is. I am thinking of games that would need you to pick up items.

**Comment by tobyplowy** [comment] 2016-04-23 08:26
@DonBatman It Could be a setting in the mod It Self so we can program it so you don't pick it up but have to click it.

**Comment by tobyplowy** [comment] 2016-04-23 08:27
@everamzah Yes That's exactly What I was trying to say Thank You For commenting :)

**Comment by paramat** [comment] 2016-04-23 10:29
:-1: It's more convenient for a player but much more complex to do this, Minetest is simple for good reason. It's better i feel to choose when or whether to pick something up, for example when in a confined space. It's also not needed as much since dug items go straight into inventory.

**Comment by C1ffisme** [comment] 2016-04-23 14:33
> I feel it's better to choose when or whether to pick something up, for example when in a confined space.

@paramat Like I suggested, objects dropped by the player himself should not be picked up. But items from other players and TNT should be picked up.

> This is mostly an engine issue, it would be too slow in lua anyway.

Surely not. Maybe moving many items towards you, but definitely not deleting an entity and preforming inventory actions every time you walk over the entity.

> I think it would be ideal to automatically pickup an item as you **walk immediately over it**

This.

**Comment by paramat** [comment] 2016-04-25 06:42
> objects dropped by the player himself should not be picked up. But items from other players and TNT should be picked up.

That's even more complex :)

**Comment by tobyplowy** [comment] 2016-04-25 08:40
@paramat haha lol thets true XD

**Comment by 0-afflatus** [comment] 2016-04-25 11:43
I'm so used to Minetest behaviour that picking up on collision would seem weird. It's a long-running argument and the existence of a mod does make this possible. If you're arguing for an engine change you really do have to come up with a good argument as to how this will benefit the game and be better than a mod.

**Comment by C1ffisme** [comment] 2016-04-25 15:34
@paramat Not really, all that would have to be done is to add a `player` variable to dropped items. This variable is set to the player that dropped the item. The player whose name is in the variable cannot pick it up automatically, but can punch it.

TNT would set the variable to `nil`, so that any player can pick it up.

**Comment by sofar** [comment] 2016-04-25 17:27
Way too complicated.

First, I'm not for including this as a default, unless the whole drop-on-dig model gets changed as well.

Second, each dropped item has an ```age``` timestamp. Just don't allow auto-pickup of items that have an age less than 2 seconds, and the problem is solved.

**Comment by C1ffisme** [comment] 2016-04-25 17:45
@sofar Eh... Okay.

**Comment by tobyplowy** [comment] 2016-04-25 19:19
@C1ffisme I'm confused and a bit Scared :smile:

**Comment by tenplus1** [comment] 2016-05-01 07:29
Personally I prefer that players need to punch dropped items to pick them up, just walking over them to do so isn't realistic and a pain if you are walking through an area with loads of dropped items from other players.

**Comment by C1ffisme** [comment] 2016-05-01 18:46
@tobyplowy I was too tired to come up with a sensible argument at the time.

Our community seems to have trouble giving into another's opinions, and knowing when an argument is lost, and it's just best to stop.

@tenplus1 It's realistic, but it's not practical. With the changes to TNT that @sofar has made, TNT drops a lot of items, and it's not very easy to find all of the itemstacks, point at their rather small selection boxes, and click, for every itemstack. Often the server deletes all of the items before you can get them all.

**Comment by sofar** [comment] 2016-05-01 19:13
@C1ffisme the last version of tnt (just merged) keeps the amount of stacks under control.

I don't want to make items pickup automatically since I want some deterrence from using TNT as a regular tool. Making it easy to pick up items from a TNT explosion would make it too convenient.

**Comment by C1ffisme** [comment] 2016-05-02 15:51
@sofar But that is... What TNT is...

A tool.

For mining.

And not collecting quite as much cobblestone. (Since TNT only drops 1/3 as much cobblestone.)

I can't see any other reason for having TNT in vanilla Minetest, other than for traps in multiplayer. (Or for simple fun in creative mode, but survival players would not concentrate on blowing things up.)

**Comment by paramat** [comment] 2016-05-02 18:43
> I don't want to make items pickup automatically since I want some deterrence from using TNT as a regular tool. Making it easy to pick up items from a TNT explosion would make it too convenient.

I agree.

**Comment by C1ffisme** [comment] 2016-05-03 17:16
@paramat I think it's a lot simpler to run over items then to aim and punch.

Besides that, it's generic game behavior. When you run over coins/rings/items, you pick them up.

**Comment by tobyplowy** [comment] 2016-05-03 18:06
@C1ffisme exactly It's a lot More convenient better and simpler And faster

**Comment by numberZero** [comment] 2016-05-11 17:15
This should be configurable. Preferably in client but as that is not supported two lines in minetest.conf would be fine too (one for MC-style drops and one for pickup).
`item_drop` is good but is not configurable (I personally like MC-style pickup but not drop) and manual drop didn’t work properly in version I tried

**Comment by paramat** [comment] 2016-05-12 17:37
I'm talking about code simplicity, MC behaviour is complex to implement.

**Comment by sofar** [comment] 2016-05-12 19:23
I'd have no issues with `item_drop` or a better version being *bundled* together with minetest. But I still don't want it enabled as the poster requests.

I suggest closing this feature request.

**Comment by paramat** [comment] 2016-07-03 17:20
This is more of an engine issue, as the only efficient way to do this is there. Perhaps you could open an engine issue, then if it is added you can request it here in MTGame.

**Closed by paramat** 2016-07-03 17:20 UTC
Labels: Feature request, Needs engine-change
