### ISSUE TITLE
Placing waterlily with a stack of 1 results in two visible lilies.

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#1046] opened 2016-04-21 02:55 UTC
![screenshot_20160420_225033](https://cloud.githubusercontent.com/assets/1761623/14696635/d19d9742-074a-11e6-95c9-d9dd9bc2450f.png)

This visual glitch doesn't appear when there's a remaining stack of lilies.

**Comment by paramat** [comment] 2016-04-21 05:29
@kilbith 
When waterlily is placed normally it does very briefly appear underwater then disappear.

**Comment by sofar** [comment] 2016-04-21 06:20
it's probably placement prediction. Disabling it may be a better effect.

**Comment by kilbith** [comment] 2016-04-21 08:25
I placed like ~500 lilies and I never seen that. I suspect he uses a different code. Anyways you know pertinently that : 

- It's not a bug, but the placement prediction (visible also when you place a lily onto a non-water node).
- It's not solvable in Minetest Game, if you believe it's a bug.

**Comment by kilbith** [comment] 2016-04-21 08:41
It's certainly an engine bug, I could find a workaround in Minetest Game but not solving the root cause.

**Comment by paramat** [comment] 2016-04-21 09:45
Workaround is fine for now. maybe we'll fix the engine issue during freeze.

**Comment by PilzAdam** [comment] 2016-04-21 10:32
Disabling placement prediction for waterlilies seems fine.

**Comment by kilbith** [comment] 2016-04-21 10:39
Solved with : https://github.com/minetest/minetest_game/pull/1048

**Comment by paramat** [comment] 2016-04-22 12:34
Please keep this issue open until we fix the engine issues.

**Comment by paramat** [comment] 2016-04-23 19:14
#1048 is merged.

**Closed by paramat** 2016-04-23 19:14 UTC
Labels: Bug
