### ISSUE TITLE
Serious bug with saplings. on_rightclick vs on_construct. formspec

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest_game#1304] opened 2016-10-04 10:35 UTC
So a player just reported that he wanted to open a locked chest, he was holding a sapling and somehow the chest node got replaced with the sapling.

I noticed that if you are holding a sapling and open a regular chest, the chest opens normally, but if you do the same with a locked chest, the sapling is placed there instead of the chest getting opened.

There's is not track record at all about him placing a sapling on the server log, but we were experiencing a lot of 
```
<WARNING> 2016-10-04 07:23:14: [Server] Deprecated call to get_look_pitch, use get_look_vertical instead
```
Around the time that happened.
And we have this around the time too.
```
<ACTION> 2016-10-04 07:22:50: [Server] buttatoes punches object 3733: LuaEntitySAO at (150.181,5.70101,-3484.2)
```

**Comment by pilino1234** [comment] 2016-10-04 12:25
Can't reproduce on latest commits of MTG and Minetest.

**Comment by t4im** [comment] 2016-10-04 14:25
Nothing weird about that. I actually predicted it [here](https://github.com/minetest/minetest_game/pull/1208#r72297657)

**Comment by paramat** [comment] 2016-10-04 16:59
Sure it's due to ignore? and why locked not unlocked chests?

**Comment by t4im** [comment] 2016-10-04 17:23
Locked chests just send the formspec as part of their `on_rightclick` to check the owner first, which wouldn't be passed yet from saplings anyway.

Unlocked chests on the other hand set their formspec metadata during `on_construct` already; so the client has the chance to intercept that "rightclick" and open the formspec before a placement would be attempted server side.

**Comment by t4im** [comment] 2016-10-04 17:52
@Megaf  Not a locked chest bug at all. Just saplings. #1306 should fix it.

**Comment by Megaf** [comment] 2016-10-04 17:52
@t4im Better title now?

**Comment by paramat** [comment] 2016-10-05 21:29
#1306 merged.

**Closed by paramat** 2016-10-05 21:29 UTC

**Comment by Megaf** [comment] 2016-10-05 22:28
Thanks.
