### ISSUE TITLE
Visual glitch between the two halves of beds

### ISSUE THREAD

**Issue by NewbProgrammer101** [minetest/minetest_game#1952] opened 2017-11-21 18:10 UTC
The differences between bed_top and bed_bottom have a minor collision in between. There is a small line dividing the two parts of the bed. Example:

![2v1ku9e](https://user-images.githubusercontent.com/3686677/35184094-ee7857c6-fde8-11e7-9fb5-77460568f041.png)

The shading is also different between the two. Example:

![a9l2s0c](https://user-images.githubusercontent.com/3686677/35184098-feee23ce-fde8-11e7-8f4d-5b3c057f0f35.png)

The shading is lighter on the left; whereas, it's darker on the right. You can also see the brown line dividing the two parts of the bed.

**Comment by Fixer-007** [comment] 2017-11-21 21:14
Use basic beds instead, they connect nicely.

**Comment by paramat** [comment] 2017-11-22 21:08
This will be fixed by #1923

**Comment by NewbProgrammer101** [comment] 2017-11-22 21:09
Cool. :)

**Comment by paramat** [comment] 2018-01-20 14:01
I can't reproduce these issues.

**Comment by TumeniNodes** [comment] 2018-01-30 16:21
I can confirm more than just this visual glitch.
Although I am on 0.4.16 stable, not aware if this was fixed in most recent builds
I have some close up shots if anyone wants to look
https://ibb.co/album/cxy10a

**Comment by NathanSalapat** [comment] 2018-01-30 16:26
The problems you are seeing @TumeniNodes are due to filtering and antialiasing. The pixels are being blurred with the adjoining pixels that aren't visible, and it produces those lines. If you turn off filters you'll see that the problems have gone away. I don't know if there is any easy way to fix this, as the filtering just blurs with adjacent pixels, and if those pixels are a very different color, as they often are with uv maps, you get artifacts. What I usually do to prevent this on my models is provide a pixel or two of 'bled' space, so when a texture blurs it has more of the same color to blur with. I'm not sure if the beds are using UV maps, or if that is a nodebox, but either way it is probably the same cause and effect.

**Comment by TumeniNodes** [comment] 2018-01-30 16:33
You are absolutely correct Nathan

With all filtering off the issues go away, aside from a small line of white dots along the seam of the two halves of the beds...
So, still something to look into over time, as it is still a visual bug which is unwanted when someone is using a feature which is included.

Thank you for point that out, that would have probably been one of the last things I looked at

**Comment by paramat** [comment] 2018-01-30 17:59
I see you don't get one half of the bed darker than the other.

Just realised the thread author has smooth lighting off, duh, that's why.
If there is any issue here it's an engine issue.

**Closed by paramat** 2018-01-30 17:59 UTC
Labels: Models, Textures, Unconfirmed bug
