### ISSUE TITLE
New leaf decay doesn't work as expected

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1663] opened 2017-03-23 13:54 UTC
I started a small survival game with the latest versions of MT and MTG. I build an axe and cut down some trees. Sadly no all leaves decay as expected

![screenshot_20170323_144537](https://cloud.githubusercontent.com/assets/16163058/24250653/f0af989c-0fd7-11e7-8eb7-239f79737cf9.jpg)

![screenshot_20170323_145351](https://cloud.githubusercontent.com/assets/16163058/24250872/991c38f0-0fd8-11e7-8d79-045ddc4319a9.jpg)

There are no trunks near this leaves

**Comment by paramat** [comment] 2017-03-23 17:30
Weird, i changed appletrees to make sure they have at least 2 opposing branches, and all leaves are within 3 nodes of these 2 guaranteed branches. This looks like mgv7?

**Comment by paramat** [comment] 2017-03-23 17:39
Did you use a mod to select mgv7 as the mapgen while mgv6 was set in menu? This could set the wrong radii, i might have to not use mapgen detection and just increase radii to the larger value for each tree.

**Comment by MarkuBu** [comment] 2017-03-23 18:29
New v7 map. No old stuff

**Comment by sofar** [comment] 2017-03-24 04:31
please reproduce this with minetest_game instead first.

**Comment by MarkuBu** [comment] 2017-03-24 07:21
It is plain minetest_game, cloned two days ago from github, just with the hunger mod, some other mods that don't effect leaf decay and pixelperfection TP

**Comment by Fixer-007** [comment] 2017-03-25 14:29
I think I've also seen this on hometown server too.

**Comment by Fixer-007** [comment] 2017-03-25 14:41
Reproduced in newest minetest_game with v7 world on this trees:
![default](https://cloud.githubusercontent.com/assets/16494741/24323140/e706d884-1179-11e7-9763-098c6d96f615.png)

**Comment by MarkuBu** [comment] 2017-03-25 15:55
If trees are standing to close they don't decay well. There are too large cluster of leaves left. And sometimes a single leaf node doesn't decay even if no trunk is near, but I don't know why.

**Comment by sfan5** [comment] 2017-03-25 16:48
@paramat 

^ This is rather annoying as the new leafdecay is supposed to work as good as the old one.

**Comment by MarkuBu** [comment] 2017-03-25 17:38
To be honest, this leaf decay works as good (or as bad) as the old one. When I developed the new system one goal was to have a better working system.

While developing the new system I noticed, that sometimes (rare, but it happend) leaves are left in the air without any trunk near. I don't know why it happend. With my solution I never had leaves left and the ugly clusters are smaller. They happen because of the leaf decay radius of 3 for apple trees. I reduced this radius to 2.

But this was revised for no reason

**Comment by sofar** [comment] 2017-03-25 18:26
Is it only apple trees that this happens with?

@paramat increasing the radius by 1 really isn't that expensive

**Comment by MarkuBu** [comment] 2017-03-25 20:08
If you add 1 to the radius in this line you can reduce the leaf decay radius to 2 for all trees

```
	for _, v in pairs(minetest.find_nodes_in_area(vector.subtract(pos, def.radius + 1),
			vector.add(pos, def.radius + 1), def.leaves)) do
```

**Comment by paramat** [comment] 2017-03-25 22:54
Will test again, it's odd because the radius for appletrees is set to 3 for mgv7, i can't see how this is happening.
This may not be a case of increasing radius but some other issue. Let's look for that issue instead of just increasing radius.

> They happen because of the leaf decay radius of 3 for apple trees. I reduced this radius to 2.
But this was revised for no reason

I doubt it. It was raised to 3 for good reason, mgv7 appletrees can have leaves 3 nodes away from a trunk node, try reducing radius to 2 and you'll see far more leaves remaining.
Mgv6 trees have leaves no more than 2 nodes away so the radius is set to 2 in that mapgen.
We chose 1 radius value for both searches for good reason, you have not yet explained why having 1 radius larger than the other is necessary.

**Comment by paramat** [comment] 2017-03-25 22:58
Hang on i think i see a cause.

**Comment by MarkuBu** [comment] 2017-03-25 23:50
I did explain it. I even posted screenshots. As you know apple and aspen trees need a radius of 3. But just to get some leaves at the top. The side effect is, that a lot of leaves don't decay. It can happen that a whole canopy can't decay if you cut a tree between two other trees, because all leaves are inside the radius of the neighbour trees.

With my code all leaves in a radius of 3 are triggered, but they decay down to a radius of 2

**Comment by MarkuBu** [comment] 2017-03-25 23:54
Btw: I still don't know why sometimes a single leaf doesn't decay. It should happen with my code too. Maybe a coincidence

**Comment by paramat** [comment] 2017-03-26 00:43
Ok sorry i may be misunderstanding something.
Both radii need to be equal or larger than the max distance of a leaf from a trunk though.
We may need to raise one or both radii to fix this bug but i want to work out why it is happening first.

**Comment by MarkuBu** [comment] 2017-03-26 06:35
No, you don't need to raise both radii. I posted a line of Code above with a little change

After that you can set all leaf decay radii to 2.

**Comment by Fixer-007** [comment] 2017-03-26 12:34
It is not only apple, I've seen leaves of pines and other custom trees hanging (including lone blocks as MarkuBu described).

**Comment by paramat** [comment] 2017-03-26 19:16
> After that you can set all leaf decay radii to 2.

I doubt it, if you update a leaf that is 3 nodes from a trunk (as on appletrees) it will decay when it should not.
Your line of code is fine because it adds 1 to the first search, but the registered radius cannot be reduced.

**Comment by paramat** [comment] 2017-03-26 19:20
Could it be because some appletree schematics are rotated, so the leaves are rotated, some leaves will have rotation = 1 so they don't decay?
We could then have leaves be given a rotation > 3 if player-placed to stop this.

**Comment by paramat** [comment] 2017-03-26 19:53
However if leaves with rotation 0-3 are allowed to decay, existing player-placed leaves will decay too.
If leaves textures work ok upside down we could have all schematics have leaves with rotation 20 (upside-down) then when rotated their params will not be 0-3.

**Comment by MarkuBu** [comment] 2017-03-26 20:13
Why should the rotation has an effect on the decay? Is param2 really set to rotated trees?

**Comment by paramat** [comment] 2017-03-26 20:45
I'm wrong, leaves are not 'facedir' so are not rotated when a tree schematic is rotated. I just remembered that leafdecay ABM also checked for param2 to decide decay, so this isn't the problem.

**Comment by paramat** [comment] 2017-03-26 20:53
If it helps maybe we can boost the first search by 1 as you suggest, while we try to work out why this happens.

**Comment by paramat** [comment] 2017-03-27 04:45
My next guess is possible strange behaviour caused by trying to start a timer that is already running.
There is a function for detecting whether a node timer is already running (is_started()), perhaps this can be checked before a timer is started on a leaf.
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2869

**Comment by paramat** [comment] 2017-03-27 19:30
@sofar from your experience of nodetimers could a double-start ^ be causing problems?

**Comment by Fixer-007** [comment] 2017-03-28 22:32
Decided to clear up my forest, that's how it ended up (some of those leaves may be placed by me) on hometown server, not sure if @ExeterDad did any changes to mtg but it seems more or less ok when all trees are cleared up, but less ok when there nearby ones:
![default](https://cloud.githubusercontent.com/assets/16494741/24430443/55189a36-141f-11e7-8df2-e2726d329406.png)

**Comment by MarkuBu** [comment] 2017-03-28 22:46
I'll try to find the problem tomorrow

**Comment by ExeterDad** [comment] 2017-03-29 05:19
@Fixer-007 Nope no changes to MTG other than moving the nyan cat to the worldmods dir. MT and MTG are a pull from last night and installed at the scheduled restart. I'm assuming your test was during the day today.
Today was the first I've noticed the new leaf decay in action. I like it, and like how it leaves a natural shape of the neighboring trees. There were many leaves left behind. But I have to accept that I was cleaning up previously and partially dug trees from other players.

**Comment by paramat** [comment] 2017-03-29 06:06
I'll probably edit the code to avoid starting a nodetimer that is already running, it may not fix the bug but is a good idea anyway.

**Comment by MarkuBu** [comment] 2017-03-29 06:52
I think I found one reason. This trunk holds this leaf. The trunk is 3 nodes away in each axis, so in the outer most corner. It is more an optical illusion. You think, that there is no trunk near

![screenshot_20170329_083315](https://cloud.githubusercontent.com/assets/16163058/24441676/013816d0-145b-11e7-86ff-d5440ccb15bd.jpg)
![screenshot_20170329_083331](https://cloud.githubusercontent.com/assets/16163058/24441675/0137ec32-145b-11e7-81a0-10062f75bdf5.jpg)

@Fixer-007 does the hometown server uses the new leaf decay? What kind of trees did you cut?

**Comment by MarkuBu** [comment] 2017-03-29 08:44
I can't reproduce what happen on the hometown server, but i still think a radius of 3 is to much for apple trees. 

![screenshot_20170329_104031](https://cloud.githubusercontent.com/assets/16163058/24446030/5b6e33c6-146c-11e7-8a95-44a995598cb9.jpg)

**Comment by Fixer-007** [comment] 2017-03-29 13:05
Apple trees.

**Comment by MarkuBu** [comment] 2017-03-29 13:34
Weired. Maybe I'll visit hometown

**Comment by MarkuBu** [comment] 2017-03-29 14:43
Strange server. I found more diamonds on the first day than coal and iron :rofl: 

I cut some trees, but everything decays until now. But with the same effect that a lot of the leaves don't decay if another tree is close. Sometimes a whole canopy wont decay

I still suggest to reduce leaf decay radius to 2 and add 1 to the radius in the `leafdecay_after_destruct` function as described before for aesthetic reasons and to make cutting trees easier.

**Comment by paramat** [comment] 2017-03-29 19:50
It can't be reduced to 2 because appletree leaves are valid up to 3 nodes away from a trunk node, as leaves get updated by nearby digging complete appletrees will lose their intended shape.
However, i would indeed like to redesign appletrees to only need a radius of 2, but then pre-existing trees will not decay completely.

**Comment by paramat** [comment] 2017-03-29 19:55
@Fixer-007 in your 1st comment those leaves may be preserved by wood of nearby trees.
But this behaviour is no worse than previous leafdecay. Previously all leaves had radius 3, now most have a radius of 2.

**Comment by MarkuBu** [comment] 2017-03-29 20:35
@paramat if you add 1 to the radius in `leafdecay_after_destruct` you CAN reduce the radius to 2. 

```
	for _, v in pairs(minetest.find_nodes_in_area(vector.subtract(pos, def.radius + 1),
			vector.add(pos, def.radius + 1), def.leaves)) do
```

The results are much better. Much less leaves left in the air and no wired single flying leaf nodes. It is annoying to cut all the leaves they are left

**Comment by paramat** [comment] 2017-03-29 21:19
The search for trunks near the leaf will have radius 2, meaning leaves will decay despite being within 3 nodes of a trunk as the appletree design intends. So yes more leaves will decay but only because valid leaves are decaying when they should not.

**Comment by MarkuBu** [comment] 2017-03-29 21:28
I think this is acceptable

**Comment by paramat** [comment] 2017-03-29 21:42
No it's not acceptable at all. If player is buildning a log cabin near a tree, placing and removing log nodes, leaves on nearby trees will start decaying despite being part of a valid tree design, this iwll remove the tops or corners from appletrees.

**Comment by MarkuBu** [comment] 2017-03-30 08:06
This is a rare situation. Cutting trees in a dense forest is rather common

**Comment by paramat** [comment] 2017-03-30 18:56
Yes, it was not a good example, this will also happen when you dig the trunk nodes of nearby trees.

**Comment by paramat** [comment] 2017-04-01 01:49
This bug should be rechecked to see if there are any trunks within 3 nodes of remaining leaves.

**Comment by paramat** [comment] 2017-04-28 03:41
Cannot reproduce and suspect trunk nodes are within a 3 node cubic radius, will close in a few days unless further tests confirm a bug.

**Comment by Fixer-007** [comment] 2017-09-11 12:44
Here is another example, found them on Calinou server (0.4.16) few days ago:
![brymtss](https://user-images.githubusercontent.com/16494741/30274924-17748c28-9708-11e7-8242-44aae0bd3988.png)

**Comment by paramat** [comment] 2017-09-11 17:25
Interesting, no trunk nodes near those this time. There must be some situations that cause this through some not-yet understood process. At least this seems rare.

**Comment by paramat** [comment] 2018-03-27 06:57
Seems quite rare and is unexplained, we can reopen if many experience this but i think it may just be random occasional weirdness, so closing for now.

**Closed by paramat** 2018-03-27 06:57 UTC
Labels: Bug, Low priority, Obscure
