### ISSUE TITLE
Bright Mese Ore node looks weird

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest_game#680] opened 2015-09-19 14:08 UTC
Some people (including me) find the Mese Ore node looking weird due to its whole brightness : https://forum.minetest.net/viewtopic.php?f=6&t=13260

Also it makes the discovery too easy.

I suggest to remove that line : https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua#L759

**Comment by PilzAdam** [comment] 2015-09-19 14:35
Try increasing it to 2; this would illuminate the neighbors, so it doesn't look so out-of-place.

**Comment by kilbith** [comment] 2015-09-19 17:28
When nodes are generated (and not placed), the light don't spread properly around them.

**Comment by paramat** [comment] 2015-09-19 17:28
I'll try that. Seems that smooth lighting is sometimes failing.

**Comment by kilbith** [comment] 2015-09-19 17:34
I think the lighting on that node should be removed totally, since we don't have partial lighting that only illumine the ores but all the stone part on this node. This doesn't look right.

**Comment by paramat** [comment] 2015-09-21 16:00
![screenshot_20150921_165330](https://cloud.githubusercontent.com/assets/3686677/9997089/3250d3c6-6082-11e5-9404-53d02caf3bfe.png)

+1 for removing light from this node. Light could be the special case for a complete mese block.
Testing, in completely dark caves the smooth lighting usually works and looks fne with light level 1 or 2, the problem is when there ia some other light in the cave like torches or lava, the whole node is brighter with a hard edge and this looks bad.

**Comment by PilzAdam** [comment] 2015-09-21 16:22
Can a subtle "glow" of the mese ore somehow be faked by brightening the texture?

**Comment by paramat** [comment] 2015-09-22 16:56
Good idea, the mese fragments themselves could be made brighter.

**Comment by RHRhino** [comment] 2015-09-22 18:16
@PilzAdam  @paramat The problem of a texture fake glow is that you cant see it in the dark ...

**Comment by paramat** [comment] 2015-09-22 21:01
Hm indeed. glow cannot be faked. Perhaps best to consider mese fragments as not glowing.
Whateveer, the light source needs removing so i will open a PR for that.

**Comment by PilzAdam** [comment] 2015-09-23 16:24
@RHRhino the brightness of a pixel on your screen is (basically) `light_value * pixel_from_texture`. We never have a pitch black light value  and we just want to be a bit brighter than the surrounding pixels, so increasing the brightness in the texture will (probably) be good enough.

Can someone actually test this and post some comparison screenshots?

**Comment by paramat** [comment] 2015-09-23 17:23
Sure i can try brightening the mese overlay.

**Comment by paramat** [comment] 2015-09-24 01:35
Okay see #682 for new texture.

**Comment by paramat** [comment] 2015-10-03 00:22
#682 merged.

**Closed by paramat** 2015-10-03 00:22 UTC
Labels: bug
