### ISSUE TITLE
Books and bookshelves bloat default mod

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#1217] opened 2016-07-25 15:29 UTC
This includes the on_use, on_player_receive_fields, craft prediction, and a local `lpp`.  Perhaps, after `nyancat` mod, `books` could be next.

Also, this issue, if it's not in duplicate, could be a generalized issue for mod separation from `default`.  Unless @rubenwardy already made one?  I think this is controversial.

**Comment by rubenwardy** [comment] 2016-07-25 15:53
Books are up next - the papyrus and book system is fairly isolated from the rest of default

**Comment by paramat** [comment] 2016-07-25 16:14
Please could you clarify the title and description? It's not clear what you are requesting.

**Comment by everamzah** [comment] 2016-07-25 16:28
I honestly don't know how to title it.  Can you suggest something or edit it as you prefer?

**Comment by paramat** [comment] 2016-07-25 16:29
This is okay, it seems you are asking for books to be moved to a seperate mod.

**Comment by C1ffisme** [comment] 2016-07-25 16:38
What about a 'storage' mod, to hold chests, locked chests and shelves? This would mean most of the formspec definitions would be in one mod, and wouldn't clutter other mods. (The only exception is the furnace formspec.)

**Comment by everamzah** [comment] 2016-07-25 17:00
No, just `books` as `vessels` set the precedent.  It also contains craftitems and a shelf to store them explicitly.  The two mods would compliment each other.

**Comment by rubenwardy** [comment] 2016-07-25 17:06
#1220

**Comment by C1ffisme** [comment] 2016-07-25 17:12
@everamzah I was thinking books themselves could be considered a method of storage, and would also go in the storage mod.

I want to try and avoid turning default into very small mods that only add three or four things. We would end up with too many small mods like:

`apple, trees, stone, grass, clay, furnace, etc.`

**Comment by rubenwardy** [comment] 2016-07-25 17:14
The books mod adds papyrus, paper, bookshelves and writable books. It's one logical concept - it has very little dependencies on other things.

**Comment by paramat** [comment] 2016-07-25 17:15
> I want to try and avoid turning default into very small mods

Don't worry there's plenty of resistance to that, these are just small steps.

**Comment by C1ffisme** [comment] 2016-07-25 17:24
@rubenwardy TNT is a very small mod that only have one logical concept. In fact, TNT is small enough to be put in default.

We could make a mod called `tools` and put tools like picks (and all other `default` tools), hoes, TNT (and gunpowder), and flint n' steel in it, for example. This saves /mod clutter.

**Comment by Wuzzy2** [comment] 2016-07-26 19:16
IMO the default mod is already massively bloated (like a god class in OOP), so I am supporting moving stuff into seperate mods.

Bloat in `default`:
- Player model with complete API (seriously, this feature SCREAMS for its own mod, in fact I even released the `playermodel` mod which does exactly that so this mod can be used without using the other default stuff)
- Defines GUI
- A MASSIVE amount of item registrations + ABMs
- Mapgens

Sadly, the default mod is very established so I fear moving any stuff away will lead to instant breakages among other mods. I mean, if you put bookshelf in books mod, you insta-broke all mods which solely depended on default to get the bookshelf. And no, aliases won't help since the dependency changed from default to books.
While I would love to see an entanglement of the default mod, I fear this is simply not possible without breaking compability quite violently.

I am strongly opposed to merging tnt with default, this suggestion is crazy. Minetest Game is often forked, having a clean architecture is thus helpful for those that want to learn from it. Making default intentionally more bloated makes it harder to rip out specific components of Minetest Game, such as the tnt mod.
Merging tnt with default would mean it would no longer be fun to simply fork the tnt mod alone, now you would have to fork default and rip out all stuff that is not tnt. Not very fun.
And I don't consider the tnt mod to be small, nor to be trivial, it is actually quite complex and having it in its own mod is completely justified IMO.

By the your logic, default should also consume dye, wool, give_initial stuff, sethome, etc., since those mods are small (smaller than tnt by LOC), but this would make default just more bloated.

And “avoiding /mods clutter” is a rather weak argument against the bigger problems caused by merging. That seems more like a minor interface issue to me which could be resolved by improving the /mods command or finding a better way to display installed mods.


I think mods should roughly implement a single feature per mod, or a set of closely-related features. The mod size is not as important as a criteria for me.
I.e. fire implements fire, tnt implements TNT, farming implements farming, etc. Mods Minetest Game mods have a pretty good and clean seperation by mods. It is only the default mod which is some kind of a feature creep. Using distinct mods, on the other hand, makes it easier to rip it out and insert it somewhere else.

**Comment by paramat** [comment] 2016-07-26 19:22
We won't put tnt into default, that's unnecessary and the opposite of what we're trying to do.

**Comment by paramat** [comment] 2016-07-26 19:29
> I mean, if you put bookshelf in books mod, you insta-broke all mods which solely depended on default to get the bookshelf. And no, aliases won't help since the dependency changed from default to books.

Is this an obstacle for #1220 ?

**Comment by t4im** [comment] 2016-07-26 21:43
Are they bloating the default mod or just nodes.lua, crafts.lua, functions.lua etc.?

Things are currently grouped by [logical instead of functional cohesion]( https://en.wikipedia.org/wiki/Cohesion_%28computer_science%29), which is easy to sort-in but becomes hard to maintain over time.

If moving out of default doesn't work for something, maybe it's already helpful moving it into its own file (or if too big, directory), like `furnaces.lua` already does.
That should have a somewhat "unbloating" effect, too.

**Comment by paramat** [comment] 2016-07-26 22:04
Yeah some movement into new files within default is good, and less disruptive.

**Comment by Wuzzy2** [comment] 2016-07-26 22:51
> Is this an obstacle for #1220 ? It's not much of a change to add 'books' to depends.

The issue I have is not that *my* mods will break but that old ones from others. Someone still has to update that `depends.txt`. The question is if we want to accept that this change will break mods.

Obviously, such a change must be announced very loudly if it is done.

**Comment by C1ffisme** [comment] 2016-07-26 23:22
> default should also consume dye, wool, give_initial stuff, sethome, etc.

Default isn't where everything goes, but it seems to be where most "misc." items go. The truth is, the mods just need to be more organized. `dye` could go in `wool`, `give_initial_stuff` seems to be unused, like an old feature just carried over from minimal. `sethome` could go in `default`, or it could go in the mentioned `tools` mod.

The truth is, mods in a subgame are just folders to organize code. Unlike non-subgame mods, you can't disable them without overwriting them. (And in that case, you've got all the control over the subgame that you can have.) Minetest Game isn't organized very well, though. We've got a few mods for tiny aspects of the game, like TNT or Wool or Beds. A better way to organize the game would be to have larger groups that don't clutter any "miscellaneous" groups as much.

For example, what does MTG have a lot of? Well, walking around the game, you see a lot of short grass. 2 different types, in fact. You also see trees. Each tree uses 2 to 3 blocks. We see longer grass and flowers, even in the desert and taiga there are dry shrubs. And if you like to wait, you can also get other plants by planting seeds. So, it makes sense to make a mod about **plants**.

Another thing MTG has a lot of is stone. Dig down and you find lots of it, as well as diamonds, minerals, mese, etc. You can find two more types of stone just by walking around the world, there is sandstone, and desert stone. Two of these stones (Normal stone and Desert stone) have a lot of different variations, like cobble and brick. Lastly, not exactly a stone, more of a mineral, but bricks baked from clay will work as a strong building material like stone. And, you might as well lump dirt and sand in the **stone** mod if clay is in there.

Once you've spent some time crafting, you get a lot of new items, like dye, wool, beds, TNT, glass, etc. These items are **manufactured**. (Bricks could go in here too, it depends on whether or not you want the clay cycle to stay in the same mod or not.)

Of course, it might make sense to put **tools** in a different category from all the blocks and items, depending on how you organize.

The **player** is a complicated thing by him/herself, we might make a separate mod for the player's model and inventory.

One more thing. **Commands**. MTG contains /sethome, /gethome, and might get more in the future. (There might be some I'm missing, I haven't checked too thoroughly.)

Now I've sorted 20 mods into 6. 5 if you put tools in the `manufactured` mod. Or you could put commands in the `player` mod. Not only that, but there is no other, misc., or default mod. All items are in groups that make sense, and it's easy to locate where an item would be. Any further organization can be done through `dofile()` and through turning mods into modpacks.

**Comment by paramat** [comment] 2016-07-26 23:44
> The truth is, mods in a subgame are just folders to organize code.

Nope, they are mods.
Your suggestions here are possibly okay but only theoretically, practically they would cause a huge amount of breakage and headache for everyone, exactly what we're trying to avoid here which is why we're being cautious with this.
Please don't clutter discussions with lengthy and obviously impractical suggestions. it's geting to the point where many here are beginning to ignore anything you write. This is why kilbith became hostile towards you.

**Comment by C1ffisme** [comment] 2016-07-27 02:32
> Nope, they are mods.

Technically, yes. Functionally, they only serve the purpose of organization. In fact, we could stuff all the code in `default` if we had only started that way. It wouldn't be organized, but no real functionality would be lost.

 > Please don't clutter discussions with lengthy and obviously impractical suggestions.

Yeah... Sorry about that... I wish Markdown had spoilers, then I could simply summarize it, leaving my big thought-process for people who have more than enough time.

I'm a terrible conversationalist, but a little too good at thinking and typing.

**Comment by rubenwardy** [comment] 2016-07-27 11:06
Have you ever made a subgame, or even a reasonably sized mod, @C1ffisme?

**Comment by C1ffisme** [comment] 2016-07-27 15:32
@rubenwardy Actually, yes. Here is a screenshot of the metals, woods, and an NPC from my unfinished "realism" game:

![screenshot_20160727_103002](https://cloud.githubusercontent.com/assets/9893266/17181292/3974ed8e-53e5-11e6-84d8-6ba85257e8cd.png)

I haven't bothered releasing it yet, the textures are a bit to ugly, and there are still bugs to work out.

**Closed** 2016-07-31 22:28 UTC
Labels: Request
