### ISSUE TITLE
Cactus seedling

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2255] opened 2018-10-29 00:17 UTC
In the current version of Minetest, the Cactus naturally grows in the shape of
![cactus](https://user-images.githubusercontent.com/33675971/47623428-a1f36080-dace-11e8-8fc5-fd9899a16dc2.png)
Where as grown cactus looks like this:
![screenshot_2018-10-28-16-46-15-1](https://user-images.githubusercontent.com/33675971/47623646-3b237680-dad1-11e8-9a67-e4a1b0e59c4c.png)
So there is no way to re-create the original look
So I think there should be a cactus seedling!
![big cactus](https://user-images.githubusercontent.com/33675971/47623696-cd2b7f00-dad1-11e8-80ce-ba5ab49678af.png)
![screenshot_2018-10-28-16-36-49-1](https://user-images.githubusercontent.com/33675971/47623745-2eebe900-dad2-11e8-9e85-86bd7d9a3d60.png)
### /\ SUBJECT TO CHANGE /\
raw file
![t026](https://user-images.githubusercontent.com/33675971/47623919-b84feb00-dad3-11e8-8b3e-165d5a9777c9.png)

**Comment by jastevenson303** [comment] 2018-10-29 11:29
I believe the issue is the inconsistency.

**Comment by TumeniNodes** [comment] 2018-10-29 18:43
Adding a new table for cactus_seedling would probably be best.

**Comment by paramat** [comment] 2018-10-29 21:41
Good point. If this is done i would add a 'sapling' for 'large cactus' and have it behave like a tree.

Tumeni, the cactus seedlng would just be a plantlike node, we don't need a new schematic.
What do you mean by 'I think that needs to be addressed in the schematic,'?

**Comment by TumeniNodes** [comment] 2018-10-29 22:53
if you want to add a cactus_sapling that's fine but it needs to be added as a schematic does it not? Same as trees do.
That is what I mean, the cactus will need a cactus_from_sapling.mts

I still feel 'sapling' is the wrong word to use for this instance, and should be 'seedling' https://duckduckgo.com/?q=cactus+seedlings&t=lm&iax=images&ia=images
because they are _not_ the same as trees

**Comment by paramat** [comment] 2018-10-29 23:14
> the cactus will need a cactus_from_sapling.mts

Ah sorry, yes. And yeah sapling is the wrong word.

**Comment by Extex101** [comment] 2018-10-30 00:38
OK yeah I looked up what they where called but I couldn't find anything
+Changed

**Comment by TumeniNodes** [comment] 2018-10-30 02:19
is this not what would be needed?

```
-- Large cactus

local C = {name = "default:cactus", prob = 255, param2 = 20}
local R = {name = "default:cactus", prob = 255, param2 = 20, force_place = true}
local E = {name = "default:cactus", prob = 127, param2 = 20}

mts_save("large_cactus", {
	size = {x = 5, y = 7, z = 1},
	data = {
		_, _, R, _, _,
		_, _, C, _, _,
		_, _, C, _, _,
		C, C, C, C, C,
		C, _, C, _, C,
		E, _, C, _, E,
		_, _, C, _, _,
	},
})

-- Large cactus from seedling

local C = {name = "default:cactus", prob = 255, param2 = 20}
local R = {name = "default:cactus", prob = 255, param2 = 20, force_place = true}
local E = {name = "default:cactus", prob = 127, param2 = 20}

mts_save("large_cactus_from_seedling", {
	size = {x = 5, y = 7, z = 1},
	data = {
		_, _, R, _, _,
		_, _, C, _, _,
		_, _, C, _, _,
		C, C, C, C, C,
		C, _, C, _, C,
		E, _, C, _, E,
		_, _, C, _, _,
	},
})

**Comment by paramat** [comment] 2018-10-30 02:43
But those schematics are identical :)

Actually, i've just seen that the cactus schematic only force-places the node in the ground, so we don't need a second schematic.
However in order to replace the seedling, the 2nd node up in the 'trunk' now needs to be force-placed too.

**Comment by paramat** [comment] 2018-10-30 02:51
Anyway, this is a good valid issue, the large cactus has been a little sloppy. I support making it growable using a special seedling.

**Comment by paramat** [comment] 2018-10-30 02:55
A seedling should be expensive in a recipe, so that you only get 1 or 2 from a large cactus, so i would make the recipe:
```
_C_
CCC
_C_
```

**Comment by Extex101** [comment] 2018-10-30 02:55
Okay sounds good

**Comment by TumeniNodes** [comment] 2018-10-30 03:01
> But those schematics are identical :)
> 
> Actually, i've just seen that the cactus schematic only force-places the node in the ground, so we don't need a second schematic.
> However in order to replace the seedling, the 2nd node up in the 'trunk' now needs to be force-placed too.

Oh good, I can scrap what I was poking with then :D

**Comment by Extex101** [comment] 2018-10-30 03:13
I can't atm I won't have access to a computer for a few days

**Comment by TumeniNodes** [comment] 2018-10-30 03:39
That's ok, it can wait :)

**Comment by paramat** [comment] 2018-10-30 06:13
I like the cactus seedling texture in the first post, Extex101 i assume you made it?

**Comment by Extex101** [comment] 2018-10-30 18:58
Yup I made it, although it's based off of the original cactus texture

**Comment by Extex101** [comment] 2018-11-03 02:09
OK so i'm gonna make a PR but i'm not sure how..
Also i don't know how to make it work like a sapling (grow)

**Comment by TumeniNodes** [comment] 2018-11-03 05:53
paramat explained what is needed here https://github.com/minetest/minetest_game/issues/2255#issuecomment-434151816

which means the new schematic needs to look like so

```
-- Large cactus

local C = {name = "default:cactus", prob = 255, param2 = 20}
local R = {name = "default:cactus", prob = 255, param2 = 20, force_place = true}
local E = {name = "default:cactus", prob = 127, param2 = 20}

mts_save("large_cactus", {
	size = {x = 5, y = 7, z = 1},
	data = {
		_, _, R, _, _,
		_, _, R, _, _,
		_, _, C, _, _,
		C, C, C, C, C,
		C, _, C, _, C,
		E, _, C, _, E,
		_, _, C, _, _,
	},
})

-- Large cactus from seedling

local C = {name = "default:cactus", prob = 255, param2 = 20}
local R = {name = "default:cactus", prob = 255, param2 = 20, force_place = true}
local E = {name = "default:cactus", prob = 127, param2 = 20}

mts_save("large_cactus_from_seedling", {
	size = {x = 5, y = 7, z = 1},
	data = {
		_, _, R, _, _,
		_, _, C, _, _,
		_, _, C, _, _,
		C, C, C, C, C,
		C, _, C, _, C,
		E, _, C, _, E,
		_, _, C, _, _,
	},
})

**Comment by paramat** [comment] 2018-11-03 17:03
^ That's wrong, we only need 1 schematic, the already existing one just needs changing to have 2 'R's in the trunk.
Extex101 you're welcome to try a PR if you want, but someone else can do it if you prefer.

**Comment by TumeniNodes** [comment] 2018-11-03 17:29
So, nothing else needs to be done?
A new seedling node is needed, yes/no? You have to have _something_ to plant.
And doesn't it need to have the growing functions added to it? (maybe not, the way it is sounding to me now)

Evidently I am incorrect about my assumptions as to what is needed...

**Comment by Extex101** [comment] 2018-11-03 17:44
What I'm saying is that I don't know how to make a PR  (I'm new to github)

And I'm not sure how to make the seedling actually grow

**Comment by Extex101** [comment] 2018-11-03 17:48
It'd probably be better if you do it because I have no idea what would need to be done

**Comment by paramat** [comment] 2018-11-03 18:17
Ok no problem.

TumeniNodes, yes other stuff is needed, i wrote 'we only need 1 schematic', as opposed to 2 schematics.

**Comment by TumeniNodes** [comment] 2018-11-03 19:42
ok,

**Comment by Extex101** [comment] 2018-11-03 21:37
OK just tell me when the PR is up

**Comment by paramat** [comment] 2018-11-03 22:40
Hopefully you are ok with the usual CC BY-SA 3.0 for the texture?

**Comment by Extex101** [comment] 2018-11-03 23:58
I don't even know what that is

**Comment by Extex101** [comment] 2018-11-04 00:01
Nvm looked it up. 
That's good thanks

**Comment by Extex101** [comment] 2018-11-05 21:17
Hey @paramat I have two questions I'd life to ask:
1) What will be coming first 0.4.18 or will you go straight to 0.5.0?
2) Is there any guessed time that 0.5.0 will come out

**Comment by Extex101** [comment] 2018-11-06 00:33
Well I was just wondering when I'd be seeing the seedling in MTG

**Comment by Ezhh** [comment] 2018-11-06 10:17
> It might also be a good idea to wait for @Ezhh 's opinion first

No issues with the concept as long as cacti can still be grown the current way as well. The current way makes sense for farming, whereas the type with arms would be the more natural/landscape option.

Note: growing time from a sapling should be handled carefully so that it's not quicker to get the same number of cactus nodes using this approach.

**Comment by paramat** [comment] 2018-11-06 18:53
Ezhh i completely agree with your points.
> growing time from a sapling should be handled carefully so that it's not quicker to get the same number of cactus nodes using this approach.
Very good point, will have to think about this issue. The sapling grow time may then have to be so slow as to be not worth doing.

**Comment by Extex101** [comment] 2018-11-06 21:06
So how long does it take for one cacti to grow? 
Time×11 (amount of cactus on large cactus 🌵)

**Comment by paramat** [comment] 2018-11-06 21:11
Yeah, i'll do this anyway and calculate growth to not create an advantage.

**Comment by Extex101** [comment] 2018-11-08 04:06
Cool can't wait!

**Comment by Extex101** [comment] 2018-11-25 20:16
Hey is there a mod that gets a scheme and turns it into one of these 
```
local C = {name = "default:cactus", prob = 255, param2 = 20}
local R = {name = "default:cactus", prob = 255, param2 = 20, force_place = true}
local E = {name = "default:cactus", prob = 127, param2 = 20}

mts_save("large_cactus_from_seedling", {
	size = {x = 5, y = 7, z = 1},
	data = {
		_, _, R, _, _,
		_, _, C, _, _,
		_, _, C, _, _,
		C, C, C, C, C,
		C, _, C, _, C,
		E, _, C, _, E,
		_, _, C, _, _,
	},
})
```
Or does it have to be done by hand?

**Comment by paramat** [comment] 2018-11-26 00:36
Yes a mod called 'schemtools', although it displays all nodes as 'n1'. 'n2', 'n3', etc. so the table doesn't look nice.

**Comment by Extex101** [comment] 2018-11-28 00:08
Made a PR! #2269

**Closed** 2019-01-02 02:18 UTC
Labels: Feature request, Mapgen
