### ISSUE TITLE
Non-ascii user name causes auth.sqlite to not be found

### ISSUE THREAD

**Issue by meetowl** [minetest/minetest_game#2441] opened 2019-08-12 17:01 UTC
Windows 10, Russian language causes problems upon creating world (and probably joining one too).

![Capture](https://user-images.githubusercontent.com/37941587/62882904-97dbdf00-bd3b-11e9-9e4d-b3a36dd079ad.PNG)
I did not censor the "..\Users\\____\\..", that's what the error shows. 

Running "Minetest 5.0.1 - portable, 64-bit (recommended)" 

Steps to recreate: 
1. Create a new user in Windows 10 with a non-ASCII name like "Влад"
2. Try to boot up a new world
3. "... unable to open database file"

**Comment by SmallJoker** [comment] 2019-08-12 17:09
This is a game for Minetest, hence the wrong location for engine bug reports.
Duplicate of https://github.com/minetest/minetest/issues/3588

**Closed by SmallJoker** 2019-08-12 17:09 UTC
