### ISSUE TITLE
Minetest is unavailable for left handers

### ISSUE THREAD

**Issue by MoistTowellettes** [minetest/minetest_game#2384] opened 2019-06-02 16:29 UTC
Minetest should have the ability to switch between left handed and right handed gameplay.

**Comment by paramat** [comment] 2019-06-02 16:31
What do you mean? The control keys can be re-assigned.
Probably an engine issue.

**Comment by DS-Minetest** [comment] 2019-06-02 16:39
I've found one related engine issue: https://github.com/minetest/minetest/issues/1465

In Lubuntu 18.04, changing the keys in minetest isn't even needed if you change activate the left-handed mouse.

**Comment by SmallJoker** [comment] 2019-06-02 16:45
Wrong repository.
Key assignments: can be changed
Wieldhand position: dupe of minetest/minetest#1465

**Closed by SmallJoker** 2019-06-02 16:45 UTC
Labels: Engine change needed

**Comment by MoistTowellettes** [comment] 2019-06-03 02:30
It can't be switched around for touch controls.

**Comment by An0n3m0us** [comment] 2019-06-03 06:46
By touch controls, do you happen to mean on an Android device?

**Comment by MoistTowellettes** [comment] 2019-06-03 16:16
Yes

**Comment by DS-Minetest** [comment] 2019-06-03 17:38
Related: https://github.com/minetest/minetest/issues/8541

@MoistTowellettes This is not an issue of minetest_game, "the button layout is hardcoded"(https://github.com/minetest/minetest/issues/8541#issuecomment-493161907), ergo the subgame can't change it.

**Comment by paramat** [comment] 2019-06-03 21:31
> It can't be switched around for touch controls.

I see. I expect left handers have no difficulty using their left hands for the movement controls. After all, both hands use the controls, so swapping them over makes little difference.
Once you get used to it it will be a non-issue, it's not worth making this possible.
:-1:

**Comment by MoistTowellettes** [comment] 2019-06-04 01:36
I only bring it up because I am left handed can't play the game with a
right handed button layout.

**Comment by Extex101** [comment] 2019-07-01 21:14
I'm all for it, and think it's well worth the effort, just because you're not left-handed doesn't mean it'll be fine without it. 

Some ppl stop playing games entirely if the controls are too hard to use

**Comment by LoneWolfHT** [comment] 2019-07-01 21:26
> > It can't be switched around for touch controls.
> 
> I see. I expect left handers have no difficulty using their left hands for the movement controls. After all, both hands use the controls, so swapping them over makes little difference.
> There are likely very many left handers using the standard controls on Android.
> Once you get used to it it will be a non-issue, it's not worth the effort.
> -1

Try playing a left handed layout on Pixel Gun 3d. I find it extremely hard to do well

**Comment by paramat** [comment] 2019-07-01 21:43
Any left handed person can play the MT Android app as it is if they get used to it.
The problem is probably made worse by other apps allowing the swapping of controls, such that some left handers swap the controls to play (which is actually not essential), and then they get used to that.

Both hands are in similar types of use so there's little relevance to left/right handed issues. This is an issue about what a player is used to.
The most complex controls (movement) are already on the left, but right handers can use this fine.
So i think there is a widespread misunderstanding about controls, generally they do not need to be swapped for left handers. If all apps only had the standard orientation there would be less of a problem.

So ironically the problem is caused by apps providing a choice in the first place, then other apps are forced to provide a choice due to those who are used to a swapped layout =)
Anyway, i'm removing my -1.
