### ISSUE TITLE
F-Droid Version Won't Load

### ISSUE THREAD

**Issue by rinamasahiro** [minetest/minetest_game#2876] opened 2021-05-19 19:28 UTC
Is the bug reproducible?
- yes

How can you reproduce the bug?
- install minetest from F-Droid and open it

What is your operating system?
- Android 10

What is your version of Minetest?
- 5.2.0.26 (most recent F-Droid version)

What game do you use? (e.g. minetest_game, MiniTest, dwarves)
- unknown

On first install, the loading screen showed filenames, got to the shaders folder and crashed the app at the same file every time. After uninstalling and reinstalling, the app doesn't even show the filenames being loaded and triggers the "App keeps stopping" dialog. Since the Google Play Store version 5.4.0 just works, it's probably already a solved issue anyway; F-Droid just never received the update.

**Comment by sfan5** [comment] 2021-05-19 19:31
Wrong repo and also duplicate of https://github.com/minetest/minetest/issues/10749.
The F-Droid version currently cannot be updated due to some issues.

**Closed by sfan5** 2021-05-19 19:31 UTC

**Comment by rinamasahiro** [comment] 2021-05-20 14:06
> Wrong repo and also duplicate of [minetest/minetest#10749](https://github.com/minetest/minetest/issues/10749).
> The F-Droid version currently cannot be updated due to some issues.

Thank you. I asked in the forums and was directed to this repo, performed a search for "f-droid" and found nothing, so I appreciate you linking me to what's going on.
