### ISSUE TITLE
Default mod is bloated

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1771] opened 2017-06-09 14:28 UTC
This is more a criticism of Minetest Game's development than anything else. Take from it what you want.

The default mod is **way** too bloated. It reminds me a lot of the anti-pattern “God Class”(https://lostechies.com/chrismissal/2009/05/28/anti-patterns-and-worst-practices-monster-objects/).

`default` has the following responsibilities:

* Registers **a ton** of nodes and items **with no clear theme or scope**, including, but not limited to:
    * Trees and saplings (+API)
    * Fences (+API)
    * Ladders
    * Signs
    * Keys
    * Chests
    * Furnaces
    * Basic plants
    * Torches
    * Almost all tools
* Almost the entire mapgen code (+mapgen aliases)
* Player model (+API)
* Default sounds

And the bloat doesn't seem to ever stop. It is still common that new features are added into `default`, making the bloat even worse. The scope of `default` is undefined either, 

This is bad because whenever you need to depend on anything from Minetest Game which happens to be in `default`, you have to depend on *all* the baggage the `default` carries along. Also, `default` provides an API for three (!) relatively unrelated things. This is bad software engineering.

More evidence of bloat is given if you just look at the line counts:

```
  2441 nodes.lua
  1826 mapgen.lua
  1229 crafting.lua
   574 functions.lua
   535 trees.lua
   419 tools.lua
   334 craftitems.lua
   330 furnace.lua
   154 player.lua
   146 torch.lua
    77 aliases.lua
    74 item_entity.lua
    52 init.lua
    25 legacy.lua

  8216 total
```

3 files alone have a line count greater than 1000. `nodes.lua` is extremely heavyweight, especially since it cobbles togehter many nodes which are not really related to each other.

Note I have no interest in working for Minetest Game. This post is more an opinion piece. I think my criticism is still valid, however. And it is a complaint from Minetest Game modders which comes up quite often.

**Comment by C1ffisme** [comment] 2017-06-09 15:50
Related : #726

**Comment by rubenwardy** [comment] 2017-06-09 18:52
👏

**Comment by sfan5** [comment] 2017-06-09 19:13
@rubenwardy 
In contrast to other bug reports that actually affect end users in some visible way, this should definitely be low priority.

**Comment by paramat** [comment] 2017-06-10 18:47
Seems a duplicate.

**Comment by paramat** [comment] 2017-06-10 18:50
We have actually already stated that from now on new stuff will be in separate mods if possible, rubenwardy's presence helps with that.

**Comment by C1ffisme** [comment] 2017-06-10 20:33
> We have actually already stated that from now on new stuff will be in separate mods if possible, rubenwardy's presence helps with that and there is no resistance to that.

That's not really any better, that's just the difference between shoving everything into one box, and shoving each individual item into it's own box, and then throwing them onto the shelf without any organization. Plus, the /mod spam would be unbearable.

Instead, it would be a good idea to organize features into categories, such as `mapgen`, `commands`, `underground`, `flora`, `player`, etc.

**Comment by dsohler** [comment] 2017-06-10 22:30
This is totally NOT a “possible close”. This is a long-term enhancement and should be dealt with properly, because in it s current state it’s the worst we can get.

> Plus, the /mod spam would be unbearable.

Then it has to be reworked to hide the stuff that currently is in the `default` mess.

**Comment by paramat** [comment] 2017-06-11 00:48
Ok, since there is no other issue on this open, removed label.

> That's not really any better, that's just the difference between shoving everything into one box, and shoving each individual item into it's own box,

What i mean is, this discussion has been had before and we agree that future changes to MTG will be done keeping these requests in mind.

> in it s current state it’s the worst we can get.

Yes it's bad, but there was discussion before in 726 about re-organising default and it was decided it is not worth doing due to the disruption, better to start a new fresh subgame.

**Comment by C1ffisme** [comment] 2017-06-11 04:35
> Then it has to be reworked to hide the stuff that currently is in the `default` mess.

This should probably be a parameter you type after the command, e.g: `/mod no_subgame`.

**Comment by dsohler** [comment] 2017-06-11 07:26
> This should probably be a parameter you type after the command, e.g: `/mod no_subgame`.

This should be as simple as possible for everyday use. So `/mods` for listing all the mods except the subgame mods and `/mods subgame` to list the subgame mods only.

**Comment by ThomasMonroe314** [comment] 2017-06-17 22:20
I agree in part with Wuzzy

**Comment by tacotexmex** [comment] 2017-06-27 12:50
Even if this has been brought up before, the fact that it is again pointed out is telling. I don't understand the

> it is not worth doing due to the disruption

argument. The point is to move out stuff from default, not to break compatibility, yes? It would be the opposite of disruption. Besides, burli has [already succeeded](https://github.com/MarkuBu/minetest_modbase/tree/master/mods) in breaking up `default` into smaller parts (though this was made in order to also slim it down to a mod base, but that's not the point).

> Plus, the /mod spam would be unbearable.

This is such a by-the-way argument it's not even worth discussing. It's as if one would be against breaking up default because "more directories to having to look at". ;D

**Comment by dsohler** [comment] 2017-06-27 17:34
Simply extracting every aspect from `default` into an own mod and creating a new `default` mod depending on all the new individual aspect mods would not break anything that depends on default but would make it possible do depend on individual aspects of the current `default` mod.

**Comment by rubenwardy** [comment] 2017-06-27 20:06
That would only work if you didn't rename any items, which isn't ideal - but is better than a bloated default mod

**Comment by paramat** [comment] 2017-06-28 04:11
No that's not better, names should follow convention.
However, seems better and easier to start a fresh new mod base game.

**Comment by rubenwardy** [comment] 2017-06-28 07:07
It's better to have a bunch of default_* games with items called default:* than a fucked dependency system.

And a new mod base completely ruins the point - the point is to make cross subgame support easier by having granular dependencies.

**Comment by paramat** [comment] 2017-06-28 07:19
> a bunch of default_* games

That's a good solution to the naming issue.

**Comment by dsohler** [comment] 2017-06-28 11:48
@rubenwardy The new default mod would not only depend on the other mods but also adds aliases for all currently registered things so nothing will break.

New things won't get aliased and with two more releases aliases will be removed (wasn't it that MT now only will be compatible for the the current and the wo previous releases?).

**Comment by paramat** [comment] 2017-06-28 13:06
I would rather avoid aliases, especially for all nodes. They only very slowly change nodenames in a world, i believe the nodename is only changed if a mapblock gets resaved, so aliases may have to remain for years to support old worlds.

**Comment by rubenwardy** [comment] 2017-06-28 13:10
Aliases don't work very well if other mods use them in logic, as mods don't tend to check aliases.

Eg:

```lua
if stack:get_name() == "default:book" then
```

**Comment by rubenwardy** [comment] 2017-06-28 14:21
> I would rather avoid aliases, especially for all nodes. They only very slowly change nodenames in a world, i believe the nodename is only changed if a mapblock gets resaved, so aliases may have to remain for years to support old worlds.

I don't think this is a very good argument against them, aliases don't incur any lag or take up any memory. The code is also minimal.

**Comment by C1ffisme** [comment] 2017-06-28 16:08
Recently an issue was created about [redoing MTG for 0.5.0](https://github.com/minetest/minetest_game/issues/1798). As silly as it may be to completely redo MTG from scratch, it might not be a bad idea to copy-paste from the current MTG and slowly recreate a better MTG to replace the original.

It would break compatibility with older worlds, but at least we would have a solution to the problem of the default mod being bloated, and we can reorganize other bits of code that don't deserve an entire mod to their namesake. (I.E. `give_initial_stuff`)

**Comment by rubenwardy** [comment] 2017-06-28 16:36
That's a very bad idea. For one, the main reason to debloat default is to make dependencies 
easier. You don't need to debloat it to make MTG dev easier, you can just move then to different files.

Give_initial_stufff 100% deserves its own mod as it's a standalone feature. Good mods are cohesive and have low coupling - that is, the mods introduce a single concept that's as self contained as possible. For example, books should be a separate mod as it's a self contained craft chain and festure. The dependencies go one way - books would depend on default for wood, but default would work perfectly without books.

**Comment by C1ffisme** [comment] 2017-06-28 17:09
> That's a very bad idea. For one, the main reason to debloat default is to make dependencies
easier. Breaking every mod in this existence doesn't really help.

If we split default, mods already have to rewrite code. I can't say whether or not that will be the case if there is a new MTG for 0.5.0. (We're breaking support for mods anyway, though, so a new MTG just helps in the process, and we can focus on the other objective: organizing code to make MTG easier to develop.)

> Give_initial_stufff 100% deserves its own mod as it's a standalone feature. Good mods are cohesive and have low coupling - that is, the mods introduce a single concept that's as self contained as possible.

In the case of a subgame mod, I don't think this should be the case. Sure, it's easy to find, but you can't get away with this for every single piece of code.

Mods should be organized into categories of related stuff that you can look at and know what it contains. (e.g. a mod named `surface` should contain dirt, trees, and respective mapgen code. A mod named `stone` should contain stones, ores, and oregen.) We should not have 40-50 mods that add seemingly random content. (E.G. `mapgen`,`trees`,`stone`,`ores`,`dirt`,`plants`,)

Does anyone use `give_initial_stuff` anymore? I feel like I have only heard of it whenever someone mentions removing it.

**Comment by dsohler** [comment] 2017-06-28 17:25
> Aliases don't work very well if other mods use them in logic, as mods don't tend to check aliases.

Sorry, but that’s entirely their fault.

**Comment by NathanSalapat** [comment] 2017-06-28 22:31
The only times I've used give_initial_stuff is in a custom subgame.

**Comment by dsohler** [comment] 2017-06-29 07:06
> I can't say whether or not that will be the case if there is a new MTG for 0.5.0.

There won't be, and there never will be with how it currently is implemented. And all other subgames depend on default in one or another way.

Without completely breaking backwards compatibility by rigorously removing the current `default` and rewriting a default set of individual mods nothing will change on this situation.

**Comment by paramat** [comment] 2017-06-29 09:59
> aliases don't incur any lag or take up any memory. The code is also minimal.

Yes. However, they are messy in the way they have to be kept for many years and the way worlds then contain a mix of replaced or not-replaced nodenames that changes very slowly over time. Having a few is bearable but the idea of everything being an alias is a nightmare.
They cause other issues too as described, likely to outweigh any advantage.

**Comment by Wuzzy2** [comment] 2017-06-29 11:17
> > Aliases don't work very well if other mods use them in logic, as mods don't tend to check aliases.

> Sorry, but that’s entirely their fault.

As far I know, it is currently impossible to check whether an itemstring is aliased. :-(

**Comment by rubenwardy** [comment] 2017-06-29 12:28
minetest.registered_aliases

**Comment by Wuzzy2** [comment] 2017-06-29 13:24
This is not mentioned in `lua_api.txt`, therefore it does not exist. :wink:

**Comment by DS-Minetest** [comment] 2017-06-30 16:24
Maybe we need something like `minetest.is_same_itemstring`.

**Comment by paramat** [comment] 2017-08-13 10:17
So as i wrote above, is there any point keeping this open? Rubenwardy has done all he can to split stuff off, and is keen to do so whenever possible. We seem to have done all we can, and we state we will keep new things to new mods in future. So the issue is rather pointless now.
@rubenwardy shall we close?

**Comment by paramat** [comment] 2017-08-30 02:52
Obvious close.

**Closed by paramat** 2017-08-30 02:52 UTC
Labels: Maintenance, Possible close, Request / Suggestion

**Comment by AntumDeluge** [comment] 2017-09-07 23:14
I know this is closed, but I want to offer what I think is a solution for the "aliases" issue. If MTG contains a mod like [cleaner](https://github.com/AntumMT/mod-cleaner) (a fork of PilzAdam's *clean* mod), then server owners could easy manage aliasing old nodes without having to modify any mod code. *cleaner* parses a file named *clean_nodes.txt* in the word path to override & alias nodes. I think this would be a good solution because then the MTG game devs don't have to worry about keeping any aliases in the code. That would be handled by server owners on an individual basis.
