### ISSUE TITLE
Leaves decay

### ISSUE THREAD

**Issue by 00c** [minetest/minetest_game#2070] opened 2018-03-05 19:00 UTC
Server 0.4.16 last minetest_game.
Default tree leaves do not  decay.
On other trees leave decay works fine. Beside default trees.

**Comment by Ezhh** [comment] 2018-03-05 20:01
On a quick test in dev version, this works as expected for me.

**Comment by 00c** [comment] 2018-03-05 20:04
I run 0.4.16 stable. not dev version. 
Its an engine bug?

**Comment by Ezhh** [comment] 2018-03-05 20:10
I saw, but if the error isn't present in the current version (the dev version), then if there was an issue, it's already been fixed.

I've also just tested in stable and can't reproduce it there either. Are you sure you haven't changed anything that might affect this?

**Comment by 00c** [comment] 2018-03-05 20:35
After doing some test.
Disabling snow mod fixed issue.

**Comment by Ezhh** [comment] 2018-03-05 20:38
Thanks for confirming.

**Comment by HybridDog** [comment] 2018-03-06 09:16
I think it's a bug in minetest_game.
https://github.com/minetest/minetest_game/blob/d4a007c0511301b6c712a5880ccbdae4475a4c48/mods/default/functions.lua#L389-L393
Registering a leafdecay overrides the after_destruct while ignoring the current after_destruct (if there is one). So [when registering a leafdecay for a tree which has the default trunk](https://github.com/Splizard/minetest-mod-snow/commit/0dcf9b5f0e2a06e9d01c3ba52285d82a6bf341ac#diff-d651edc9077eaf572bb53693e71df507R270), the previous leafdecay's after_destruct is overridden, which disables the decaying.

**Comment by HybridDog** [comment] 2018-03-06 13:06
@MarkBu @sofar @paramat 
https://github.com/minetest/minetest_game/commit/60e5b299af564f250af8304b5146f79693c314ff

**Comment by HybridDog** [comment] 2018-03-06 13:07
@MarkuBu @sofar @paramat 
https://github.com/minetest/minetest_game/commit/60e5b299af564f250af8304b5146f79693c314ff

**Comment by Fixer-007** [comment] 2018-03-06 14:24
I want to remind everyone that tree leave decay is not working properly in some edge cases :(

**Comment by paramat** [comment] 2018-03-06 18:39
Duplicate of #1879 
The snow mod ideally should use mod nodes for trunks, however any 'fix' is still welcome.

**Closed by paramat** 2018-03-06 18:39 UTC
Labels: Bug, Duplicate
