### ISSUE TITLE
Uncatchable butterflies

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest_game#2270] opened 2018-11-28 03:42 UTC
##### Steps to reproduce

Get a butterfly place on anything that is buildable_to
It places two butterflies?
![screenshot_20181127_194213](https://user-images.githubusercontent.com/33675971/49127546-908fa680-f27c-11e8-91e3-cb90a7746baa.png)
Top one can be caught but the bottom one is uncatchable

**Comment by Ezhh** [comment] 2018-11-28 15:54
@paramat Using current MT and current MTG I still can't duplicate this, even following your exact instructions. The butterfly simply doesn't replace the buildable_to node for me.

Are you able to dig the butterfly that isn't a butterfly (instead of using the net)? Which selection box do you see? It sounds like you're seeing butterflies when there aren't any there.

**Comment by jastevenson303** [comment] 2018-11-29 09:04
This reminds me of the slab duplication bug that was recently removed in favor of a craft recipe (lol).

I think it also depends on hosting a server/going singleplayer (I know, that's a controversial stance, because the consensus has seemed to be: "but they're the same.)

Basically, the client puts it there, but the server doesn't know anything about it?  It's definitely obscure and unfortunate, but I haven't personally seen it (yet).

**Comment by Ezhh** [comment] 2018-11-29 09:48
Well, there is definitely an issue. It's like on the client side the normal placement happens AND the on_place happens, but the server knows better.

Either way, I think the problem isn't in the mod, though I'll be happy to adjust if someone has any suggestions.

**Comment by jastevenson303** [comment] 2018-11-29 12:57
I dunno, I just tried it and it was pretty easy to reproduce with a firefly replacing a flower.  I agree it's in engine, but I figure it may be difficult to address.  I mean, they removed the slab doubling feature for a craft recipe because of it.  It was thought fixed, after one PR was merged, but it didn't really stick I guess.

**Comment by jastevenson303** [comment] 2018-11-29 13:00
It boggles my mind, because here fireflies mod checks explicitly for air: https://github.com/minetest/minetest_game/blob/master/mods/fireflies/init.lua#L34

But in game, if you right-click flowers with a firefly, it thinks the flowers are air?  Because in the client, as mentioned, it appears to replace them.  But when you leave the server and rejoin, the flowers are back and everything looks fine.  (Just like what used to happen with slab-on-slab to make one node.)

**Comment by Ezhh** [comment] 2018-11-29 13:35
I don't think I'm familiar with the slab issue you're referring to. 

The two slabs = a full need feature was removed because we didn't like it, not due to a bug.

**Comment by Ezhh** [comment] 2018-11-29 14:16
Confirmed client side only. Starting a server and after (30+ butterflies later)  I get a glitched one, joining with a second client shows me the second client sees a butterfly above the plant instead of two butterflies.

**Comment by jastevenson303** [comment] 2018-11-29 16:42
its an older issue from some years ago.  recurring.

**Comment by jastevenson303** [comment] 2019-01-24 13:37
It's also an engine bug.  It's not that the you cannot catch the butterfly, it's that the butterfly is not really there.

**Comment by HybridDog** [comment] 2019-07-30 09:48
There the clients adds the prediction: https://github.com/minetest/minetest/blob/2dd645134eaab7611d167e2cb8469242e642c7ef/src/client/game.cpp#L3325
There the server informs the client about the prediction failure: https://github.com/minetest/minetest/blob/2dd645134eaab7611d167e2cb8469242e642c7ef/src/network/serverpackethandler.cpp#L1340

**Comment by Wuzzy2** [comment] 2022-05-24 12:24
I can't reproduce this in 5.5.1. The buildable_to node is never replaced. Both in Creative and non-Creative.

Maybe this was accidentally fixed already?

**Comment by appgurueu** [comment] 2022-05-24 12:52
> Maybe this was accidentally fixed already?

Perhaps this was fixed in the engine - who knows? It can't be fixed in MTG anyways.

**Closed by appgurueu** 2022-05-24 12:52 UTC
Labels: Bug, Won't fix, Engine change needed, Can't fix, Obscure
