### ISSUE TITLE
Place stairs upside down depending on click position

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest_game#1572] opened 2017-02-15 19:20 UTC
To place stairs upside down you need to place a node above or a screwdriver. It would make things easier if stairs are rotated if you click in the top half of the node and not rotated if you click in the lower half.

I don't know if it is possible to get the click position on a node

**Comment by paramat** [comment] 2017-02-16 12:09
Getting the click position might be quite complex to do, needing a new API.

**Comment by MarkuBu** [comment] 2017-02-16 12:17
I know I saw this in a mod, but I don't remember

**Comment by sofar** [comment] 2017-02-16 22:27
If you know the look yaw/pitch of the player, and you know their position, you can mathematically calculate where on the surface the cursor should be. This is what the painter mod does.

https://github.com/xyzz/painting/blob/master/init.lua#L91

However, wrt slab/stair placing, people have complained about the handling before and I fear that any change is just going to get more people complaining again. The code is already overly complex as is.

**Comment by paramat** [comment] 2017-02-16 22:48
Yeah i would prefer simpler behaviour, impossible to satisfy most builders as building preferences vary so much.

**Comment by MarkuBu** [comment] 2017-02-16 23:19
Simpler behaviour (for the user) normally means more code

It is not simple to rotate each slab or stair with the screwdriver just because of the code is simple.

And to be honest: was there a change in history that has satisfied EVERYBODY?

The behaviour should be logical. And it is not logical that a slab is placed vertical if I attach it to a horizontal slab, for example.

@sofar, thanks for the link. Maybe I try a PR some day if no one else will

**Comment by paramat** [comment] 2017-02-17 00:27
Yes i mean simple codewise.

**Comment by DS-Minetest** [comment] 2017-02-17 19:30
Btw, not only the painting mod does this. Some other examples:
@HybridDog made a [fork of digipad](https://github.com/HybridDog/digipad) where you can punch at the digipad to use it, his [technic_extras mod](https://github.com/HybridDog/technic_extras) changes the music player so that you can punch the numbers to change  and stop the music and he made [a fork of travelnet](https://github.com/HybridDog/travelnet/tree/punch_change) where you can use the elevator by punching it.
There might be more but I don't remember everything.

**Comment by HybridDog** [comment] 2017-02-17 20:57
> Getting the click position might be quite complex to do

It's very easy (it's taught at grammar school). The camera offset is 1.625 m above player:getpos() position + the bobbing offset. The offset caused by bobbing is not known serverside, but it's small, so it can be omitted.
https://github.com/HybridDog/technic_extras/blob/master/init.lua#L64

**Comment by paramat** [comment] 2017-02-17 21:19
Yes, simple maths but it's a lot of code for something probably unnecessary. SImple code helps devs' heads.

**Comment by sofar** [comment] 2017-02-21 08:07
If someone writes a PR, I'll review and help improve it (as I always do).

**Comment by MarkuBu** [comment] 2017-02-21 08:58
I don't think it is unnecessary. I think, a game should be K.I.S.S for the players, not for the devs

Will try to make a PR. I'll start with #1568

**Comment by paramat** [comment] 2017-02-21 18:45
Actually since we have limited dev time it's important that code doesn't get unnecessarily complex, i will oppose any PR that detects click position on a node, simpler slab behaviour will be just as usable.

**Comment by MarkuBu** [comment] 2017-02-21 19:11
Well, then I'll fork the stairs mod

**Comment by C1ffisme** [comment] 2017-02-21 19:11
Rather than simply adding code into the stairs mod to detect where on a node you have clicked, wouldn't it make sense to put this functionality into builtin?

**Comment by HybridDog** [comment] 2017-02-21 21:02
> Well, then I'll fork the stairs mod

You can't fork the stairs mod because it's not an repository.
But you can run ```$ git subtree push -P mods/stairs/ https://github.com/<you>/<stairsrepo> master``` to get one with history, e.g.:
https://github.com/HybridDog/stairs (from my minetest_game fork)

**Comment by HybridDog** [comment] 2017-02-23 13:40
C1ffisme, that function detects where on the node you have clicked:
https://gist.github.com/HybridDog/76eee7890a439e6984aa4ca45c1e04e9

**Comment by MarkuBu** [comment] 2017-02-23 17:21
@HybridDog cool, thx. What does pt stand for? Position of the pointed node?

**Comment by DS-Minetest** [comment] 2017-02-23 17:23
I think, it means pointed_thing.

**Comment by MarkuBu** [comment] 2017-02-23 19:03
perfect, thanks. It works

**Comment by MarkuBu** [comment] 2017-02-23 20:35
that was easy

https://youtu.be/KQRGy8Hkzhw

**Comment by MarkuBu** [comment] 2017-02-23 22:05
Is someone willing to add HybridDog's code to builtin? Might be useful for other mods

slabs are now a bit different. Also auto rotation works with different slab types

https://youtu.be/Qkb3acMjCig

**Comment by paramat** [comment] 2017-02-23 23:30
Sorry for my comment, this looks good on the video, i don't oppose.

**Comment by MarkuBu** [comment] 2017-02-23 23:54
If someone can add HybridDog's code to builtin I can remove the code from stairs mod. I'll make a PR tomorrow

**Comment by paramat** [comment] 2017-02-24 00:37
Perhaps adding that code to builtin should be a separate PR?

**Comment by MarkuBu** [comment] 2017-02-24 06:28
I think about more rotations depending on click position. Vertical rotation if clicked on the left or right side of the surface and default rotation when click at the center. But I'm afraid that this is more complicated and I want to try first if it feels natural

**Comment by paramat** [comment] 2017-02-24 06:39
> Vertical rotation if clicked on the left or right side of the surface and default rotation when click at the center

Sorry i'm not keen on that.

**Comment by MarkuBu** [comment] 2017-02-24 09:10
I'll make a mod for this. It can be used in older MTG versions too

**Comment by hkzorman** [comment] 2017-02-24 13:27
This is really good :+1:

**Comment by paramat** [comment] 2017-04-09 13:26
PR #1581

**Comment by paramat** [comment] 2017-04-11 07:41
#1697 merged.

**Closed by paramat** 2017-04-11 07:41 UTC
Labels: Request / Suggestion
