### ISSUE TITLE
Permafrost with moss and permafrost with stones are non-renewable

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest_game#2297] opened 2019-02-04 03:34 UTC
I noticed neither permafrost with stones nor permafrost with moss are renewable resources, i.e. they are not collectible and do not spread. This seems like a somewhat major gameplay issue to me, being someone who likes to use different nodes in builds. Moss especially could be a rather interesting block to build with.

This ~~could~~ will also lead to a lot of accidental griefing and destruction of permafrost biomes. For example, I might start building a house, remove some permafrost, and then decide that I want to build somewhere else. Now, a large area of permafrost has been compromised permanently.

This was mentioned briefly before, but I feel it needs more consideration.

**Comment by paramat** [comment] 2019-02-04 14:16
Permafrost with moss can't spread because it is meant to be patchy and would cover everything, maybe the moss can be dropped as an item?
Permafrost with stones could perhaps drop stones as an item?
These items don't have a use yet. Moss could be crafted to green dye?
Good issue.

**Comment by paramat** [comment] 2019-02-04 22:00
I want to sort this out to a degree before 5.0.0 so i suggest temporarily just making these nodes drop themselves, then worlds won't lose stones and moss.

**Comment by Ezhh** [comment] 2019-02-04 22:46
@paramat No objections from me. I think it's important for people to have the options to build with, one way or another.

**Comment by Linuxdirk** [comment] 2019-02-06 12:03
> Permafrost with moss can't spread because it is meant to be patchy and would cover everything, maybe the moss can be dropped as an item?

What about some sort of "age" or "generation" as metadata for each of the nodes? When the node spreads the "age" is stored as metadata and raised with each spread, so there is a value to use for stop spreading.

**Comment by paramat** [comment] 2019-02-06 18:44
I don't think it should spread at all. Grass spreads on dirt because that is desirable and dirt is not a desirable or valid surface node, 'permafrost with stones' is. I can imagine someone using 'permafrost with stones' and not wanting nearby 'permafrost with moss' to spread onto it. Also of course metadata adds data to a map.

**Comment by random-geek** [comment] 2019-02-06 20:18
Moss would not have to spread to permafrost with stones, only to bare permafrost. Permafrost with stones could spread too, which would prevent moss from dominating, although it is less realistic as stones are not living and cannot "spread" per se.

**Comment by benrob0329** [comment] 2019-02-06 20:22
Moss is most definitely a desirable ground cover, imagine a ruins build with mossy cobble, stone brick, and a mixture of moss and grass ground.

**Comment by paramat** [comment] 2019-02-07 19:07
> Moss would not have to spread to permafrost with stones, only to bare permafrost

Aha that's possibly a good idea. Spread can then be unlimited, i would prefer to avoid metadata. This might be addable to the 'spreading dirt type' code.

**Comment by TumeniNodes** [comment] 2020-03-18 06:01
I've had an idea for adding a gathering feature/function for the stones, which does not involve digging the node and dropping stones...
One should be able to gather them without digging/destroying the entire node, and disrupting the area, or altering the landscape.
Working on it a bit at a time as I have time...

**Comment by paramat** [comment] 2020-03-19 00:58
Digging the node is fine as long as the player then receives a node to place back in the hole, which presumably would be bare permafrost. So 'permafrost with stones' would drop a stones item and 'permafrost' (i assume a node can drop multiple items?). This would also be by far the simplest implementation (very important) and consistent with many other nodes.
But yes i agree that the node should not be destroyed, leaving a hole in the terrain.

The stones should be removed, leaving bare permafrost, otherwise the node would become an infinite resource. So altering the landscape in that way is fine, if that is what you meant.
As i mentioned earlier, i do not agree that stones should reproduce or spread, they are not living, so are like any other non-living node and a finite resource.

**Comment by TumeniNodes** [comment] 2020-03-19 03:26
> Digging the node is fine as long as the player then receives a node to place back in the hole, which presumably would be bare permafrost. So 'permafrost with stones' would drop a stones item and 'permafrost' (i assume a node can drop multiple items?). This would also be by far the simplest implementation (very important) and consistent with many other nodes.
> But yes i agree that the node should not be destroyed, leaving a hole in the terrain.
> 
> The stones should be removed, leaving bare permafrost, otherwise the node would become an infinite resource. So altering the landscape in that way is fine, if that is what you meant.
> As i mentioned earlier, i do not agree that stones should reproduce or spread, they are not living, so are like any other non-living node and a finite resource.

Yes, this is precisely what I meant.
Basically, the player will be able to punch the node which will either drop a stone with each punch up to 5 (slow) punches, or directly into inventory.
I am unsure whether I want to try using multiple top stone textures to animate as each of the 5 are collected (or whichever amount) or once they are all collected from that node, a completely stone free permafrost texture swaps in. (opinions on this appreciated)
Whereas continuous punching will destroy the entire node as usual.
Something like that, I am still hashing out the details.

**Comment by TumeniNodes** [comment] 2020-03-19 03:33
As a side note, and potential idea for future ref...
these stones _could_ then be throwable (in pvp play) or if mobs are used to throw at an opponent or to kill a small animal for food, etc.

They could also be incorporated into a system where combined with sticks and vines to craft a first level axe, which can also double as a weapon, or even to dig up soil to plant...
In other words... a new way to do first level, primitive stone tools?
(this is just an idea Ive had for a long time)
punching a stone node with a stone in hand could sharpen the stone to use for the axe... But I am jumping well ahead, but doing so just to give an idea of where I may intend to go with this current step

**Comment by paramat** [comment] 2020-03-19 21:37
Hm, after thinking more on this, making tundra surface nodes a resource of stones items makes no sense.
If a stones item is desired, the obvious source is from default:stone (via default:cobble), which is present in vast quanties thoughout the depth of the world. Tundra surface nodes are just 1 biome on the surface.
Cobble is the obvious source as it is already broken stones.
Another benefit is that underground nodes then become the source, meaning the tundra surface will not become bare as players collect stones resources.

So, i disapprove of 'permafrost with stones' being the source of a stones item, it should come from cobble.
I disapprove of 'permafrost with stones' being renewable or spreading as it is non-organic.
:-1: for the above.
'permafrost with stones' now drops itself which seems fine, i cannot see anything that needs doing for that node.

Making 'permafrost with moss' spread, and therefore be renewable, makes some sense, although i think it is low priority because digging 'permafrost with moss' now does not destroy the moss. Surface spreading is mostly done because digging a 'dirt with x' node destroys the surface layer.
Whatever is done it needs to avoid endless spreading as moss needs to be patchy.

Keep in mind that most of the initial issue is now resolved due to #2301 , the nodes are now collectable and are not destroyed by digging and re-placing.

**Comment by TumeniNodes** [comment] 2020-03-20 01:47
> Whatever is done it needs to avoid endless spreading as moss needs to be patchy.

Suggest maybe do the same as was done for dry dirt for non spreading?

I'll think on the cobble suggestion, it can probably be worked to make sense for players.

**Comment by paramat** [comment] 2020-07-27 01:35
Closing due to #2710 and https://github.com/minetest/minetest_game/issues/2297#issuecomment-601428966

**Closed by paramat** 2020-07-27 01:35 UTC
Labels: Low priority, Request / Suggestion, Supported by core dev
