### ISSUE TITLE
furnaces dont work after rejoin

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest_game#978] opened 2016-03-26 11:19 UTC
Hi, players reported me that their furnaces dont want to work since they was offline some time.
The coal/cactus/... have to insert again.
Im not sure how long you have to be offline, im currently try to reproduce.

Edit: im not sure if it has something todo with it but the players who reported it, using the `pipeworks` mod to refill the furnaces

**Comment by paramat** [comment] 2016-03-27 07:30
@sofar

**Comment by tenplus1** [comment] 2016-03-27 09:58
Yeah furnaces had a problem with Hoppers mod as well, they would stall and no longer work, so had to revert to using old-style abm furnaces for hoppers.

**Comment by kilbith** [comment] 2016-03-27 11:26
It's normal, the timer only starts when something is [**put**](https://github.com/minetest/minetest_game/blob/master/mods/default/furnace.lua#L257) in the furnace. If something has been moved inside when the furnace worked with an ABM, you have to take it and put it again to cook.

**Comment by PilzAdam** [comment] 2016-03-27 14:44
@kilbith `move` is moving items in the same inventory, so a hopper `put`s items in the furnace inventory, doesn't it?

Btw, I'd consider this a bug anyway, since moving an item from the output to the input could possibly start the furnace again.

**Comment by kilbith** [comment] 2016-03-27 14:49
`move` is moving items between non-player inventory lists. `put` is moving items from your inventory to some list.

> since moving an item from the output to the input could possibly start the furnace again

That's not possible currently. As I said, only `put` triggers the timer, not `move`.

**Comment by sofar** [comment] 2016-03-27 17:57
I'll look into the behavior later today. I have not tested with pipeworks, it may require a pipeworks change if that's the case.

**Comment by sofar** [comment] 2016-03-27 23:04
Pipeworks directly modifies the inventory, but doesn't activate the furnace. I checked and none of the methods in the furnace get called when items are injected in the inventory, so this would require to be patched in pipeworks  it just has to start the timer if there is none running, which should be fairly simple.

**Comment by sofar** [comment] 2016-03-27 23:23
I can't even have pipeworks insert items into ```fuel```, it just drops them on the ground. :(

**Comment by sofar** [comment] 2016-03-27 23:32
https://github.com/VanessaE/pipeworks/pull/134

**Comment by sofar** [comment] 2016-03-27 23:32
The same fix is likely what hoppers needs.

**Comment by sofar** [comment] 2016-03-27 23:59
Pushed a fix for the ```move``` part of the problem shown by pilzadam. #980.

**Comment by sofar** [comment] 2016-03-28 00:12
https://github.com/jordan4ibanez/Hoppers/pull/4

**Comment by PilzAdam** [comment] 2016-03-28 08:09
> Pipeworks directly modifies the inventory, but doesn't activate the furnace. I checked and none of the methods in the furnace get called when items are injected in the inventory

Why is that?

> so this would require to be patched in pipeworks it just has to start the timer if there is none running, which should be fairly simple.

This is not a proper fix. We shouldn't break mods with changes in minetest_game.

**Comment by tenplus1** [comment] 2016-03-28 10:12
Thanks for solution Sofar, hoppers now fixed and working.

**Comment by paramat** [comment] 2016-03-28 10:36
> We shouldn't break mods with changes in minetest_game.

Often it's necessary and the best solution.

**Comment by kilbith** [comment] 2016-03-28 10:39
> Often it's necessary and the best solution.

Sure, easy to say when you don't maintain such mods with metadatas stuff.

**Comment by PilzAdam** [comment] 2016-03-28 13:09
> Often it's necessary and the best solution.

I strongly disagree. Since minetest_game has grown into this base for so many mods, I hold it up to the same standards as the engine API.

**Comment by paramat** [comment] 2016-03-28 15:22
Sorry, i mean, sometimes it's necessary.

**Comment by kilbith** [comment] 2016-03-28 15:40
No you didn't mean "_sometimes_". You clearly wrote "_often_".

**Comment by sofar** [comment] 2016-03-28 18:29
So, I initially assumed that since the callbacks ```on _inventory_put``` wasn't getting called that there was no way of solving this problem without fixing the mods. After all, if you consider each node an object, and one messes with internal members of the other, then it is generally an acceptable rule to write "If you mess with my internals, afterwards please call my function foo() so I can act on that new data".

However, in an ideal world, if an itemstack associated with a node is modified (```stack:add_item(item)``` is called), then the code that is handling the storing of the new item should be able to call the callback ```on_metadata_inventory_put``` afterwards. And that callback (in this case) properly starts the nodetimer already.

So, I'll look and see if we can have that callback called, and then all the workarounds can be removed.

**Comment by PilzAdam** [comment] 2016-03-28 18:55
> However, in an ideal world, if an itemstack associated with a node is modified (stack:add_item(item) is called), then the code that is handling the storing of the new item should be able to call the callback on_metadata_inventory_put afterwards. And that callback (in this case) properly starts the nodetimer already.

> So, I'll look and see if we can have that callback called, and then all the workarounds can be removed.

I would prefer this solution.

Btw, you have to call `inv:set_stack` to actually change the inventory; `stack:add_item` only modifies your local copy of the stack.

**Comment by sofar** [comment] 2016-03-28 19:18
pipeworks uses ```inv:add_item()```

https://github.com/minetest-mods/pipeworks/blob/master/compat.lua#L23

**Comment by PilzAdam** [comment] 2016-03-28 21:11
Theres really no difference. These functions of the inventory should call the `on_put` methods. Probably an engine bug.

**Comment by sofar** [comment] 2016-03-28 21:16
I can see why it's missing - you'd have to find a backpointer from the ```inventory``` to the ```node```, and I don't think there is one right now.

**Comment by sofar** [comment] 2016-03-29 06:58
The lua_api parts just never call any of the callbacks. They notify the server code to update blocks, but nothing more.

**Comment by paramat** [comment] 2016-03-30 22:19
#980 merged.

**Comment by paramat** [comment] 2016-03-31 23:05
Do the remaining problems need fixing before release?

**Comment by sofar** [comment] 2016-03-31 23:15
They should be fixed. I'm in the middle as to where it's crucial that they must be fixed before release, but prefer it if it would.

The culprit is that in ```src/script/lua_api/l_inventory.cpp``` we notify clients of inventory changes, but do not call a single lua `on_metadata_*``` handler, and I have no idea how to add the callbacks. All the callbacks are right now in ```src/script/cpp_api/s_nodemeta.cpp``` but I don't know what the right way to bridge those two together is.

Should I let it go higher up the stack and then notify? or add a backref from the itemstack to the inventory and use the backref pointer immediately in the lua_api code?

**Comment by PilzAdam** [comment] 2016-04-01 14:01
@paramat yes, of course. This is a blocker since it breaks mods.

**Comment by sofar** [comment] 2016-04-06 02:08
Discussion from IRC with @ShadowNinja 

<ShadowNinja> sofar: That's a bit difficult, since the check has to be done in inv:set_item, where you have to check how the stack changed to decide if inv_put or inv_take (or both, or neither) has to be called.
<ShadowNinja> The "best" solution is probably just having mods call "on_put".
<<ShadowNinja> It makes the ABM->timer change breaking, but there isn't really a better solution.  Anything else would probably just be a hack.
<ShadowNinja> And the "set_item calls on_meta_inv*" change would likely break other mods.

tbh, I personally agree that calling random callbacks isn't an appropriate solution. This doesn't feel like an engine issue since the engine doesn't know which one to call. Perhaps the _put, _take and _move callbacks should have been combined altogether?

Only the calling mod code knows which of the 3 callbacks is the right one. The mod may also want to shuffle with several of the nodes' inventories and *then* call callbacks, not before it's done modifying them as well, further complicating any implementation that automatically calls any of the callbacks.

**Comment by paramat** [comment] 2016-04-15 12:56
@PilzAdam @ShadowNinja thoughts on this?

**Comment by sofar** [comment] 2016-04-15 17:36
It seems (1) everyone acknowledges that this is a regression, and (2) there are two apparent solutions.

Proposed solutions are:

(a) the engine calls callbacks
(b) mods should call callbacks

Solution (a) has issues, because the API does not account for subtle differences in put/get/update easily. It also would add a lot of complex code that may get it wrong and break mods by calling unexpected callbacks.

Solution (b) has issues, because while being the best possible and most efficient solution, it breaks existing mods

My gut feeling is that (b) is the right way to go, as "object a manipulates object b's internals" should result in "object a calls a notification for object b". Once "object a" goes away nothing in the core knows what the hell happened and it can only make misinformed guesses.

**Comment by sofar** [comment] 2016-04-16 19:38
As for impact - the mods that were affected by this have been patched about 3 weeks ago already, so this is not as urgent as it was.

**Comment by paramat** [comment] 2016-04-19 02:06
@PilzAdam @ShadowNinja this can possibly be removed from milestones, unless someone wants to work on it.

**Comment by PilzAdam** [comment] 2016-04-19 14:30
@paramat the affected mods are patched with a workaround, so we could release without resolving this issue. But this is still very high priority.

**Comment by sofar** [comment] 2016-04-19 15:52
@PilzAdam  can you please respond to @shadowninja's assessment ? The statements you and him made are in conflict, and cannot be resolved until you or shadowninja come to an agreement.

**Comment by paramat** [comment] 2017-01-14 04:20
@sofar was this solved by recent furnace changes?

**Comment by sofar** [comment] 2017-01-14 07:48
Very old bug. All the mods have been fixed a long time ago.

**Comment by paramat** [comment] 2017-01-14 20:31
Ok i assume this is ok to close then.

**Closed by paramat** 2017-01-14 20:31 UTC
Labels: Bug, Engine change needed, Possible close
