### ISSUE TITLE
Sounds are lost when placing blocks quickly.

### ISSUE THREAD

**Issue by Loppansson** [minetest/minetest_game#3083] opened 2023-12-20 12:20 UTC
**Release:** 5.8.0

**Current Behavior:** As can be seen in [my video on PeerTube at 15:41](https://spectra.video/w/tiKd6YgkwMUHLriK91U4tz?start=15m41s), sounds are lost when placing multiple blocks quickly. In other words, when placing two blocks in quick succession, only the sound effect for the first placed block is played.

**Comment by appgurueu** [comment] 2023-12-20 13:29
Sounds like an engine issue. @minetest/supertriagers could you transfer this?

**Comment by Desour** [comment] 2023-12-20 14:01
Duplicate of https://github.com/minetest/minetest/issues/13154.

**Closed** 2023-12-20 14:12 UTC
