### ISSUE TITLE
Saplings don't respect protected nodes

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest_game#1192] opened 2016-07-12 19:16 UTC
https://youtu.be/iNlXsGm5FO0?t=47m15s

**Comment by Fixer-007** [comment] 2016-07-13 00:00
Can confirm.

**Comment by paramat** [comment] 2016-07-13 12:24
Discussion http://irc.minetest.ru/minetest-dev/2016-07-12#i_4648623

Proposed solution:
New API 'is protected in area (player, minp, maxp)' that quickly checks all nodes in a volume for any protected areas not belonging to 'player'.
This check runs in sapling 'on place' function, and don't place sapling if not allowed.
Volume for each tree is roughly known: jungletree 5x5x16 etc.

**Comment by tenplus1** [comment] 2016-07-13 13:48
How slow would that make growing a tree on server having to check ALL nodes ?!?!?!  If an area is protected then the sapling itself cannot be placed, that's more than enough checking required to stop a tree growing.

**Comment by paramat** [comment] 2016-07-13 13:57
See discussion, the problem is a sapling under a protected area and growing into it.
However checking every node might be intensive, i might prefer just checking 6 or so nodes: one at tree centre and 5 at edges.

**Comment by paramat** [comment] 2016-07-13 13:59
How does a protection check work? does it scan a volume nearby for a protection block and check its defined volume of protection?

**Comment by rubenwardy** [comment] 2016-07-13 14:04
AreaStores, usually.

**Comment by paramat** [comment] 2016-07-13 14:10
```
-- To be overriden by protection mods
function core.is_protected(pos, name)
	return false
end
```
Just seen this, problem is some protection mods may not be so efficient.
For this non urgent problem it may be best to just check a few points.

**Comment by everamzah** [comment] 2016-07-13 20:30
Interestingly, it takes almost an hour to grow a tree, so there's plenty of time to check for protected nodes.

**Comment by tenplus1** [comment] 2016-07-14 09:04
https://github.com/minetest/minetest_game/pull/1195

**Comment by paramat** [comment] 2016-07-18 22:32
Further discussion for a simpler (possibly temporary) check.
#1195 is no solution. I might work on the discussed simple solution soon.

**Comment by paramat** [comment] 2016-07-19 00:09
See #1208

**Comment by paramat** [comment] 2016-07-27 20:47
#1208 merged.

**Closed by paramat** 2016-07-27 20:47 UTC
Labels: Bug, Feature request
