### ISSUE TITLE
Dry grass on dirt does not grow (anymore, but it should)

### ISSUE THREAD

**Issue by Montandalar** [minetest/minetest_game#2684] opened 2020-05-18 11:22 UTC
In development of 5.2.0 ([this commit](https://github.com/minetest/minetest_game/commit/c32b8adaa36353f9b21d896e93cce732e26cf0a0#)) replaced the default dirt in savannah biomes with dry dirt, while the older dirt_with_dry_grass nodes were left unchanged. At the same time, spread for dry grass on dirt/dry grass on dry dirt was disabled, according to paramat this was so that the savannah could have patchs of bare dry dirt ([according to issue #2405](https://github.com/minetest/minetest_game/issues/2405)).

I understand the aesthetic reasons for the dry grass not growing on dry dirt but as-is it also makes the dry grass unable to reproduce as a species, unlike other grass species. I don't see why spread should be left disabled for dry grass onto ordinary (not dry) dirt; you could say perhaps that the grass grows easily onto the 'moist' soil. Since this kind of soil is not found in the mapgen any more, it will not be an issue, and it will also stop existing older worlds from having their functionality changed. Anyway this fits my style of play where you can effectively 're-biome' an area by placing a new kind of grass there and growing grass etc. with bonemeal (yes I know bonemeal is a mod). I hope the dry grass doesn't go extinct!

**Comment by paramat** [comment] 2020-05-18 22:09
I would only agree to this if it can be done very simply, as being able to reproduce dry grass is not a high priority.

I am now wondering if bare patches of dry dirt in savanna was a mistake, it is not essential and made code more complex.

The plant reproduction/spreading code in MTG is a horrible mess, the worst aspect of MTG and the main reason i want to move on.
Tree and their saplings are ok, but i am thinking that plants should have optional and controllable reproduction using seeds and nodetimers, no ABMs. Perhaps also auto-replanting of a seed when digging a plant.

**Comment by Montandalar** [comment] 2020-05-22 09:38
Here is my proposal:

Bare patches should be made of clay, so that they are not grown over. Then restore growth of dry grass onto dry dirt and normal dirt. Then players can grow as much grass as they want, but the bare patches will stay.

**Comment by paramat** [comment] 2020-05-22 18:27
We cannot do that, bare patches in savanna are intended to be bare dirt and can be nothing else.
Besides, we might not need to do that.

**Comment by tenplus1** [comment] 2020-05-23 09:03
Why not keep dry_grass_on_dirt as a spreadable type and when cooked in furnace it outputs dry_grass_on_dry_dirt to supply any need for that node, same with dirt to dry_dirt.

**Comment by paramat** [comment] 2020-05-23 23:30
> Why not keep dry_grass_on_dirt as a spreadable type

That might be possible.
> when cooked in furnace it outputs dry_grass_on_dry_dirt to supply any need for that node

No point, as all new savanna areas now have dry_grass_on_dry_dirt, there is no need to produce that node.
It should not be obtainable as digging should give dirt or dry dirt.
Placing dry grass in a furnace should burn up the dry grass.

**Comment by Montandalar** [comment] 2020-05-25 03:53
Not obtainable in the base game does not necessarily mean unobtainable. The crystal shovel from ethereal lets you obtain and transport grass blocks. But if this is not satisfactory, we still need to come to a solution that works for the vanilla game I suppose. I still don't see any reason to stop the spread of dry_grass_on_dirt at least.

As for the bare dirt patches, would it hurt to make another node specifically for them? It could be called 'dry clay' and have a clay texture in the colour of the dry dirt. The dry clay has to be wet by contact with a water node or with a bucket of water to turn it into ordinary clay.

**Comment by tenplus1** [comment] 2020-05-25 20:05
That would be a good idea Montandalar, if water is near dry dirt or dry dirt with dry grass then it changes to to the normal dirt variant, which can easily be re-dryed in a furnace if need be and only the normal dirt variant can spread :)

**Comment by paramat** [comment] 2020-05-25 20:59
> As for the bare dirt patches, would it hurt to make another node specifically for them? It could be called 'dry clay'

It is messy, unsuitable and unacceptable to change bare dry dirt patches into something else, because they are intended to be bare dry dirt and cannot be anything else.
I would far rather remove the bare patches completely if something must be done and there is no other solution. I do not mind removing the bare patches as i am wondering if they were a mistake, savanna rarely has bare dirt patches and looks fine without them.

I have already responded to your suggestion above:
> We cannot do that, bare patches in savanna are intended to be bare dirt and can be nothing else.
Besides, we might not need to do that.

As i wrote above ("Besides, we might not need to do that"), there is no need to suggest messy solutions yet because this issue might be fixable in a simple and acceptable way. Please wait until a core dev has time to investigate this.
I agree with allowing dry grass to spread on dirt if that can be done in an acceptable and fairly simple way. When i have time i will investigate this.

**Comment by paramat** [comment] 2020-05-25 22:46
PR #2687 
Please test this PR and let me know if it does what it intends,

**Comment by koi-ghoti** [comment] 2020-05-27 21:39
I ran into this problem today. It makes the area very ugly if you have to do some digging and you like to preserve the natural environment.

**Comment by paramat** [comment] 2020-05-28 18:06
Yes i admit the commit went unnecessarily far in removing spreading behaviour of the old savanna nodes. Luckily this is simply fixable.

**Comment by paramat** [comment] 2020-06-16 19:43
PR merged.

**Closed by paramat** 2020-06-16 19:43 UTC
Labels: Request / Suggestion
