### ISSUE TITLE
Better sounds

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest_game#1204] opened 2016-07-18 10:40 UTC
Minetest sounds are usable but needs to be enhanced

**Comment by MarkuBu** [comment] 2016-07-18 13:46
you should specify what exactly you mean. 

Some of the sounds like footstep on grass are ok, others like snow or ice are terrible

**Comment by masrourmouad** [comment] 2016-07-18 15:04
sound of snow or ice 
sound of dirt
a lot of sound are missing missing like wool, chest, water, lava
when you jump into water there is no sound

**Comment by tobyplowy** [comment] 2016-07-20 23:19
@masrourmouad I think the dirt sounds are okay but they could be improved.
We really need water and lava sounds ( for water we need a sploensh sound and a water stream flow sound And for lava we need a pop sound And a lava stram sound) 
And i hate the snow sownd it's way too noisy and too repetitive
I also think the wood sounds should be a little bit more Crackle like old wood ( Minecraft wood sound is a great example of what I'm trying to say here)
Also @paramat if you walk on a iron trapdoor it makes wood sounds

**Comment by paramat** [comment] 2016-07-20 23:23
Steel trapdoor has stone defaults now instead of wood https://github.com/minetest/minetest_game/commit/f796194c6959ca4e560bfcb03f173e06a94755de

**Comment by tobyplowy** [comment] 2016-07-20 23:25
@paramat oh okay sorry I'm not on the newest unstable sorry for the misunderstanding again :\

**Comment by Wuzzy2** [comment] 2016-08-16 10:10
Some sound ideas:
- Player sounds:
   - Spawn (only played near player, not everywhere)
   - Disconnect (only played near player, not everywhere)
   - Hitting enemy
   - Death
   - Taking damage by hit
   - Taking damage by falling
   - Taking drowning damage (?)
   - Eating (I offer you to use the eating sound of `hbhunger`, no conditions)
- Placing boat
- Taking boat
- Putting out fire
- Nya-nya sound for mining and placing nyan cat (my Weird subgame has this in the `nyan` mod, these sounds are Public Domain and you can feel free to use them)

IMO the player sounds is the biggest area where Minetest Game is lacking in sounds.

**Comment by tobyplowy** [comment] 2016-08-16 13:48
@Wuzzy2 well that's exactly all the sounds that shuld get added (And the player sounds really are lacking) 1+ from me

**Comment by paramat** [comment] 2016-08-16 14:14
freesounds.org
Please search around for any good ones, i have an account so can use them.

**Comment by Fixer-007** [comment] 2016-08-16 14:17
With proper licence :)

**Comment by MarkuBu** [comment] 2016-08-27 08:33
default_dirt_footstep.1.ogg has a disturbing "crack" sound

**Comment by MarkuBu** [comment] 2016-08-27 09:03
Suggestion for new snow footstep sounds. Extracted from this sound

http://www.orangefreesounds.com/footsteps-in-snow-sound-effect/

License: https://creativecommons.org/licenses/by-nc/4.0/

[default_snow_footstep.zip](https://github.com/minetest/minetest_game/files/440570/default_snow_footstep.zip)

**Comment by MarkuBu** [comment] 2016-08-27 09:26
Suggestion for new ice footstep sounds. Not perfect, but better than glass

http://www.orangefreesounds.com/walking-on-ice/

License: https://creativecommons.org/licenses/by-nc/4.0/

[default_ice_footstep.zip](https://github.com/minetest/minetest_game/files/440578/default_ice_footstep.zip)

**Comment by tobyplowy** [comment] 2016-08-27 09:57
@MarkuBu I really like these sounds especially the snow sownds

**Comment by MarkuBu** [comment] 2016-08-27 10:00
I'm not finally happy with the ice sounds. Will try to find better

I hope, the licence is ok for Minetest

**Comment by Wuzzy2** [comment] 2016-08-27 19:35
CC-BY-NC 4.0 is an absolute no-go, sorry.

**Comment by paramat** [comment] 2016-08-27 19:39
The current snow sound that sounds like a door slamming has to go.

**Comment by MarkuBu** [comment] 2016-08-27 20:08
It is hard to find good sounds in good quality with a free licence

**Comment by tobyplowy** [comment] 2016-08-28 11:38
@paramat actually now that you say it, it actually sounds like a door slamming never really noticed that XD (but the snow sounds are terrible so it should be replaced with something better!)

**Comment by sofar** [comment] 2016-08-29 22:07
This request is too generic. We can't close it even if we fix the snow footstep sound. I suggest closing this and taking only specific feature requests for things that can actually be fixed (e.g. a bug for "replace snow sounds" is entirely reasonable).

**Comment by paramat** [comment] 2016-08-29 22:36
I agree the issue is too vague, it's also obvious, we are always trying to improve the sounds.

**Closed** 2016-09-22 12:40 UTC
Labels: Possible close, Request, Sounds
