### ISSUE TITLE
Placing bed in front of any node destroys both node and bed

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#950] opened 2016-03-18 16:20 UTC
Beds seem to be very broken at the moment.
Just place a bed facing somewhere directly in front of a solid node and facing that node so that the second “half” of the bed would, in theory, end up at that place.
Now the bed is gone and so is the node.

Things get even uglier if the solid node is another bed part. Now the old bed is partly destroyed, too!

IMO the mod should completely prevent placement if any collisions like this occour.

d90a0817223e33996b7fc3bb1c986da3a324aa98

**Comment by sofar** [comment] 2016-03-18 17:47
agreed, this should probably get fixed in 0.4.14, and will take a look at this.

**Comment by everamzah** [comment] 2016-03-19 01:59
FWIW, this only removes the frontal node the first time.  The second time `reverse` is false, so things seem to work correctly.  The third time things go awry once more and the bed becomes a powerful mining tool.

https://github.com/minetest/minetest_game/blob/master/mods/beds/api.lua#L16

**Comment by sofar** [comment] 2016-03-19 02:01
beds are entirely broken at this point.

- anyone can sleep in a bed that's in a protected area
- beds can be placed in ares not owned
- beds place over any node

yikes. I'm looking into it.

**Comment by everamzah** [comment] 2016-03-19 02:11
@kilbith wrote a beds mod using meshnodes that works quite well when rotated.  It also prints a friendly message when there is not enough room, and is licensed WTFPL.

https://forum.minetest.net/viewtopic.php?f=9&t=11817

**Comment by sofar** [comment] 2016-03-19 03:13
I have fixes for all the listed issues above. PR coming in a sec.

**Comment by sofar** [comment] 2016-03-19 03:15
I'd like to fix first instead of replacing this mod. It seems the fixes are relatively simple, so replacing the whole code is something we can do later.

**Comment by red-001** [comment] 2016-03-19 15:14
What's the advantage of using meshnodes for beds?

**Comment by sofar** [comment] 2016-03-19 16:49
#955

**Comment by sofar** [comment] 2016-03-19 21:03
@red-001 since beds do not move (like doors) or swap as pair, there's little to no gain to make them a meshnode.

**Comment by paramat** [comment] 2016-03-21 16:12
Did #955 fix this?

**Comment by sofar** [comment] 2016-03-21 16:19
No. While it could be (ab)used for this, it's turned into a feature, not an anti-griefing thing.

**Comment by sofar** [comment] 2016-03-29 20:59
@paramat I'm completely confused in my last reply. Yes, #955 fixes this issue.

**Comment by everamzah** [comment] 2016-03-30 00:37
@sofar @paramat 

Right clicking a door with a bed results in a door replacing an adjacent node.

![screenshot_20160329_201653](https://cloud.githubusercontent.com/assets/1761623/14128335/f65f811c-f5ed-11e5-97a7-2033eb10f2ba.png)

**Comment by sofar** [comment] 2016-03-30 02:46
@everamzah was that node protected?

**Comment by Fixer-007** [comment] 2016-03-30 13:32
Can't reproduce

**Comment by paramat** [comment] 2016-03-30 19:50
@everamzah could you open a new issue for that? This issue is fixed.

**Closed by paramat** 2016-03-30 19:50 UTC
Labels: Bug, High priority

**Comment by everamzah** [comment] 2016-03-31 01:45
https://github.com/minetest/minetest_game/issues/991
