### ISSUE TITLE
Slabs textures not rotated to match facedir

### ISSUE THREAD

**Issue by webdesigner97** [minetest/minetest_game#1109] opened 2016-05-23 20:36 UTC
If you have a slab that's supposed to facedir because of a texture that needs to be rotated for each direction, you'll discover that the slab gets replaced by itself, but with a static facedir value.
With this behaviour, it is impossible to make the slab rotate to align its texture.

Edit:
![](https://camo.githubusercontent.com/0acf120979c90de6cd54b4fac030ca410aec60d3/687474703a2f2f692e696d6775722e636f6d2f6f426e777779432e706e67)

**Comment by sofar** [comment] 2016-05-23 20:38
I'm not following, facedir is not a static thing, and the screwdriver can always rotate slabs in every way possible.

**Comment by webdesigner97** [comment] 2016-05-23 20:40
The problem is that the stairs mod seems to be setting it to a staic value somewhere. It's quite hard to describe, maybe you want to check it out on a server?

**Comment by sofar** [comment] 2016-05-23 20:54
make screenshots to show your problem? I can't try it if I don't understand what I'm looking for.

**Comment by webdesigner97** [comment] 2016-05-23 20:55
Or maybe you want to try it out on your own. The problematic slabs are in this mod: https://github.com/webdesigner97/streets/tree/relaunch

Give yourself stairs:slab_asphalt_side_slim and place it from diffrent angles. You'll notice the problem. I can't show it on screenshots because that wouldn't be better than a text about the problem ;)

**Comment by webdesigner97** [comment] 2016-05-23 20:57
You'll never notice that for cobble slabs or other default ones because their textures don't require rotation ,while mine do.

**Comment by sofar** [comment] 2016-05-23 21:03
The wood slab textures rotate fine for me when I place it e.g. sideways-up. Please make screenshots of your problem. I'm not going to try your custom mod. The default wood texture isn't symmetric so it should be fine to demonstrate the issue.

**Comment by webdesigner97** [comment] 2016-05-23 21:04
Whatever, I'll try my best ;)

**Comment by webdesigner97** [comment] 2016-05-23 21:08
Maybe this set of screenshots explains the problem: http://imgur.com/a/0IO52

The node I'm pointing at was placed just before I took the screenshot. You'll notice that all slabs have the same orientation, although they were placed from 4 different look directions.

I hope you can understand the problem now...

**Comment by sofar** [comment] 2016-05-23 21:12
I think I'm starting to understand what you're trying to say:

![](http://i.imgur.com/B6VGzmv.png)

You're looking at:

```
slab     slab
planks   planks
```

The slab on the left will never align with the wood below (unless I rotate the wood, of course)

Reason: slabs are (1) bottom-block-halve meshes that are (2) textured *before* rotation.

If you want to make all the slab align in the same pattern, you need to create a "top-of-block-half mesh" version of the slab. It's mathematically (geometrically) impossible for slabs to match the texture pattern BOTH ways.

Is this the problem you are seeing?

**Comment by sofar** [comment] 2016-05-23 21:15
> You'll notice that all slabs have the same orientation, although they were placed from 4 different look directions.

The slab placement code automatically rotates slabs to match adjacent slabs, on purpose. Why?

1) the chance that you *want* them to match is very high
2) the chance that you *don't want* them to match is very, very low.

This is intentional.

**Comment by webdesigner97** [comment] 2016-05-23 21:20
Now I'm not sure if I understand you... Maybe another screenshot helps:
http://i.imgur.com/oBnwwyC.png

**Comment by webdesigner97** [comment] 2016-05-23 21:21
But I think you got the point now... I cannot agree to point 2. It depends on the mod whether you want slabs to match or not. Just because the chance is low for minetest_game, some mods (like streets) do need this behaviour.

**Comment by sofar** [comment] 2016-05-23 21:21
hmmm, that last image is a lot better at showing an issue, yes.

**Comment by webdesigner97** [comment] 2016-05-23 21:23
hehe, took some time to find an appropriate setting for showing it...

**Comment by paramat** [comment] 2016-05-24 00:06
This needs fixing, big problem.

**Comment by paramat** [comment] 2016-07-24 19:10
So it seems the problem is that, although slabs have 'paramtype2 = facedir' the textures are not rotated to match the facedir.

![screenshot_20160724_200845](https://cloud.githubusercontent.com/assets/3686677/17085848/77248886-51da-11e6-8f60-450fe99218f0.png)

Confirmed with brick texture for slabs, but see stairs, here these 4 stairs were placed with the player facing the 4 directions, but the texture is rotated to match facedir.

**Comment by paramat** [comment] 2016-07-25 23:45
Issue moved to https://github.com/minetest/minetest/issues/4357

**Comment by paramat** [comment] 2016-09-13 01:10
Oops i think i'm wrong (hopefully), slabs have param2 set to 0 here https://github.com/minetest/minetest_game/blob/master/mods/stairs/init.lua#L144

**Comment by paramat** [comment] 2016-09-14 00:18
Confirmed i was wrong, i made snow slab facedir' and it worked.

**Comment by paramat** [comment] 2016-09-22 13:02
#1111 is merged.

**Closed by paramat** 2016-09-22 13:02 UTC
Labels: Bug
