### ISSUE TITLE
suggestion: Use submodules

### ISSUE THREAD

**Issue by Hume2** [minetest/minetest_game#2417] opened 2019-07-20 11:05 UTC
Currently, it is impossible to fork only one mod from the default game. My suggestion is as follows: Each mod from minetest_game should have its own submodule. So if I want to fork only one mod, I won't need to fork whole the game or do non-git operations.

**Comment by SmallJoker** [comment] 2019-07-20 11:09
Duplicate of #875

**Closed by SmallJoker** 2019-07-20 11:09 UTC
