### ISSUE TITLE
New TNT sounds needed (was: license for tnt_explode.ogg isn't specified?)

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest_game#2435] opened 2019-08-09 19:31 UTC
I'm looking to use `tnt_boom.ogg` in my grenades PR for CTF but when I look at the `license.txt` I see nothing about the license for that sound or the other ones. Unless someone forgot to add `sounds` on line 30? https://github.com/minetest/minetest_game/blob/master/mods/tnt/license.txt#L30

**Comment by SmallJoker** [comment] 2019-08-09 20:39
Originally it was WTFPL: https://github.com/minetest/minetest_game/commit/1e628ed
Needs documentation to clarify that.

**Comment by LoneWolfHT** [comment] 2019-08-09 20:48
I can create a PR. Should I change the license to MIT while I'm at it?

**Comment by TumeniNodes** [comment] 2019-08-10 00:00
for the sound file, just use CC BY-SA 3.0

>Should I change the license to MIT while I'm at it?

change _what_ license to MIT? the overall code for tnt? 0_o

**Comment by LoneWolfHT** [comment] 2019-08-10 00:03
> for the sound file, just use CC BY-SA 3.0
> 
> > Should I change the license to MIT while I'm at it?
> 
> change _what_ license to MIT? the overall code for tnt? 0_o

SmallJoker said the license for the TNT sounds was WTFPL.
I'm offering to create a PR that says what the license for the sounds is. If it *is* WTFPL I should be able to change it to MIT, or on second though, CC0

**Comment by TumeniNodes** [comment] 2019-08-10 00:04
That was in the original before it was all merged into MTG

everything should be properly covered now

**Comment by LoneWolfHT** [comment] 2019-08-10 00:04
> Licenses of media (textures)

Line 30 ^
Only says `textures` there. I see nothing about sounds

**Comment by TumeniNodes** [comment] 2019-08-10 00:05
well, "License of media" basically means all media, visual and audio but I see where the confusion is now

**Comment by LoneWolfHT** [comment] 2019-08-10 00:07
> I think just removing the "(textures)" bit would suffice unless someone feels differently

Ok, I can create a PR for that too

**Comment by TumeniNodes** [comment] 2019-08-10 00:08
see my comment above please, I edited :P I think (textures/audio) is better but wait for a core dev to chime in on it

**Comment by TumeniNodes** [comment] 2019-08-10 00:11
actually, go ahead and whip that PR together and put it up... if someone wants it done diff they'll let you know in the reviews ; )
giddyup

**Comment by LoneWolfHT** [comment] 2019-08-10 03:58
How would one go about adding the sound license to this section? PilzAdam's sounds under WTFPL?
![image](https://user-images.githubusercontent.com/28972859/62817273-3e2fa680-bae8-11e9-8678-50ed3cf1cec4.png)

**Comment by paramat** [comment] 2019-08-10 19:32
We avoid WTFPL now, MIT is for code only i think, so i guess this should be licensed CC0.

**Comment by Linuxdirk** [comment] 2019-08-14 11:59
So you don't know the author but you know the license?

**Comment by TumeniNodes** [comment] 2019-08-14 15:32
> So you don't know the author but you know the license?

Good point, not knowing where it originated from is a bit of a problem
(wondering if it should be replaced)

**Comment by paramat** [comment] 2019-08-14 17:26
Looking through Freeminer ...

**Comment by paramat** [comment] 2019-08-14 17:35
Hm actually, we don't know what the sound license is. I searched through Freeminer and MTG history and there is no credit or license anywhere for the sounds, so the license could be anything and we can't assume it is WTFPL -> CC0.
Until we know best to leave them undocumented.

**Comment by Linuxdirk** [comment] 2019-08-15 08:00
So when author and license are unknown this is not suitable for being in an open source game because license could be a nonfree one which would cause issues.

**Comment by paramat** [comment] 2019-08-15 15:50
I'll try to track down the source of the sounds.

**Comment by paramat** [comment] 2019-08-15 16:08
TNT mod added here https://github.com/minetest/minetest_game/commit/1e628ed92aa1caea17c8e33fd15f76d8c8486f07#diff-089b7574e2fa91957f08a1ce5d20ba36
It's PilzAdam's mod, modified by Freeminer. The sounds were present in PilzAdam's initial mod.
Forum thread for original mod https://forum.minetest.net/viewtopic.php?f=13&t=2902&hilit=tnt+mod

**Comment by Linuxdirk** [comment] 2019-08-15 17:20
> I think all we can do for the moment is add a note stating author and license of sounds are unknown. Then work on finding new sounds.

Yes, that is the minimum.

Oh, and I don’t think that this is a low priority documentation issue, but a high-priority legal issue that could cause a lot of legal trouble for everyone.

**Comment by paramat** [comment] 2019-08-15 21:43
Yes, removed 'low priority'.
The comment should probably also state that the sounds should not be reused as the license is unknown.
I'll make a PR.

**Comment by paramat** [comment] 2019-08-15 21:54
Attempted contact https://github.com/PilzAdam/CertificateWatch/issues/1

**Comment by PilzAdam** [comment] 2019-08-16 22:37
See my reply here: https://github.com/PilzAdam/TNT/issues/3

**Comment by paramat** [comment] 2019-08-17 02:02
Thanks =)
Reproducing reply here:

//////////////////
If I remember correctly, I originally took the sounds from the nuke mod. This mod is also referenced in the forum thread of my TNT mod. tnt_ignite.ogg and tnt_explode.ogg are straight up copies from nuke_ignite.ogg and nuke_explode.ogg. tnt_gunpowder_burning.ogg is a modified version of nuke_ignite.ogg (a part cut out of the middle).

I just downloaded both mods and checked the files; they are identical. I guess you now have to ask @sfan5 where he got the original files.
//////////////////

**Comment by sfan5** [comment] 2019-08-18 16:21
Googling the md5sum reveals Minecraft as the source for `tnt_explode.ogg` and `tnt_ignore.ogg`.
Entirely proprietary of course, so those two will need to be replaced.

**Comment by TumeniNodes** [comment] 2019-08-18 16:59
woopsie doodles... I'd say it's a bit of a priority now that it's been mentioned.

**Comment by LoneWolfHT** [comment] 2019-08-18 17:46
2nd, maybe 3rd, and maybe 5th, all the rest won't work IMO, and they all need a little touching up

**Comment by paramat** [comment] 2019-08-18 18:07
LOL MC, ok those sounds are coming out immediately, no delay, will do now. Replace later.

**Comment by HybridDog** [comment] 2019-08-18 18:34
I've edited Explosion2, e.g. to make it mono.
[modified Explosion2.wav-80401.ogg.txt](https://github.com/minetest/minetest_game/files/3513415/modified.Explosion2.wav-80401.ogg.txt) (remove the .txt suffix after download)

**Comment by paramat** [comment] 2019-08-18 18:37
Initial PR #2447

**Comment by HybridDog** [comment] 2019-08-18 18:39
[MC old TNT explosion](https://www.youtube.com/watch?v=Hi53Bseg-mw&t=12)

**Comment by LoneWolfHT** [comment] 2019-08-18 18:48
I think the debris in that 2nd sound should be removed too, seems out of place

**Comment by LoneWolfHT** [comment] 2019-08-18 19:04
Hmmm, tnt_explode.3 in https://github.com/tacotexmex/snowsong might work too

**Comment by TumeniNodes** [comment] 2019-08-18 20:15
> I've edited Explosion2 to make it mono, remove very low frequencies and slightly cut the start and end.

Nice, sounds great. I like the trailing sounds at the end

**Comment by TumeniNodes** [comment] 2019-08-19 16:01
Ooof... the temp sounds are.... a bit _too_ temp-ish
We need some decent replacements quick

**Comment by TumeniNodes** [comment] 2019-08-19 20:33
a decent file for tnt_ignite I found
I already converted it to .ogg and reduced the file size to 52.9kb
https://freesound.org/people/theneedle.tv/sounds/316682/

**Comment by TumeniNodes** [comment] 2019-08-20 00:24
New PR
https://github.com/minetest/minetest_game/pull/2449

**Comment by paramat** [comment] 2019-08-28 02:15
PR merged.

**Closed by paramat** 2019-08-28 02:15 UTC
Labels: Request / Suggestion, Sounds
