### ISSUE TITLE
Tin block stairs sometimes are black in inventory/hotbar (also slabs and other materials)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#1959] opened 2017-11-28 08:59 UTC
Very weird, in ed83e30d6826083f273ca323420402485c260cdc, some (normal) stairs, inner stairs and outer stairs turn sometimes completely black in the hotbar, or when you pick them up via left click in the inventory.
In the hotbar, the affected stairs are only black if you have *not* selected it. If you highlighted it, the stairs look normal again.
It looks like an ordinary stair inventory image, except that all color pixels are black.
The wieldhand is OK.

Oddly, this happens especially with tin block stairs. I haven't seen this for other stair types so far.

MT version: c0dd4ea46acc37e873c28776142a57945f776d0b
MTG version: ed83e30d6826083f273ca323420402485c260cdc

**Comment by paramat** [comment] 2017-11-28 21:20
I did recently change these 3 to nodeboxes, maybe i made a mistake?

**Comment by TumeniNodes** [comment] 2017-11-29 07:04
Tin stairs were added after the fact paramat, remember? Maybe something small missed in the code when they got added?
It is odd, I have never noticed this

**Comment by paramat** [comment] 2017-11-30 02:29
Ah only tin. likely an issue with tin block texture.

**Comment by paramat** [comment] 2017-12-09 01:29
I just got dark slabs and stairs in aspen wood:

![screenshot_20171209_011831](https://user-images.githubusercontent.com/3686677/33791181-0cf52998-dc80-11e7-8827-85a15f842a9d.png)

![screenshot_20171209_011834](https://user-images.githubusercontent.com/3686677/33791185-1767b580-dc80-11e7-9fcd-250f8612fb69.png)

![screenshot_20171209_011912](https://user-images.githubusercontent.com/3686677/33791187-1becc73a-dc80-11e7-9964-2607a1bfbdae.png)

![screenshot_20171209_012040](https://user-images.githubusercontent.com/3686677/33791188-1f91d934-dc80-11e7-96e0-84e29c91d22c.png)

Moving the dark nodes to a new slot sometimes fixes it, returning it to the first slot makes it dark again.
Highlightng the node slot fixes it.

**Comment by paramat** [comment] 2017-12-09 02:22
Possibly engine related.

**Comment by Fixer-007** [comment] 2017-12-10 17:02
Confirmed on d677f292 with sandstone outer stair

**Comment by rubenwardy** [comment] 2017-12-10 17:12
This smells like an engine bug

**Comment by Fixer-007** [comment] 2017-12-10 17:14
Like this one? https://github.com/minetest/minetest/issues/4876

**Comment by Thomas--S** [comment] 2017-12-10 17:31
I experienced a very similiar thing with items from other mods on my server, so I think rubenwardy is right: This seems to be an engine bug.

**Comment by Fixer-007** [comment] 2017-12-11 00:12
Persists after complete game restart (at least on the same world restart).

**Comment by paramat** [comment] 2017-12-11 06:15
Thanks.

**Comment by paramat** [comment] 2018-01-20 13:49
https://github.com/minetest/minetest/pull/6780 merged.

**Closed by paramat** 2018-01-20 13:49 UTC
Labels: Bug, Engine change needed
