### ISSUE TITLE
Cheaper beds

### ISSUE THREAD

**Issue by alugarius** [minetest/minetest_game#1748] opened 2017-05-25 14:42 UTC
Problem 1: I have to find a red flower for like 5 hours to make a bed. thats screwing the gameplay.
Solution: 
Make multiclorored beds so dyes are not important, (red dye/wool = red bed, no dye/white wool = white bed, black dye/wool = black bed, etc) or remove the need of red wool/dye for a bed.
(several persons agreed to this on IRC)

Problem 2: Locked doors are useless because #954 and #1712 (i know, there're issues there, I'll explain)
Solution: (for #954 ) Not even allow a player to mine a block, you did this already in the way that i cant mine steel with a wooden pickaxe, that should be possible. (for #1712) make some official tool for multiplayer that makes any block locked for others. (there are mods for it so why not including them out of the box?)

**Comment by rubenwardy** [comment] 2017-05-25 14:56
This isn't going to happen, we've already entered feature freeze so only bug fixes will happen now.

**Comment by rubenwardy** [comment] 2017-05-25 14:57
Duplicate of #954

**Closed** 2017-05-25 14:59 UTC
Labels: Duplicate
