### ISSUE TITLE
Written books no longer editable (after book title commit?)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1622] opened 2017-03-12 00:37 UTC
I have a written book with my notes on 0.4.15-dev server called Hometown (@ExeterDad), it seems minetest_game was updated to new one that has book description commit, and now my book can be read, but I can't write new text into it, pressing save does not do anything, text remains the same.

Confirmed the bug on my local install. @octacian 

Could be related https://github.com/minetest/minetest_game/commit/c68b8274fed183f30bd7609018766a261448b83d

**To reproduce**:
* Download older MTG from here: https://codeload.github.com/minetest/minetest_game/zip/89c45993acae89ee1bc68f42e510f5304f13ffa9
* Create a fresh word
* In creative or survival give yourself a book and write title and text into this book, save it for sure and close the game.
* Now upgrade to newest MTG and open that world and try to edit that book you saved earlier - it will not save your changes and will stay the same (so it is impossible to edit Title and Contents, but tooltip somehow updates itself after save).

This issue is about backwards compatibility.

**Comment by sofar** [comment] 2017-03-12 00:52
Can't confirm. Made a book with title and text. Changed the text just fine. Changed the title too.

**Comment by ExeterDad** [comment] 2017-03-12 16:33
I went on the server last night to try to get my hands on a book authored with the older MTG without success. Myself nor anyone logged in seemed to have one. However I can confirm that creating, saving and editing a NEW book works as expected. I didn't really get to test too much as usually I can't get anything done unless I log in with an alt.

**Comment by octacian** [comment] 2017-03-12 18:13
I did very extensive testing on the books PR before even submitting the PR itself. Personally, I've never experienced the issue. New books work fine, and I believe the old books were fine too. Considering the code, it should definitely work in theory and I remember doing extensive testing updating old books to new. So yeah, I can't confirm this issue either.

**Comment by octacian** [comment] 2017-03-12 18:18
Wait.. This might actually be an issue. If the old data isn't removed/overwritten, the backwards-compatibility code would still be executed next time you viewed the book, and since the old data still existed the new data would be overwritten. I thought that using `:from_table(<table>)` would automatically overwrite everything, but there's a possibility that it only updates the specific fields, which would actually make sense.

I'll do some more testing if it is an issue I can fix it with 1 line of code after calling `:from_table()`:
```lua
itemstack:set_metadata("")
```

**Comment by Fixer-007** [comment] 2017-03-12 20:51
Nobody can confirm it? WTH, I can reproduce it 100% times on newest everything, am I explaining it wrongly?

Trying again:
* Download older MTG from here: https://codeload.github.com/minetest/minetest_game/zip/89c45993acae89ee1bc68f42e510f5304f13ffa9
* Create a fresh word
* In creative or survival give yourself a book and write title and text into this book, save it for sure and close the game.
* Now upgrade to newest MTG and open that world and try to edit that book you saved earlier - it will not save your changes and will stay the same (so it is impossible to edit Title and Contents, but tooltip somehow updates itself after save).

I can even record a gif if needed...

**Comment by ExeterDad** [comment] 2017-03-12 22:40
Is the book and meta stored in player files? If so I can grep them and find who has one. Even copy it over to another account for testing.

**Comment by sofar** [comment] 2017-03-12 23:07
@fixer oops yes, I can indeed reproduce this.

**Comment by octacian** [comment] 2017-03-14 05:07
I can reproduce this too. However, I'm really confused as to the reason. I did a bit of debugging, simply printing the new meta :to_table() output and the old get_metadata(), and I discovered that the latter is blank. This is super weird, but I'll see what I can figure out.

**Comment by octacian** [comment] 2017-03-14 05:11
**Update!** I found the cause right away. Somehow, yes, the old metadata is still hiding in there. I'm doing a bit more testing, but it turns out that some portions of the book code still using the old storage methods, which is kinda confusing as to why this worked at all. I'll submit a PR tomorrow hopefully fixing both this and the book crafting bug as they both have the exact same cause.

**Comment by paramat** [comment] 2017-03-20 00:20
#1636 merged.

**Closed by paramat** 2017-03-20 00:20 UTC
Labels: Bug
