### ISSUE TITLE
downsizing default

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest_game#2440] opened 2019-08-12 01:08 UTC
I figured I would try to get a discussion going, which has been beaten like a red-headed step-child's dead horse.
But it's worth having again

I am of the opinion, that default should only contain elements required for map generation.
Meaning the very basic, natural elements...
water, lava, stone, gravel, sand, dirt, dirt with grass, trees, (or maybe even trees and other vegetation should be separate as well?)

But basically, yeh, that is my idea regarding 'default'
Just the absolute basic, natural materials/elements required for generating a world...

Everything else should be done via mods... lighting, manufactured materials related to stones, woods etc., all done via mods

As a new series, I had actually wished that the 0.4.x series would have been left avail and maintained as needed and an entirely new project opened to start 5.0.x but that is just another personal opinion.
This way MTG2 could have been created almost from scratch, with lessons learned applied from the start

All still "doable"... it's never "too late" for such a restructure

**Comment by DS-Minetest** [comment] 2019-08-12 13:32
Related: #515

Nobody is stopping you from creating a new, very minimalistic subgame.

**Comment by TumeniNodes** [comment] 2019-08-12 13:55
>Nobody is stopping you from creating a new, very minimalistic subgame.

Started one just recently but it will remain local/unpublished until I get to a certain point.

I have another on github but I plan for it to be a creative only version for builders, which is very slow going, and it's actually a mess right now, as far as I need to go through and redo all the licensing.

**Comment by TumeniNodes** [comment] 2019-08-12 14:00
I think what I am getting at, is to provide just the very basics as I said, for map generation, and call it Minetest Base or something... rather than "game"

This would be targeted specifically toward game creators. It would provide the "world' foundation. From there they would need to provide the game content

**Comment by paramat** [comment] 2019-08-12 19:02
Duplicate of #726
 
Same problems too, this can't be done without a huge amount of aliases and stuff to maintain compatibility with everything that depends on MTG. The result would be even more of a unpleasant and complex mess than it is now, so it's not worth doing.
It would also be a move in the direction of 'perpetuating the unfixable pain of MTG' instead of moving on to new games.
MTG has to be maintained and bugfixed of course, due to what depends on it, but other than that our time and effort is better directed to new games.

The structure of MTG should be different i agree, with 1 mod that does the basic mapgen stuff.

**Closed by paramat** 2019-08-12 19:02 UTC
Labels: Duplicate

**Comment by TumeniNodes** [comment] 2019-08-13 00:03
I was referring to a sort of "MTG-2", not doing this with the current MTG.
Which is the only reason I figured I would put it up for discussion here.

Which is explained in the portion of the original post
>As a new series, I had actually wished that the 0.4.x series would have been left avail and maintained as needed and an entirely new project opened to start 5.0.x but that is just another personal opinion.
This way MTG2 could have been created almost from scratch, with lessons learned applied from the start

Only now, it would be looking at anything _after_ 5.0.1 (or .2)

**Comment by rubenwardy** [comment] 2019-08-13 00:47
> MTG has to be maintained and bugfixed of course, due to what depends on it, maybe occasionally add a minor feature, refinement is worth doing, but other than those our time and effort is better directed to new games.

This doesn't help as 99% of mods are targetted to MTG. The point of splitting up default is to make it easier to have inter-game modding. It is possible to split up default in a way that is backwards compatible, I just don't have the energy to do it and also deal with the bolitics needed to merge it

**Comment by paramat** [comment] 2019-08-13 21:49
Ok i misunderstood. I thought you meant reducing the size of default by moving stuff out into other MTG mods. I assumed this was the topic because creating a new game is somewhat off topic in this repo. Not sure where to discuss, but feel free to continue discussing here.
> Everything else should be done via mods

So i guess you meant non-MTG optional mods here.
You wrote 'restructure' which implied a restructure of MTG.

I am quite interested in taking the good parts of MTG and creating a new modding base game, indeed as you descibe being just a set of biomes and resources, plus creative mod, maybe nothing else.
Unfortunately MTG is halfway between being a modding base game and an 'impressive game', but no good at either, and can never be good at either.
We need new 'impressive' games and new 'modding base' games, and we need to give up trying to make MTG either of those.

**Comment by TumeniNodes** [comment] 2019-08-14 03:01
>So i guess you meant non-MTG optional mods here.
I am quite interested in taking some good parts from MTG and creating a new modding base game, as you describe being just a set of biomes and resources, plus creative mod, maybe nothing else.

Exactly, This is correct.

**Comment by paramat** [comment] 2019-08-14 21:24
rubenwardy, ok i may have slightly misunderstood. It seems what you propose would then have benefits for new games and the shift of focus to new games as it would be easier for mods to be multi-game. I'm still concerned about the amount of mess needed in MTG to do this.

**Comment by TumeniNodes** [comment] 2019-08-14 21:31
No mess, start a new  project/repo (an official fork) leaving the existing always avail and lightly maintained

**Comment by paramat** [comment] 2019-08-15 16:20
That's not possible while maintaining compatibility, a new MTG as you suggest would have no compatibility with mods that are based on it.
The mess i describe is compatibility code needed to allow the structure of current MTG to be improved.
What rubenwardy wants to do and what you want to do are different.
