### ISSUE TITLE
You can place items like tree trunks, etc without it being noted in the log, or calling registered_on_placenodes functions

### ISSUE THREAD

**Issue by est31** [minetest/minetest_game#656] opened 2015-08-30 07:16 UTC
The issue https://github.com/minetest/minetest/issues/1338 points into the mods direction. If a node overrides the `on_place` call, and it doesn't call `minetest.item_place` like the stairs mod, it risks to sneak item placement past logging, and past functions registered by `minetest.register_on_placenode`.

The problem affects at least the tree trunk node, but may also affect other nodes as well, like the grass node. I guess [a search](https://github.com/minetest/minetest_game/search?utf8=%E2%9C%93&q=on_place) would help identifying the suspects.

**Comment by LazyJ** [comment] 2015-10-23 06:29
Confirmed.

I placed nodes from the "default" mod in minetest_game. Trees, cactus, fence, jungletree, and pine trees were not recorded in the logs. MoreTrees' tree trunks were not recorded either.

The placement of these nodes were recorded in the logs of MT 0.4.12 but after upgrading to MT 0.4.13, they are not. In addition, the minetest_game we are using is several months old; it does not yet have the default acacia trees in it yet. This suggests the problem may be in the engine itself.

**Comment by LeMagnesium** [comment] 2015-10-23 09:06
> This suggests the problem may be in the engine itself.

I can guess what the problem is. It's part of the engine, but not inside the engine. It may be a problem of `callbacks`. You see, Minetest is designed in a way that when an event happens, a table of callback functions will be parsed to run every single one of the functions, but you're never really sure all of them will be run. Whenever one of them returns a value that is supposed to change the typical reaction of the engine (for example : return a specific ItemStack instead of taking one item from the wielded stack), [all of the following callbacks are left forgotten](https://github.com/minetest/minetest/issues/2615).. **including logging calbacks**.
I've already had to fix tons of such bugs on servers with more than 200 mods where 1 action could trigger 10 callbacks in a row, to make sure those 10 callbacks would be called whatever situation may happen. I already pushed more than 30 commits on their repository just to change the loading order of some mods to put the blocking callbacks at the end of the callbacks table. This is a problem which exists since at least 0.4.9 and surely before.

Here is my list of nodes which, I noticed, were not recorded in the logs with creative mode enabled : 
 - `default:acacia_tree`
 - `default:cactus`
 - `default:jungletree`
 - `default:tree`
 - `default:pine_tree`
 - `doors:door_glass`
 - `doors:door_obsidian`
 - `doors:door_steel`
 - `doors:door_wood`

Doors always block their logging callback [because they return an itemstack](https://github.com/minetest/minetest_game/blob/master/mods/doors/init.lua#L97). All those tree nodes and the cactus [use](https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua#L814) [`minetest.rotate_node`](https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua#L577) which handles the itemstack changes itself by [always returning an ItemStack object](https://github.com/minetest/minetest/blob/master/builtin/common/misc_helpers.lua#L469), blocking the logging mechanism.

**Comment by rubenwardy** [comment] 2017-01-02 16:06
From reading the code, it seems this is still an issue for nodes that use rotate node, but not doors

**Comment by paramat** [comment] 2017-05-24 06:13
See related https://github.com/minetest/minetest/issues/5807

**Comment by HybridDog** [comment] 2017-05-25 06:53
Does it also affect rollback?

**Comment by paramat** [comment] 2017-05-25 06:57
yes i think so, rollback uses the logging.

**Comment by est31** [comment] 2017-05-25 08:05
Unless something has changed since I was away, rollback is an entirely different system and uses its own database and everything.

**Comment by paramat** [comment] 2017-05-25 11:34
Yeah, i have no idea how rollback works.

**Comment by paramat** [comment] 2017-12-07 12:42
Is this fixed by https://github.com/minetest/minetest/pull/6648 ? @SmallJoker

**Comment by SmallJoker** [comment] 2017-12-07 16:03
No, that's only fixed for `minetest.rotate_node`, but not for `on_place` in general. Mods have to handle the node placement themselves if they overwrite that function.

**Comment by An0n3m0us** [comment] 2020-02-19 10:11
It seems to work fine now; I get placing and digging logs for the moretrees mod and the nodes mentioned in the original post.
And the rollback seems fine too; I did a check on some tree nodes.

**Comment by SmallJoker** [comment] 2020-02-19 17:48
Please ask to re-open if this is still an issue.

**Closed by SmallJoker** 2020-02-19 17:48 UTC
Labels: Bug, Engine change needed
