### ISSUE TITLE
Improving the glass door handle

### ISSUE THREAD

**Issue by paramat** [minetest/minetest_game#2260] opened 2018-11-07 23:36 UTC
The new glass door handle looks messy (too much meaningless noise) and it's orientation means when you have a double door the handles contact each other which seems odd for getting your hand around it, and visually the 2 handles merge.
It seems to be a metal U-shaped handle, where the tips of the U at each end are connected to the door like this:

![stainless-steel-door-handle-hero-new](https://user-images.githubusercontent.com/3686677/48167848-fd023000-e2e4-11e8-99a0-ff3f6b7da03c.jpg)

I suggest flipping the handle left to right to be as in that photo above. The U-tips are now closest to the door edge. This is the most ergonomic orientation as you use your arm that is on the hinge side, so your hand approaches the handle from the hinge side.
If liked i can update the textures and make the obsidian doors match (same handle and hinges).

![screenshot_20181115_021345](https://user-images.githubusercontent.com/3686677/48525495-42da6d80-e87c-11e8-99f4-9ef560b0a688.png)

![screenshot_20181115_021416](https://user-images.githubusercontent.com/3686677/48525498-47068b00-e87c-11e8-8207-940632831b04.png)

MTG master texture below:

![screenshot_20181115_015820](https://user-images.githubusercontent.com/3686677/48524928-1b82a100-e87a-11e8-8ef8-e95b0eb57ead.png)

![screenshot_20181115_015802](https://user-images.githubusercontent.com/3686677/48524939-20475500-e87a-11e8-8848-47c8604be45a.png)

Looks like someone installed the handles flipped and you can't grab them because they touch.

**Comment by Extex101** [comment] 2018-11-08 01:04
Nice! 
I'm all for it

**Comment by TumeniNodes** [comment] 2018-11-08 01:07
Looks good to me. And yes, obsidian glass doors should have been included in the last PR, I was too busy with IRL matters to mention it at the time.

**Comment by DS-Minetest** [comment] 2018-11-08 17:46
Related: #2252 
There were complaints about this issue already before the new glass textures PR was merged. But it was merged, so I thought this was intended because of thermic reasons.

However, like this the door handles make a 0 instead of an X. They have to be more right, on the glass instead of the frame that is no frame.

>If liked i can update the textures and make the obsidian doors match (same handle and hinges).

Personally I wouldn't like this as there's no good reason for uniform door handles. Each type of door can have their own style. By making it all the same, you would loose features. It would be a bit like removing the handle from a mug because you never drink any hot substances with it.

**Comment by paramat** [comment] 2018-11-08 21:07
Yes i could move the handle in one pixel to avoid a 'O' shape, happy to do that

**Comment by jastevenson303** [comment] 2018-11-14 06:10
no

**Comment by Fixer-007** [comment] 2018-11-14 19:58
Wonder how it will look ingame, as single and doubledoors

**Comment by paramat** [comment] 2018-11-15 02:02
yes

**Comment by paramat** [comment] 2018-11-15 02:02
I inset the handles by a pixel, good advice, new screenshots and comparison in first comment.

**Comment by TumeniNodes** [comment] 2018-11-15 02:49
> I inset the handles by a pixel, good advice, new screenshots and comparison in first comment.

The handles look much nicer now...

**Comment by paramat** [comment] 2018-11-26 00:37
WIP after input from Ezhh.

**Closed** 2018-12-22 00:33 UTC
Labels: Request / Suggestion, Textures
