### ISSUE TITLE
Player does not reliably sit down into boat

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#3043] opened 2023-07-10 18:40 UTC
If you want to enter a boat, the player model will not always be in the "sit" animation. Sometimes, the model is still standing. It is hard to predict when the player will actually sit and when not.

Operating the boat itself still works; this is a graphical bug.

### How to reproduce

- Set camera to 3rd person
- Place a boat
- Rightclick it

Repeat this multiple times. The player model should always sit down. But in reality, the sitting animation will only appear seemingly at random.

Minetest version: 5.7.0
Minetest Game version: 5.7.0

**Comment by appgurueu** [comment] 2023-07-10 19:25
Duplicate of https://github.com/minetest/minetest_game/issues/3042 (engine issue, fixed in 5.8-dev)

**Closed by appgurueu** 2023-07-10 19:25 UTC

**Comment by Wuzzy2** [comment] 2023-07-12 15:44
Rofl my memory is terrible. Thanks for the link.
