### ISSUE TITLE
Tools: rebalance needed

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#1681] opened 2017-03-31 19:38 UTC
**Update, read here first:**
https://github.com/minetest/minetest_game/issues/1681#issuecomment-347047311

**Bronze part of discussion:**
Since moreores/tin discussion bronze tools problem appeared to me, those tools were not good buy, I rarely used them. I decided to benchmark steel/bronze shovels durability in game (lua code was somewhat confusing), I ended up with:
Steel shovel - 271 mined sand, bronze - 361 mined sand (1.33x more durability, to little gain for twice the cost).

Bronze tools cost much more mining and time (since you need to mine/smelt both iron and copper, and craft two times), there are several solutions, not always realistic or whatever:
* Bronze tools have some special/unique ability, for example silk touch analog from MC: mined blocks go as mined blocks, without conversion to say cobblestone or ores. // Preffered for me right now
* Bronze tools have same mining speed/efficiency as steel, BUT twice as much durability (to compensate for the cost of crafting that tool), this will make it much more viable in game but IRL bronze is not that durable iirc
* Bronze tools will be removed (bronze/steel/tin/whatever itself will be used in further projects like automation).

**Comment by C1ffisme** [comment] 2017-03-31 21:03
In addition to this, I would suggest two other changes:

1. Bronze tools should be renamed to copper, and all bronze ingots and such will be aliased back to copper. Those tools will no longer require steel.
2. Copper tools will mine faster and longer than steel tools, but they cannot mine harder materials. (I.E. They can only mine the same blocks as a stone pickaxe can.)
(3. Also, copper should be made just a tad more common because of this.)

This makes copper tools a utility tool, and only useful for a certain purpose. The only problem with this is that a player could still carry a copper pick and a steel pick for harder things, which means he almost never needs to repair/replace either. Maybe copper pickaxes should break more easily on stone-based blocks? Or maybe if we ever invent enchantments/tool upgrades, copper pickaxes have limited upgrade-ability?

**Comment by tenplus1** [comment] 2017-04-01 08:47
I agree with the first point, bronze tools should be twice as durable as steel but dig at the same level...  Personally I would love if moreores themselves would make it into mtg and we'd have tin to mix with copper to make bronze instead of the steel+copper recipe, then it would give a good use for the abundance of tin.

**Comment by C1ffisme** [comment] 2017-04-01 15:32
@tenplus1 Except that as soon as you find mese or diamonds, tin and copper become useless. With my change, at least copper has can be used for digging bulk amounts of dirt, stone or common blocks for building projects.

Each tier should have uses after it has been surpassed:

Wood: Used for building, and making sticks for all other tools.
Stone: Used for building, and creating lots of other building materials.
Steel: Rails, Iron Bars, Flint and steel, Locked chests, Screwdrivers, and futuristic builds if you have enough.
Copper/Bronze: **Nothing ATM. There are bronze blocks, but that's pretty much it.**
Mese: Mese lamp. (Mese doesn't have that much usage either, although you can use it as an alternative tool material even after you find diamonds.)
Diamonds: Diamonds are the highest tier, and do not require too many other uses (At least until you have large quantities of diamonds, then you have a problem.)

This is probably why people complained about bronze being an odd addition to the game's progression. It just doesn't have enough uses to warrant a tier of tools.

**Comment by tenplus1** [comment] 2017-04-01 16:59
@c1ffisme - I agree'd with you that bronze tools should be twice as durable and the same strength as steel, and when I was starting out in Minetest I always made bronze tools until I could mine deep enough for mese and diamond...  I did however disagree that bronze should be aliased back to copper, we need both and should add more bronze additions to either the game or through a mod (springs, turbines, blades, coins etc.)

**Comment by C1ffisme** [comment] 2017-04-01 17:41
> we need both

Why? We don't have tin, and there isn't even a good alloying system at the moment. Combining ingots is a _lazy_ way of alloying. At the very least, I would appreciate a pulverizer or crusher to make dusts which can be mixed.

I suppose it would be a good idea to alias bronze tools to steel, though. Since aliasing them to copper would mean that the tools that were originally good enough to mine better ores are now only good for lower tier blocks.

**Comment by benrob0329** [comment] 2017-04-04 00:27
Copper is **way** to soft to make tools out of, in fact that's why its so good for wire.

**Comment by Ferk** [comment] 2017-04-08 09:19
The copper+steel thing never made sense to me.

Imho, if there's bronze, tin should be a thing.
The underground is huge and not very exciting in vanilla MTG, it could do with some more ores, specially now that it's agreed that MTG should be a full blown game.

Tin should be able to make buckets.
Maybe iron should be moved deeper and/or maybe the bronze recipe could be tweaked so that you get more bronze out of a lower amount of copper+tin. Then bronze tools will be cheaper and it might start being worth it.

**Comment by C1ffisme** [comment] 2017-04-08 19:56
@BlockMen 
> Copper is way to soft to make tools out of, in fact that's why its so good for wire.

We're playing a game with blocks that can float in the air and water that infinitely flows from a single source block. I don't think strong-ish copper is that far of a stretch.

> But even after you are already in the steel age, considering that steel can be used for so many other things than just tools, there would still be a place for bronze even if it wasn't better than steel. Many would prefer to not waste steel in their tools and keep using bronze

But, like you said, iron is so incredibly common. IMHO, I think iron should be common enough to be used as a regular building block, rather than being something that is difficult to build out of.

**Comment by Ferk** [comment] 2017-04-08 20:11
> I think iron should be common enough to be used as a regular building block, rather than being something that is difficult to build out of

In the "steel age" it should be easy to build out of. Just saying that it would be interesting if there was more progression and additional steps were required for efficient iron production, like for example using an improved furnace, so you will actually need to use bronze for a while.

**Comment by paramat** [comment] 2017-04-20 14:55
Tin is being added now.

> Bronze tools should be renamed to copper, and all bronze ingots and such will be aliased back to copper.
Copper tools will mine faster and longer than steel tools

No, copper is soft, many parts of MT are unrealistic but our normal material tools are fairly realistic in terms of material capability..

**Comment by sofar** [comment] 2017-04-22 04:11
We should consider migrating some tools to tin, like, the bucket.

**Comment by C1ffisme** [comment] 2017-04-22 04:16
> Tin is being added now.

(Slams head against keyboard.)

(Loudly groans "Nooooooooo....")

(Hesitates and starts commenting.)

Why??? We have barely enough uses for gold, and bronze. Why would you go and add another metal with only one use?

At the very least, you could have copper smelt directly into bronze, just like how iron smelts directly into steel. That would at least be consistent. But why would we add another mostly useless metal to a game that doesn't have any progression besides getting a stronger and faster pickaxe?

In fact, one of the reasons I suggested making copper/bronze a utility tool was because the addition of bronze into the tier system was originally controversial. But when it becomes a utility tool, it's not supposed to be any tier, it's there for a certain purpose. And it also means we can get rid of the dumb steel + copper recipe by removing steel from the recipe.

 > We should consider migrating some tools to tin, like, the bucket.

That only takes away from the value of iron. Now tin is more useful, but iron is far less so. In fact, none of the things besides tools that iron makes are needed for progression. (Well, actually, now that I think about it, they still weren't really needed. But still, I can live without crafting iron bars, rails, minecarts and even locked chests if I'm playing in singleplayer mode. Buckets are something that is needed for the simplest gameplay.)

**Comment by sofar** [comment] 2017-04-22 04:25
Well, farming is fairly essential, and buckets are really needed to get a decent pasture. Tin should be easily obtainable (shallow cave) while iron should be deeper down - 50+ deep perhaps?

**Comment by C1ffisme** [comment] 2017-04-22 04:36
> Well, farming is fairly essential

Not until hunger is implemented.

> and buckets are really needed to get a decent pasture.

Not if you build it on an ocean.

Still, it has uses, such as transporting the water to a pasture closer to your inland base, and water and lava can be used for decorative purposes, and lava can even be used as fuel. But my point is that iron bars, minecarts and rails do not share this many uses. (Especially since, whilst the minecart does offer faster travel, you still have to at least been there once to place rails. That means it's only real use is vertical travel from inside of mines back to home.)

**Comment by sofar** [comment] 2017-04-22 05:21
don't forget about ladders. That makes, with steel tools, like 10+ things and none for tin.

**Comment by benrob0329** [comment] 2017-04-22 10:34
A tin bucket? Heh, I wouldn't trust a tin if my life depended on it (especially if carrying molten lava)

**Comment by Fixer-007** [comment] 2017-04-22 13:23
Thats why main use for tin/bronze/copper will be in automation.

**Comment by C1ffisme** [comment] 2017-04-22 13:25
@sofar Easily trumped by the much cheaper wood ladders, and the far more pleasing option of building a staircase. (It fits into builds, sure, but that's the same case for iron bars and iron blocks.)

@Fixer-007 
> Thats why main use for tin/bronze/copper will be in automation.

How about... Hoppers? (And "LV Copper Wire" as a replacement for mesecons/redstone?)

**Comment by sofar** [comment] 2017-04-23 07:17
We're not going to radically add all sorts of new tools, but we have too many things that use steel and not other metals, so, let's tackle one problem at a time.

steel exclusive items:
* steel sign
* locked chest
* steel ladder
* rails
* locked door and locked trapdoor
* bucket
* cart
* steel bars
* vessels
* flint and steel
* screwdriver

all items that are made with steel. 

Copper exclusive items: **none**
Bronze exclusive items: **none**
Tin exclusive items: **none**


Random ideas: 

 - A tin bucket can hold water, a steel bucket is needed for lava.
- metal bottle in vessels should use tin instead
- screwdriver bronze
- Tin sign instead of steel sign (it's not locked anyway), or better yet, a copper sign

as for axe/shovel/etc. the extra time needed to make bronze isn't relevant, what's important is the mining depth and ore rarity. If making bronze axes takes more play time than steel axes, the durability should be longer for bronze.

**Comment by Fixer-007** [comment] 2017-04-23 11:18
^^ this is just silly :D

**Comment by Ferk** [comment] 2017-04-23 11:27
Real steel would rust with water, you'd need to add additional metals (chromium) to make it stainless.
So, tin for water buckets imho makes sense, as it's rust-proof from the ground up.

Imho, Minetest is too much like Minecraft, things like these would set it apart. Some people react like following Minecraft is the only logical way of how things should work.

**Comment by C1ffisme** [comment] 2017-04-23 17:49
> Imho, Minetest is too much like Minecraft, things like these would set it apart. Sometimes people react like following Minecraft is the only logical way of how things should work, when there are many things that could have been made more interesting, adding variety and more progression.

You are right, and I don't actually mind tin itself. The problem is that the game doesn't have a lot of uses for a new metal, and we already have too many metals without a use or without enough uses like gold and copper. Even mese used to be pretty useless before mese lamps came along.

**Comment by Fixer-007** [comment] 2017-04-23 21:35
@Ferk I was brainstorming in the process, rethinked it a bit.

**Comment by tenplus1** [comment] 2017-04-24 06:26
How about changing the word Steel in ladders, bucket, sign etc. to Metal instead, that way you could use multiple metals to make them?  e.g.  Metal Bucket, Metal Sign, Metal Door etc.

**Comment by C1ffisme** [comment] 2017-04-24 14:56
@tenplus1 That could work, but at that point there is almost no point in having multiple metals at all. Why gather up iron if tin or copper, being much more common, can do the same things?

(Besides that, I'd prefer copper stuff to look orange.)

**Comment by Fixer-007** [comment] 2017-11-26 23:18
More and more I look into this I feel renaming this whole topic to "Tools: rebalance needed"
![default](https://user-images.githubusercontent.com/16494741/33245417-3e331566-d310-11e7-95c8-fc8a070a2412.png)
![default](https://user-images.githubusercontent.com/16494741/33245416-2ea128ae-d310-11e7-8906-892e949dfbb2.png)

Observe this ^, we have 6 (SIX) tiers of weapons, with confusion added about bronze and mese, and we also have almost useless tin ore too

My new ideas about rebalancing tools:
* Still six tiers, but not boring and confusing like now.
* Make bronze as fast as diamond but as durable as iron (some trade off, bronze is already quite costly though, maybe invent special use for it?)
* MESE tools are derived from that hyped MESE block, so add special abilities for it, say pickaxe/shovel will pickup original blocks and axe will chop wood in bigger chunks?

**Comment by paramat** [comment] 2017-11-27 00:05
> Bronze tools cost much more mining and time (since you need to mine/smelt both iron and copper, and craft two times),

No, as you get 9 bronze ingots from 8 copper and 1 tin. Same work, just one ore is different.

> not boring and confusing

It's neither, just a lot of choice, bronze wasn't essential as there wasn't a hole in the progression that needed filling, so it's somewhat of a duplication.

> Make bronze as fast as diamond but as durable as iron

No, diamond should be superior in every way.

> (some trade off, bronze is already quite costly though)

See above, no more than steel.

> Another way is to dump bronze and mese tools entirely.

Nah too much breakage.

**Comment by Fixer-007** [comment] 2017-11-27 00:16
>No, as you get 9 bronze ingots from 8 copper and 1 tin. Same work, just one ore is different.

It is same work, but in different - more cumbersome way.
To make 1 iron tool you collect 3 iron ore (just mine one ore cluster) and smelt it = done fast, with 
bronze you need to collect 9 ores (need to visit at least three ore clusters = more time wasted) and then smelt them all (needs more coal), sure you get 9 ingots, but, who would do that since it is evidently less efficient.

**Comment by paramat** [comment] 2017-11-27 00:26
I see, but in the end you get multiple tools out of it.
The higher ability of bronze is the reward for a little more effort.

**Comment by Fixer-007** [comment] 2017-11-27 00:28
And don't forget tin starts at -32 while iron is readily available at 0. So it is obvious that bronze tools should be better than steel, via durability or speed.

**Comment by benrob0329** [comment] 2017-11-27 04:23
Idea:

Fist gets you wood tools and a wood shack to start, wood tools also start your mine. Stone tools are removed, as they are only used to get to iron (and how is stone good for anything but a knife or spear?).

Iron comes a little ways underground. It took a while to dig far enough down, but once you got it you have everything you need to smelt it into a fine *iron* pickax, which makes mining much faster.

Bronze is your next step, copper/tin is spotty at first, but eventually it becomes common enough to leave raw iron tools alone behind. (You need bronze to mine diamond, and it's still slow)

Diamond is the last big step, it takes a good while before you get enough to make a pickax, but once you do the stone cuts like butter. You'll need this to mine mese, which you've seen a few crystals laying around on your way down. Diamond become more common **way** far down, but still remains fairly rare.

Mese tools could be a long term plan. I like the idea that @Jordach had with Solar Plains (mese levels up over time, eventually becomes faster than diamond but it takes a lot of mining to get there) but some other effect could be thought of.

**Comment by MarkuBu** [comment] 2017-11-27 05:28
No, stone tools are relatively common, especially at the beginning. 

Wood tools are useless. The only tool I build is the pickaxe to get stone. An axe is totally useless since it takes nearly the same time to chop wood as with the hand

**Comment by paramat** [comment] 2017-11-27 05:42
> Stone tools are removed, as they are only used to get to iron

? They're necessary to get iron to make steel, they're a good part of the progression.

> Wood tools are useless.

? They're used to get stone, they're also a good part of the progression.
Bronze is the truly unnecessary step, and we admit that was a mistake.

**Comment by MarkuBu** [comment] 2017-11-27 06:24
>  They're used to get stone

That's the only reason for their existence. You don't need a shovel, you don't need an axe, you don't need a hoe

You have to build exactly one wooden tool to get stone. After that you can use it as fuel for the furnace.

**Comment by benrob0329** [comment] 2017-11-27 12:24
>You have to build exactly one wooden tool to get stone. After that you can use it as fuel for the furnace.

Thus, remove stone and spread wood out a little longer.

Bronze could be improved by having it a good while before diamond (in fact, let the player get settled in all tool tiers before advancing) and have it be required to get diamond.

**Comment by paramat** [comment] 2017-11-27 21:02
We can't remove tools, mods depend on them.

**Comment by Fixer-007** [comment] 2017-11-27 21:15
Then it is way of rebalancing them in some way.

**Comment by Fixer-007** [comment] 2018-02-15 20:23
>We can't remove tools, mods depend on them.

Can't you alias them to steel tools and mods will work just fine?

**Comment by paramat** [comment] 2018-02-16 08:44
Eww i expect it's not as simple.

**Comment by Ferk** [comment] 2018-02-16 13:49
It would have made more sense for there to exist pieces of rock scattered in the world that you can collect with the hands and use them for stone weapons (together with, eg, wood sticks from leaf blocks or found in the ground as roots), it's more intuitive, realistic and obvious than expecting a wood pickaxe to actually be able to break rock. Honestly, I think the only reason wood tools are there is because Minecraft uses them to obtain rock and early Minetest was trying too hard to copy Minecraft.

But the damage is done and unless MTG really wants to break compatibility, I suggest rather implement a system with more sense as a separate subgame (and also take the opportunity to fix things like tool_capabilities letting you break most things with bare hands and lacking proper high dig times that make impossible to have blocks that take really long to mine).

That said... if I were to change the iron-bronze balance in MTG, I would rather have the order be more logical and consistent with reality: "stone < bronze < steel" and make the steel tier harder to reach by requiring an upgrade to the "oven" to smelt it, encouraging the use of bronze in the meantime and requiring bronze for the upgrade. I already suggested it in the past: https://github.com/minetest/minetest_game/issues/2010#issuecomment-356567850

**Comment by Ezhh** [comment] 2018-02-16 18:45
> It would have made more sense for there to exist pieces of rock scattered in the world (wallmounted node showing 2 or 3 square pebbles) that you can collect with the hands

@Ferk This is something I explored when I started thinking about subgames, and I've seen at least one subgame that uses this approach, but I quickly realised there is a problem. Stone that appears as a decoration on mapgen is a non-renewable resource. This means on a server you quickly end up with an environment where new players can't find any without walking ridiculous distances. Trees on the other hand can be planted over and over again and don't run out.

**Comment by paramat** [comment] 2018-03-27 06:49
Hmmm actually a big issue is that steel should be more capable than bronze, but isn't in MTG, and the ores for bronze are deeper than iron which suggests bronze shoud be more capable. However iron is available just below the surface so copper and tin can't be above them.

Copper and tin being more specialist ores (for crafting more specialist items) could perhaps be the reason for them being deeper (y = -128) than iron (y = 0), however the bronze tools don't make sense in the tool progression. What a mess bronze is, there really isn't a gap for bronze on the tool progression.

I suggest we swap the abilities of bronze and steel tools so that steel > bronze as it should be.
I think the ores depth progression is good as it is, i wouldn't want iron, copper and tin to all be available at y= 0.

I'll reread about the addition of bronze.

**Comment by Ezhh** [comment] 2018-03-27 09:28
> I suggest we swap the abilities of bronze and steel tools so that steel > bronze as it should be.
I think the ores depth progression is good as it is,

So the more powerful tool is quicker to find materials for and easier to make? No one will ever use bronze tools in this scenario. (Which isn't to say it shouldn't be changed anyway... but how to justify the existence of bronze tools?)

**Comment by Fixer-007** [comment] 2018-03-27 11:56
>I suggest we swap the abilities of bronze and steel tools so that steel > bronze as it should be.

Then it will be completely redundant and useless. 
Steel pickaxe = 1 coal + 3 iron, bronze pickaxe = 1 coal + 8 copper + 1 tin, who will use it?

**Comment by Ezhh** [comment] 2018-03-27 12:16
I agree with Fixer completely. (Assuming he means sticks, not coal).

We basically have a bad situation that's not easy to solve because it wasn't given any serious thought to begin with, and it's now really difficult (maybe impossible) to set right without some kind of disruption that will manage to make someone or other angry. 

I'll try and take a proper look at the tool situation tonight to see if I can think of anything. I'm just somewhat reluctant because it's something it would be easy to pour time I don't have into, and then it would collapse into endless debate/disagreement anyway. On the other hand, it's quite possibly important enough to really push for change here, since the tool balance issue is, in my opinion, one of the biggest problems with MTG.

**Comment by Ezhh** [comment] 2018-03-27 16:59
So after trying to make sense of it all, this is what I have. This is just the problems (there are probably more as well). Sorry for the length.

Problem 1
----

I'm only going to look at picks in this analysis. This highlights a problem in and of itself: picks are the only tool for which there seems to be ANY real progression at all, other than speed/durability related (and sometimes there is not even that). Having so many versions of any tool other than picks is therefore of questionable use before we get started.

With that said, moving to picks:

Problem 2
---

What is going on with the levels? 

stone_with_iron is cracky = 2 and can be dug by stone pick but not wood pick. Groupcaps give:
	Wood: cracky = {times={[3]=1.60}, uses=10, maxlevel=1},
	Stone: cracky = {times={[2]=2.0, [3]=1.00}, uses=20, maxlevel=1},

So we see that a higher level node is actually WEAKER (cracky = 3 is weaker than cracky = 2). This is very counter-intuitive. This also shows that omitting a level (as can be seen with wood not able to mine stone_with_iron) means nodes at that level simply can't be mined.

So why do we have a SECOND way of implementing this? (Notably, one where higher level means more difficulty to dig, so we have one difficulty scale with ascending, one with descending order!)

Diamond Block has: groups = {cracky = 1, level = 3},
It can be dug by mese or diamond pick because they have maxlevel=3 for cracky, whereas steel and bronze, which could usually dig cracky=1, can't touch this node.

All I can think of is it's so time to dig can be different. For example, compare:
	stone_with_messe:  groups = {cracky = 1},
	mese: groups = {cracky = 1, level = 2},

Mese takes longer to dig, even though the exact same tools can dig both, because all tools with maxlevel=2 or higher can also handle cracky = 1. (Possibly wasted potential to have more distinct groups for tool progression here?)

In other words, between what can be dug and differing dig times, more than three levels are actually needed/desired, but apparently we're limited to three:
https://github.com/minetest/minetest/blob/040b878cd5f77f6b44622b7c00255b4981500dc8/doc/lua_api.txt#L5031

Now if what lua_api says is just an MTG restriction, can't we get more levels by changing MTG?
If this is an engine restriction... regardless of MTG it should surely be changed (what if I want to make a game with 4 or 5 levels of tool?).

From review of default/nodes.lua, only ONE item (diamond block) is level = 3.
Eight are level = 2 (metal blocks, mese block, obsidian nodes).
So this second method of deciding digging difficulty is barely used.

In summary: overly complicated and somewhat contradictory tool levels system that isn't really even utilised very well. And of course, any attempt to improve it will break things.


Problem 3
----

Given the twisted up complexity shown in problem 2, you'd think we could have a nice deep system for progression.

Wrong: it takes only a couple of minutes to give yourself the ability to dig... oh, pretty much everything.

1 tree node creates wooden pick (with 2 sticks to spare!).
Dig 2 stone, combine with the 2 remaining sticks to make stone pick.
Dig 8 stone, 3 iron ore, 1 coal. Craft furnace and make 3 steel ingots. Get one more tree node and you have steel pick. 

If you know what you're doing, this takes maybe a couple of minutes from the time you find your first tree, and now you can break every single cracky node in game apart from one (and since you can get diamonds other than as diamond blocks, that one is not a big deal anyway).

Yes, getting better picks beyond this point makes you more efficient, but shouldn't reaching the "you can get every single item in game with the tools you have now" progression point require more than a couple of minutes to reach?


Problem 4
---

Bronze ranks higher than steel?? Uhhhhhh.


Problem 5
---

Iron ore becomes steel ingots becomes iron bars!!

Problem 6
---

lua_api.txt is very unhelpful when it comes to understanding tools... Difficult to fix what it's not easy to get information on. 

For example, let's look at max_drop_level. Ctrl+F for "max_drop_level" isn't helpful. One hit on line 1846, one on 5059. Neither area of the document seems to explain what it means there.

Then 1806 gives:
	#### Maximum drop level
	Suggests the maximum level of node, when dug with the tool, that will drop
	it's useful item. (e.g. iron ore to drop a lump of iron).

This is listed under "Groups" (perhaps "Tools definition" above it is meant to be the heading, but they are the same level?)... either way, since "max_drop_level" doesn't appear in this section it's difficult to find this information when trying to check what it means, and going in the opposite direction, it's difficult to read this information and then know how to actually use it.
#

**Comment by paramat** [comment] 2018-03-28 10:41
> So the more powerful tool is quicker to find materials for and easier to make? No one will ever use bronze tools in this scenario

> Then it will be completely redundant and useless.

:) yes indeed this is the problem, either it doesn't make sense (bronze more capable than steel) or bronze is not worth using.

Because bronze tools were such a mistake, i'm beginning to wonder if we could phase them out, perhaps by a first step of removing the crafting recipes. Since tools get used up they will disappear from worlds, then later we can completely remove bronze tools.
Bronze ingots will have to stay because many mods use these to craft other items.
Then we can leave steel tools having the capabilities they currently have.
This will need discussion on the forum first, mods may depend on bronze tools as crafting recipes for something else.

However Ezhh i agree with your opinion that it's a mess that mostly cannot be fixed due to so much depending on MTG being the way it is (this can also be applied to many areas of MTG).
There are some ideas being suggested for radical changes and new systems that make sense but i think these can only go into new games.
I suggest we mostly leave the tool mess as it is, it will be boring, time consuming, controversial and disruptive work that breaks mods.
//////////////

Problem 2:
Levels and digging times still make my head hurt, they're confusing. I think this has to be left as it is because of mods (and i can't face working on it).

Problem 3:
Yeah, but doubt we can change it.

Problem 5:
Not a problem, in the 'iron smelts to steel' issue it is shown that iron does indeed process to steel, MTG just leaves out the specific process (air blasting to reduce carbon) for simplicity.
My PR renames bars to complete the fix.

**Comment by benrob0329** [comment] 2018-03-28 12:34
I do believe that the most missing community would rather fix their mods (which will eventually break anyways) if it means fixing this broken mess.

I'll make a forum poll though to see.

**Comment by rubenwardy** [comment] 2018-03-28 12:51
The problem isn't the bronze tools, the problem is with the wooden tools. I suggest somehow allowing gathering stones from another source - say rocks and boulders - then remove wood picks as they don't make sense. There should then be floating point groups in the engine, to allow a higher range of digging speeds. Obtaining higher level tools should then be made harder

**Comment by paramat** [comment] 2018-03-28 13:13
benrob0329 the poll is a little problematic as it says 'fix your mods' which sounds trivial when it would actually be rethink and rewrite your mods. Also, many mods are not maintained so it's also a case of 'rewriting all mods you use whether or not you understand them' which doesn't sound good to me.
It also goes against our policy of not causing mass-breakage of mods.
The poll will probably get support due to how it's worded but it is somewhat misleading.

**Comment by paramat** [comment] 2018-03-28 13:17
rubenwardy that makes sense but what makes sense is not the issue, MTG is a mod base that many mods rely on to be as it is, so we can't change it much.

**Comment by rubenwardy** [comment] 2018-03-28 13:19
Lol. Not many mods go that deeply into tool mechanics, so in most cases it would just be adjusting groups

**Comment by paramat** [comment] 2018-03-28 13:32
Ezhh about problem 2, the times and levels system in the engine may be fine, after all it has been maintained and improved over years. I found this comment by myself in creative:
```
+	-- Dig time is modified according to difference (leveldiff) between tool
+	-- 'maxlevel' and node 'level'. Digtime is divided by the larger of
+	-- leveldiff and 1.
```
rubenwardy, ok, what you suggest may be possible.

benrob0329 a poll needs to be specific, for example i was thinking of a thread or poll that asked how essential bronze tools are to your mods and whether it would be ok to phase them out over time as i suggested, and what problems this would cause.

**Comment by paramat** [comment] 2018-03-28 15:03
The wooden tools aren't much of an issue because that's a realism issue and MTG isn't that realistic.
Bronze and steel though are inconsistent with the internal logic of the game, which is why they are a big issue.
The wooden tools in MTG are just the way they are because it copies MC. They are somewhat abstract symbols for the progression of humans through the various industrial ages:
Punching trees: Monkeys.
Wooden tools: Smart monkeys with sticks.
Stone tools: Early humans "Stone age".
Bronze tools should obviously be next for the "Bronze age" (but they aren't).
Steel tools: Early industrial revolution, steampunk theme, "Industrial revolution".
Diamond tools: Modern usage of 'industrial diamonds' in tools, "Current day".
Mese tools: Discovery of magickal substances or alien technology, "fantasy, future or scifi".

It doesn't matter if wooden tools breaking stone doesn't make sense, it's just the way MTG is, the internal logic.

The poll is too vague for the result to mean anything, people don't know what they are voting on, there is no detailed suggestion and no way to know how much breakage there will be. Just to be clear the result will not mean much and will not decide anything.
The important part will be the discussion in the thread.

**Comment by paramat** [comment] 2018-04-06 14:11
#2103 simplifies and rebalances hoes, and attends to #1252

**Comment by paramat** [comment] 2018-04-08 16:41
Looking at tool capabilities bronze is not quite as imbalanced as i thought, it has the same capabilities as steel but more uses. I would still prefer it had less capability than steel.
PR #2107 allows us the option of swapping the depths of iron and tin/copper if desired.

**Comment by paramat** [comment] 2018-04-08 19:47
So i have a new suggestion:
Reduce bronze tool capabilities and uses to place them below steel tools, then swap the depths of the ores (y = -64 and y = -128).
Then we can go Stone age > Bronze age > Steel age.

**Comment by Fixer-007** [comment] 2018-04-08 21:35
Can someone post current tools capabilities table for better understanding?

**Comment by paramat** [comment] 2018-04-19 04:45
PR #2110

**Comment by paramat** [comment] 2018-04-20 19:15
#2110 merged.
Feel free to continue discussion but this seems mostly sorted now.

**Closed by paramat** 2018-04-20 19:15 UTC
Labels: Balance, Request / Suggestion
