### ISSUE TITLE
Prod Feature request

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest_game#525] opened 2015-06-01 17:16 UTC
Add a Prod function, so i can prod guys into lava :-D

**Comment by C1ffisme** [comment] 2015-06-01 17:18
You mean knockback?

I already made an issue on that.

So you WANT to push people into lava?

**Comment by est31** [comment] 2015-08-19 14:04
Dupe of https://github.com/minetest/minetest/issues/2394
Also, the wrong tracker.

**Closed by est31** 2015-08-19 14:04 UTC
